// Owns: every REST endpoint definition (SPEC §10 plus the additions recorded in docs/PROGRESS.md), grouped by area.
// The Worker validates params/query/body with these and the PWA calls through them. A Binary body is sent as
// application/octet-stream; every other body is JSON. offline: 'queue' marks idempotent writes (client-generated id)
// the PWA may hold in its offline queue.
import * as z from 'zod'
import {
  AiJob,
  AiWorkoutRequest,
  Binary,
  ChatHistoryQuery,
  ChatMessage,
  ChatSend,
  ChatSent,
  DateRange,
  DaysQuery,
  DaySummary,
  DayView,
  EquipmentItem,
  EquipmentUpdate,
  EventsQuery,
  EventsResponse,
  Exercise,
  ExerciseCreate,
  ExerciseExclusion,
  ExerciseHistory,
  ExerciseQuery,
  ExclusionCreate,
  ExportManifest,
  ExportPage,
  ExportTableQuery,
  Fast,
  FastEnd,
  FastListQuery,
  FastPlan,
  FastStart,
  Favourite,
  FavouriteCreate,
  FavouritePatch,
  FileKey,
  Food,
  FoodCreate,
  FoodSearchQuery,
  HealthImport,
  HealthImportResult,
  HealthIngest,
  HealthIngestResult,
  Id,
  ImportFileQuery,
  ImportPage,
  ImportResult,
  IsoWeek,
  JobRef,
  LocalDate,
  Meal,
  MealCreate,
  MealListQuery,
  MealPatch,
  MealPhoto,
  MealPhotoUploadQuery,
  Measurement,
  MeasurementsCreate,
  NoteResponse,
  Ok,
  PhotoListQuery,
  PhotoUploadQuery,
  PlanVersion,
  ProgressPhoto,
  ProposalDecision,
  PushSubscribe,
  PushSubscription,
  Scan,
  ScanPatch,
  ScanUploaded,
  ScanUploadQuery,
  SessionCreate,
  SessionFinish,
  SessionFinishResult,
  SessionSet,
  SetCreate,
  SetPatch,
  SettingsUpdate,
  SettingsView,
  SignedFile,
  SignedFileQuery,
  SleepLog,
  SleepLogCreate,
  StepLog,
  StepLogCreate,
  Template,
  TemplateCreate,
  TemplatePatch,
  TrendSeries,
  Upload,
  WaterLog,
  WaterLogCreate,
  WeekPlan,
  WeekPlanCreate,
  WeekPlanQuery,
  WeeklyReview,
  WeighIn,
  WeighInCreate,
  WeighInUpdate,
  WorkoutSession,
} from '../schemas/index'
import { defineEndpoint } from './endpoint'

const IdParams = z.object({ id: Id })
const DateParams = z.object({ date: LocalDate })
const WeekParams = z.object({ week: IsoWeek })
const FileKeyParams = z.object({ key: FileKey })

export const endpoints = {
  system: {
    health: defineEndpoint({
      method: 'GET',
      path: '/api/health',
      response: z.object({ ok: z.boolean(), tz: z.string() }),
    }),
  },

  day: {
    get: defineEndpoint({ method: 'GET', path: '/api/day/:date', params: DateParams, response: DayView }),
    range: defineEndpoint({ method: 'GET', path: '/api/days', query: DaysQuery, response: z.array(DaySummary) }),
    events: defineEndpoint({ method: 'GET', path: '/api/events', query: EventsQuery, response: EventsResponse }),
    note: defineEndpoint({ method: 'GET', path: '/api/notes', response: NoteResponse }),
  },

  body: {
    createWeight: defineEndpoint({ method: 'POST', path: '/api/weights', body: WeighInCreate, response: WeighIn, offline: 'queue' }),
    updateWeight: defineEndpoint({
      method: 'PUT',
      path: '/api/weights/:id',
      params: IdParams,
      body: WeighInUpdate,
      response: WeighIn,
      offline: 'queue',
    }),
    createMeasurements: defineEndpoint({
      method: 'POST',
      path: '/api/measurements',
      body: MeasurementsCreate,
      response: z.array(Measurement),
      offline: 'queue',
    }),
    trend: defineEndpoint({ method: 'GET', path: '/api/trend', query: DateRange, response: TrendSeries }),
  },

  nutrition: {
    listMeals: defineEndpoint({ method: 'GET', path: '/api/meals', query: MealListQuery, response: z.array(Meal) }),
    createMeal: defineEndpoint({ method: 'POST', path: '/api/meals', body: MealCreate, response: Meal, offline: 'queue' }),
    updateMeal: defineEndpoint({
      method: 'PATCH',
      path: '/api/meals/:id',
      params: IdParams,
      body: MealPatch,
      response: Meal,
      offline: 'queue',
    }),
    deleteMeal: defineEndpoint({ method: 'DELETE', path: '/api/meals/:id', params: IdParams, response: Ok, offline: 'queue' }),
    addMealPhoto: defineEndpoint({
      method: 'POST',
      path: '/api/meals/:id/photos',
      params: IdParams,
      query: MealPhotoUploadQuery,
      body: Upload,
      response: MealPhoto,
      offline: 'queue',
    }),
    searchFoods: defineEndpoint({ method: 'GET', path: '/api/foods/search', query: FoodSearchQuery, response: z.array(Food) }),
    createFood: defineEndpoint({ method: 'POST', path: '/api/foods', body: FoodCreate, response: Food, offline: 'queue' }),
    listFavourites: defineEndpoint({ method: 'GET', path: '/api/favorites', response: z.array(Favourite) }),
    createFavourite: defineEndpoint({
      method: 'POST',
      path: '/api/favorites',
      body: FavouriteCreate,
      response: Favourite,
      offline: 'queue',
    }),
    updateFavourite: defineEndpoint({
      method: 'PATCH',
      path: '/api/favorites/:id',
      params: IdParams,
      body: FavouritePatch,
      response: Favourite,
      offline: 'queue',
    }),
  },

  water: {
    create: defineEndpoint({ method: 'POST', path: '/api/water', body: WaterLogCreate, response: WaterLog, offline: 'queue' }),
  },

  fasting: {
    start: defineEndpoint({ method: 'POST', path: '/api/fasts/start', body: FastStart, response: Fast, offline: 'queue' }),
    end: defineEndpoint({
      method: 'POST',
      path: '/api/fasts/:id/end',
      params: IdParams,
      body: FastEnd,
      response: Fast,
      offline: 'queue',
    }),
    plan: defineEndpoint({ method: 'POST', path: '/api/fasts/plan', body: FastPlan, response: Fast, offline: 'queue' }),
    list: defineEndpoint({ method: 'GET', path: '/api/fasts', query: FastListQuery, response: z.array(Fast) }),
  },

  health: {
    createSleep: defineEndpoint({ method: 'POST', path: '/api/sleep', body: SleepLogCreate, response: SleepLog, offline: 'queue' }),
    createSteps: defineEndpoint({ method: 'POST', path: '/api/steps', body: StepLogCreate, response: StepLog, offline: 'queue' }),
    importHealth: defineEndpoint({
      method: 'POST',
      path: '/api/imports/health',
      body: HealthImport,
      response: HealthImportResult,
      offline: 'never',
    }),
    /** iOS Shortcut webhook; Bearer HEALTH_WEBHOOK_TOKEN instead of Access. Never called by the PWA. */
    ingest: defineEndpoint({
      method: 'POST',
      path: '/api/ingest/health',
      body: HealthIngest,
      response: HealthIngestResult,
      offline: 'never',
    }),
  },

  training: {
    listExercises: defineEndpoint({ method: 'GET', path: '/api/exercises', query: ExerciseQuery, response: z.array(Exercise) }),
    createExercise: defineEndpoint({
      method: 'POST',
      path: '/api/exercises',
      body: ExerciseCreate,
      response: Exercise,
      offline: 'queue',
    }),
    getEquipment: defineEndpoint({ method: 'GET', path: '/api/equipment', response: z.array(EquipmentItem) }),
    updateEquipment: defineEndpoint({
      method: 'PUT',
      path: '/api/equipment',
      body: EquipmentUpdate,
      response: z.array(EquipmentItem),
      offline: 'queue',
    }),
    createExclusion: defineEndpoint({
      method: 'POST',
      path: '/api/exclusions',
      body: ExclusionCreate,
      response: ExerciseExclusion,
      offline: 'queue',
    }),
    listTemplates: defineEndpoint({ method: 'GET', path: '/api/templates', response: z.array(Template) }),
    createTemplate: defineEndpoint({
      method: 'POST',
      path: '/api/templates',
      body: TemplateCreate,
      response: Template,
      offline: 'queue',
    }),
    updateTemplate: defineEndpoint({
      method: 'PATCH',
      path: '/api/templates/:id',
      params: IdParams,
      body: TemplatePatch,
      response: Template,
      offline: 'queue',
    }),
    startSession: defineEndpoint({
      method: 'POST',
      path: '/api/sessions',
      body: SessionCreate,
      response: WorkoutSession,
      offline: 'queue',
    }),
    getSession: defineEndpoint({ method: 'GET', path: '/api/sessions/:id', params: IdParams, response: WorkoutSession }),
    logSet: defineEndpoint({
      method: 'POST',
      path: '/api/sessions/:id/sets',
      params: IdParams,
      body: SetCreate,
      response: SessionSet,
      offline: 'queue',
    }),
    updateSet: defineEndpoint({
      method: 'PATCH',
      path: '/api/sets/:id',
      params: IdParams,
      body: SetPatch,
      response: SessionSet,
      offline: 'queue',
    }),
    deleteSet: defineEndpoint({ method: 'DELETE', path: '/api/sets/:id', params: IdParams, response: Ok, offline: 'queue' }),
    finishSession: defineEndpoint({
      method: 'POST',
      path: '/api/sessions/:id/finish',
      params: IdParams,
      body: SessionFinish,
      response: SessionFinishResult,
      offline: 'queue',
    }),
    exerciseHistory: defineEndpoint({
      method: 'GET',
      path: '/api/history/exercises/:id',
      params: IdParams,
      response: ExerciseHistory,
    }),
  },

  plan: {
    get: defineEndpoint({ method: 'GET', path: '/api/plan', response: PlanVersion }),
    versions: defineEndpoint({ method: 'GET', path: '/api/plan/versions', response: z.array(PlanVersion) }),
    restoreVersion: defineEndpoint({
      method: 'POST',
      path: '/api/plan/versions/:id/restore',
      params: IdParams,
      response: PlanVersion,
    }),
    acceptProposal: defineEndpoint({
      method: 'POST',
      path: '/api/proposals/:id/accept',
      params: IdParams,
      response: ProposalDecision,
    }),
    rejectProposal: defineEndpoint({
      method: 'POST',
      path: '/api/proposals/:id/reject',
      params: IdParams,
      response: ProposalDecision,
    }),
    listWeekPlans: defineEndpoint({ method: 'GET', path: '/api/week-plans', query: WeekPlanQuery, response: z.array(WeekPlan) }),
    createWeekPlan: defineEndpoint({ method: 'POST', path: '/api/week-plans', body: WeekPlanCreate, response: WeekPlan }),
    applyWeekPlan: defineEndpoint({
      method: 'POST',
      path: '/api/week-plans/:id/apply',
      params: IdParams,
      response: WeekPlan,
    }),
  },

  ai: {
    workout: defineEndpoint({ method: 'POST', path: '/api/ai/workout', body: AiWorkoutRequest, response: JobRef }),
    chat: defineEndpoint({ method: 'POST', path: '/api/ai/chat', body: ChatSend, response: ChatSent }),
    chatHistory: defineEndpoint({ method: 'GET', path: '/api/ai/chat', query: ChatHistoryQuery, response: z.array(ChatMessage) }),
    job: defineEndpoint({ method: 'GET', path: '/api/jobs/:id', params: IdParams, response: AiJob }),
  },

  scans: {
    upload: defineEndpoint({ method: 'POST', path: '/api/scans', query: ScanUploadQuery, body: Upload, response: ScanUploaded }),
    confirm: defineEndpoint({ method: 'PATCH', path: '/api/scans/:id', params: IdParams, body: ScanPatch, response: Scan }),
    list: defineEndpoint({ method: 'GET', path: '/api/scans', response: z.array(Scan) }),
  },

  photos: {
    upload: defineEndpoint({
      method: 'POST',
      path: '/api/photos',
      query: PhotoUploadQuery,
      body: Upload,
      response: ProgressPhoto,
      offline: 'queue',
    }),
    list: defineEndpoint({ method: 'GET', path: '/api/photos', query: PhotoListQuery, response: z.array(ProgressPhoto) }),
  },

  reviews: {
    list: defineEndpoint({ method: 'GET', path: '/api/reviews', response: z.array(WeeklyReview) }),
    get: defineEndpoint({ method: 'GET', path: '/api/reviews/:week', params: WeekParams, response: WeeklyReview }),
    pdf: defineEndpoint({ method: 'POST', path: '/api/reviews/:week/pdf', params: WeekParams, response: SignedFile }),
  },

  export: {
    manifest: defineEndpoint({ method: 'GET', path: '/api/export', response: ExportManifest }),
    table: defineEndpoint({ method: 'GET', path: '/api/export/tables', query: ExportTableQuery, response: ExportPage }),
    importTable: defineEndpoint({ method: 'POST', path: '/api/import', body: ImportPage, response: ImportResult, offline: 'never' }),
    importFile: defineEndpoint({
      method: 'POST',
      path: '/api/import/files',
      query: ImportFileQuery,
      body: Upload,
      response: Ok,
      offline: 'never',
    }),
  },

  settings: {
    get: defineEndpoint({ method: 'GET', path: '/api/settings', response: SettingsView }),
    update: defineEndpoint({ method: 'PATCH', path: '/api/settings', body: SettingsUpdate, response: SettingsView }),
  },

  push: {
    subscribe: defineEndpoint({ method: 'POST', path: '/api/push/subscribe', body: PushSubscribe, response: PushSubscription }),
  },

  files: {
    /** Our HMAC-signed, expiring file URL. Used as an <img src>/download link, not through the JSON client. */
    get: defineEndpoint({
      method: 'GET',
      path: '/api/files/:key',
      params: FileKeyParams,
      query: SignedFileQuery,
      response: Binary,
    }),
  },
} as const
