// Owns: every visual token (SPEC §11) — ink, surfaces, borders, the accent and its tints, the dark surface, status
// palettes, the metric palette and its tints, the type scale, spacing, radii, shadows, motion, chart style, muscle-map
// steps — and the MUI theme built from them. Nothing else in the app hard-codes a colour. Charts read `tokens` directly
// so SVG output carries literal hex colours for print and the PDF archive.
//
// Visual language (2026-10-07, "2a" — docs/design/design_handoff_fitness_2a/README.md, the shadcn/ui idiom): white
// page, hairline-bordered white cards (1 px #E4E4E7, radius 12, a 1 px whisper of shadow), #FAFAFA tinted panels,
// #F4F4F5 fills for tracks, hovers and segmented controls, zinc ink, and the accent blue #166FE5 spent on the primary
// action, the trend line and the current point. One family, Geist (self-hosted, `@fontsource-variable/geist`, OFL),
// with the platform stack behind it. Motion is one staggered entrance (cards rise 26 px and fade in over 700 ms on an
// expo-out curve, 60–90 ms apart), number count-ups (~1.6 s) and chart/bar/ring draws (1.4–1.6 s); under reduced
// motion everything appears in place with a 200 ms cross-fade.
//
// Names: every token name the app imported before 2a is kept, re-valued (a page restyled later still compiles and
// already looks closer); 2a's own names are added beside them. Where an old name now means a 2a role it says so —
// `ink.secondary` IS 2a's "muted" (#71717A, every caption and description), and `ink.label` is 2a's "secondary"
// (#52525B, stat labels and row values). The cleanup phase removes the legacy names nothing uses any more.
//
// Accessibility decisions (measured on white unless stated, WCAG 2.2 AA):
//   • Text ink: #09090B 19.9:1, #3F3F46 10.4:1, #52525B 7.7:1, #71717A 4.83:1 (4.63 on #FAFAFA). #A1A1AA is 2.56:1,
//     so `ink.faint` is for glyphs, chevrons, dots and dashed target lines only — never for text that carries
//     information. That moves three 2a details to `ink.muted`: chart axis labels, input placeholders and the
//     struck-through "before" value of a proposal.
//   • Unselected segments sit on #F4F4F5, where #71717A measures 4.40:1, so they use `ink.label` (7.03:1) instead.
//   • The info-blue chip's text is `accent.deep` (#1263CC, 5.24:1 on #EFF6FF): #166FE5 on it is only 4.35:1.
//   • Status text on its own tint: success 4.57, warning 4.51 (banner body uses `warning.deep` 6.37), danger 5.30,
//     info 9.52. White on `accent.main` 4.73, on `accent.deep` 5.70, on `dark.bg` 19.9.
//   • Metric colours: the app's measured palette is kept (README: "where the app already has a measured colour for a
//     metric, keep it and map the tints as 12 % / 16 % alphas of it"). Every one clears 3:1 on white (WCAG 1.4.11);
//     2a's illustrative water #0EA5E9 would not (2.77:1). Tints are `metricTint()` / `metricSoft()`.
//   • Focus: buttons and every ButtonBase get a 2 px #166FE5 ring 2 px out (MUI 9's `focusVisible` theme option, which
//     also insets the ring on clip-prone rows); inputs get the 2a ring — blue border + 3 px #DBEAFE (WCAG 2.4.7).
//   • Touch: on a coarse pointer every button, icon button, chip, segment and menu row keeps a 44 px target and inputs
//     take 16 px text (iOS Safari zooms into anything smaller); the 2a desktop sizes apply to a fine pointer.
import { createTheme } from '@mui/material/styles'
import { springCurve, SPRING_DEFAULT } from './motion/spring'

/** The two ends of the ink scale, named so nothing below hard-codes a white or an ink twice. */
const WHITE = '#FFFFFF'
const INK = '#09090B'

/** 2a's zinc ramp, as it is used: text → body copy → labels → muted → faint → disabled → border → fill → panel. */
const ZINC = {
  950: INK,
  700: '#3F3F46',
  600: '#52525B',
  500: '#71717A',
  400: '#A1A1AA',
  300: '#D4D4D8',
  200: '#E4E4E7',
  100: '#F4F4F5',
  50: '#FAFAFA',
} as const

/** The accent blue and its tints (2a: blue-50 … blue-400 beside the brand blue). */
const BLUE = {
  main: '#166FE5',
  hover: '#1263CC',
  50: '#EFF6FF',
  100: '#DBEAFE',
  200: '#BFDBFE',
  300: '#93C5FD',
  400: '#60A5FA',
} as const

/**
 * The sheet spring — critically damped, response 0.35 s — as a CSS `linear()` curve, generated by the solver in
 * `motion/spring.ts`. 2a's entrance is a fixed 700 ms expo-out (`enterEasing()`), so this is now only for layers a
 * gesture drives (the bottom sheet). `null` where the browser cannot parse a `linear()` easing.
 */
const SPRING = springCurve(SPRING_DEFAULT)

/** 2a's entrance curve: cubic-bezier(.16, 1, .3, 1), an expo-out. */
const EXPO_OUT = 'cubic-bezier(0.16, 1, 0.3, 1)'

/** The entrance length, ms (2a: "cards rise 26 px and fade in over 700 ms"). */
const ENTER_DURATION = 700

const METRIC = {
  weight: '#166FE5',
  calories: '#C2410C',
  protein: '#7C3AED',
  carbs: '#A16207',
  fat: '#0E7490',
  water: '#0369A1',
  steps: '#15803D',
  sleep: '#4338CA',
  fatMass: '#9D174D',
  lean: '#047857',
  fasting: '#475569',
} as const

export const tokens = {
  font: {
    /** Geist (variable, self-hosted by `main.tsx`), then the platform's own face. */
    family:
      '"Geist Variable", Geist, system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, sans-serif',
    /** Weights: 400 body, 500 labels and buttons, 600 headings and numbers — emphasis by weight, not by size. */
    weight: { body: 400, label: 500, heading: 600, number: 600 },
    /**
     * The 2a scale, in px. Legacy names are kept and re-valued to the 2a role they now play:
     * largeTitle = page title (h1), title1 = a primary card's h2 (Train's "Upper B — Pull"), sectionTitle / cardTitle
     * = section and card-header titles, itemTitle = a proposal / exercise / template name, body = body copy,
     * emphasis = a running paragraph or an emphasised line, small = dense body, descriptions and tables,
     * label = a stat card's label, caption = captions and card descriptions, micro = uppercase group labels.
     */
    size: {
      largeTitle: 26,
      title1: 22,
      sectionTitle: 16,
      cardTitle: 16,
      itemTitle: 15,
      body: 14,
      emphasis: 14,
      small: 13,
      label: 13,
      caption: 12,
      micro: 11,
      /** Numbers: a stat card's value (28), a medium value / phone stat (22), the Today chart value (34), the hero (40). */
      bigNumber: 28,
      bigNumberSmall: 22,
      bigNumberMedium: 34,
      bigNumberLarge: 40,
      statNumber: 28,
    },
    /** Letter-spacing in px (2a's em values × the size). Only the large steps tighten; micro labels open up. */
    tracking: {
      largeTitle: -0.52,
      title1: -0.33,
      sectionTitle: 0,
      cardTitle: 0,
      itemTitle: 0,
      body: 0,
      emphasis: 0,
      small: 0,
      label: 0,
      caption: 0,
      micro: 0.44,
      /** A stat value (28 × −.02em). */
      number: -0.56,
      /** A hero value (40 × −.03em). */
      hero: -1.2,
    },
    /** 2a's letter-spacing as em, for anything sized off-scale: titles and stats −.02em, heroes −.03em, micro +.04em. */
    em: { title: '-0.02em', number: '-0.02em', hero: '-0.03em', micro: '0.04em' },
    leading: {
      largeTitle: 1.2,
      title1: 1.25,
      sectionTitle: 1.4,
      cardTitle: 1.4,
      itemTitle: 1.35,
      body: 1.5,
      emphasis: 1.55,
      small: 1.5,
      label: 1.4,
      caption: 1.4,
      micro: 1.3,
      number: 1,
    },
  },
  ink: {
    /** Primary text. */
    text: INK,
    /** Long-form copy (the coach note) and inactive sidebar items. */
    body: ZINC[700],
    /** 2a "secondary": stat labels, row values, neutral chip text. */
    label: ZINC[600],
    /** 2a "muted" under its legacy name: every caption, description, unit and subtitle (4.83:1). */
    secondary: ZINC[500],
    /** 2a "muted" (same value as `secondary`; new code uses this name). */
    muted: ZINC[500],
    /** Glyphs, chevrons, dots, dashed target lines. 2.56:1 — never informational text. */
    faint: ZINC[400],
    /** Disabled text and the dashed border of an empty slot. */
    disabled: ZINC[300],
    /** Card and control borders, table head rules. */
    border: ZINC[200],
    /** Row hairlines inside a card. */
    hairline: ZINC[100],
    /** The dashed border of an empty slot. */
    dashed: ZINC[300],
    /** An outline that must identify a control on its own: ≥3:1 on white and #FAFAFA (WCAG 1.4.11). */
    control: '#8E8E96',
    card: WHITE,
    /** The page itself (2a: white; cards are separated by their hairline). */
    page: WHITE,
    /** Tinted panels and the sidebar. */
    panel: ZINC[50],
    /** Legacy name for a raised well inside a card — now the 2a panel tint. */
    sunken: ZINC[50],
    /** Muted fill: progress tracks, segmented-control track, hover, neutral chip. */
    fill: ZINC[100],
  },
  /** The action colour. `main` carries white text at 4.73:1; `deep` is its hover and the text colour on `soft`. */
  accent: {
    main: BLUE.main,
    /** 2a hover of `main`; also blue text on `soft` (5.24:1). */
    deep: BLUE.hover,
    hover: BLUE.hover,
    /** Tint: highlighted rows, info chip and banner, AI tile. */
    soft: BLUE[50],
    /** The 3 px input focus ring and a light blue fill. */
    ring: BLUE[100],
    /** Info banner border. */
    border: BLUE[200],
    /** A light blue mark (chart series, muscle-map step 2). Never text. */
    light: BLUE[300],
    /** A bright blue mark on dark (rest timer glyph and bar). Never text on white. */
    bright: BLUE[400],
  },
  /** The dark surface: the Accept button, the user's chat bubble, the rest-timer bar, tooltips, the dark segment. */
  dark: { bg: INK, hover: '#27272A', border: ZINC[700], text: WHITE, muted: ZINC[400] },
  /** Status palettes — text on its own tint. Never a metric colour. */
  tone: {
    success: { text: '#15803D', bg: '#DCFCE7', soft: '#F0FDF4', border: '#BBF7D0', solid: '#16A34A', light: '#86EFAC' },
    warning: { text: '#B45309', bg: '#FEF3C7', deep: '#92400E', border: '#FDE68A' },
    danger: { text: '#B91C1C', bg: '#FEE2E2', soft: '#FEF2F2', border: '#FECACA' },
    info: { text: '#1E3A8A', bg: BLUE[50], border: BLUE[200], icon: BLUE.main },
    neutral: { text: ZINC[600], bg: ZINC[100] },
  },
  /** One colour per metric, used identically in rings, charts, the report and legends (kept from the measured palette:
   * each clears 3:1 on white). Tints come from `metricTint()` (16 %) and `metricSoft()` (12 %). */
  metric: METRIC,
  /** Legacy: the gradient a `MetricCard` with `surface="gradient"` is filled with. 2a has no gradient surfaces. */
  gradient: {
    weight: ['#0B4FC4', '#166FE5'],
    calories: ['#9A3412', '#C2410C'],
    protein: ['#5B21B6', '#7C3AED'],
    carbs: ['#713F12', '#A16207'],
    fat: ['#155E75', '#0E7490'],
    water: ['#0C4A6E', '#0369A1'],
    steps: ['#14532D', '#15803D'],
    sleep: ['#312E81', '#4338CA'],
    fatMass: ['#831843', '#9D174D'],
    lean: ['#064E3B', '#047857'],
    fasting: ['#1E293B', '#475569'],
  },
  /** Status text colours under their legacy names (good = success text, warning, flag = danger text). */
  status: { good: '#15803D', warning: '#B45309', flag: '#B91C1C' },
  /** The printed report (SPEC §11 print: black text on white): body text, secondary text, the running header. */
  print: { text: '#000000', secondary: '#333333', header: '#444444', page: WHITE },
  chart: {
    /** Horizontal gridlines. */
    grid: ZINC[100],
    /** The x-axis baseline. */
    baseline: ZINC[200],
    lineWidth: 2,
    /** The top of an area fill's fade (to 0 at the baseline). */
    areaOpacity: 0.16,
    /** The forecast band (≈ #EFF6FF over white). */
    bandOpacity: 0.08,
    barRadius: 3,
    /** Dashed target lines and the weigh-in dots' ring. */
    target: ZINC[400],
    targetDash: '4 4',
    forecastDash: '5 5',
    /** Axis labels: 2a draws them #A1A1AA, which is 2.56:1 — muted keeps them readable (4.83:1). */
    axis: ZINC[500],
    axisFontSize: 11,
    dotRing: ZINC[400],
    /** The goal line (the fat-mass colour). */
    goal: METRIC.fatMass,
    tooltip: { bg: INK, text: WHITE, muted: ZINC[400] },
  },
  /** Muscle map: zinc body, white strokes, four blue steps; the scan's fat segments use four rose steps. */
  muscleMap: {
    body: ZINC[200],
    bodyAlt: ZINC[100],
    stroke: WHITE,
    steps: [BLUE[100], BLUE[300], BLUE[400], BLUE.main] as const,
    fatSteps: ['#FECDD3', '#FDA4AF', '#FB7185', '#F43F5E'] as const,
  },
  /**
   * Radii, px. `chip` keeps its legacy meaning — fully round (pills, dots, tracks) — and `pill` says so; a 2a badge is
   * `badge`. Write radii as `${n}px` in an `sx`: MUI multiplies a bare number by `shape.borderRadius`.
   */
  radius: {
    card: 12,
    control: 8,
    inner: 6,
    chip: 999,
    pill: 999,
    badge: 6,
    /** A small (11 px) badge. */
    badgeSmall: 5,
    segment: 7,
    segmentTrack: 9,
    panel: 10,
    bar: 2,
    /** A keyboard key (the header's ⌘K). */
    kbd: 5,
    /** The focus ring's corners on a plain text link or a text-only button. */
    link: 4,
  },
  /** Legacy translucent materials. 2a's chrome is opaque white with a hairline; the fills are near-opaque to match. */
  material: {
    chrome: { fill: 'rgba(255,255,255,0.94)', blur: 'blur(12px) saturate(160%)' },
    sheet: { fill: 'rgba(255,255,255,0.96)', blur: 'blur(16px) saturate(160%)' },
    /** Behind a modal task. */
    scrim: 'rgba(9,9,11,0.4)',
    /** A row's press highlight. */
    press: 'rgba(9,9,11,0.04)',
    edge: 'rgba(255,255,255,0.6)',
  },
  /** Shadows (2a). A card is a 1 px whisper; only floating layers get a real one. */
  elevation: {
    card: '0 1px 2px rgba(0,0,0,0.04)',
    /** A clickable card under the pointer (its border does not change). */
    raised: '0 1px 3px rgba(0,0,0,0.08)',
    /** Menus, popovers, dialogs. */
    overlay: '0 10px 30px -6px rgba(9,9,11,0.16), 0 2px 6px rgba(9,9,11,0.06)',
    /** The floating rest timer and the quick-log button. */
    floating: '0 12px 32px rgba(9,9,11,0.28)',
    /** Legacy (the active rail tile): now the button shadow. */
    accent: '0 1px 2px rgba(0,0,0,0.08)',
    button: '0 1px 2px rgba(0,0,0,0.08)',
    /** The selected segment of a segmented control. */
    segment: '0 1px 2px rgba(0,0,0,0.08)',
    tooltip: '0 4px 12px rgba(0,0,0,0.15)',
    /** A switch's knob. */
    knob: '0 1px 2px rgba(0,0,0,0.2)',
    /** The highlighted card's ring (with a `accent.main` border). */
    highlight: `0 0 0 3px ${BLUE[50]}`,
  },
  /**
   * Motion. Only `opacity` and `transform` animate on entrance, so nothing shifts layout (no CLS). Under
   * `prefers-reduced-motion` the helpers below keep a 200 ms cross-fade and drop the movement.
   */
  motion: {
    duration: {
      instant: 100,
      fast: 200,
      base: 320,
      slow: 420,
      slower: 560,
      /** The entrance rise + fade. */
      enter: ENTER_DURATION,
      /** Bars growing and rings drawing. */
      grow: 1400,
      /** Chart lines drawing. */
      draw: 1600,
      /** Headline numbers counting up. */
      count: 1600,
    },
    easing: {
      /** 2a's entrance: expo-out. */
      enter: EXPO_OUT,
      /** Its mirror, so a reversible transition retraces its path. */
      exit: 'cubic-bezier(0.7, 0, 0.84, 0)',
      /** A value changing in place. */
      standard: 'cubic-bezier(0.4, 0, 0.2, 1)',
    },
    /** Entrance stagger, ms: rows in a list, cards in a row, sections down a page. */
    stagger: { row: 45, card: 60, section: 90 },
    /** The sheet spring's `linear()` curve, or `null` (see `SPRING`). */
    spring: SPRING,
    enterDuration: ENTER_DURATION,
    /** How far an entering card rises, px. */
    rise: 26,
  },
  /** 4 px base spacing scale. */
  space: (n: number) => n * 4,
  /** Gaps (2a): label → value 8–10, between cards 16, between sections 20–24, card padding 18–20. */
  rhythm: { tight: 8, group: 16, block: 20, section: 24, page: 36 },
  /** Card padding (2a): standard `18px 20px`, dense `16px 18px`; header row `16px 20px 12px`. */
  pad: { card: { y: 18, x: 20 }, dense: { y: 16, x: 18 }, header: { top: 16, x: 20, bottom: 12 } },
  tapTarget: 44,
  /** Keyboard focus: a 2 px accent ring 2 px out on buttons; inputs get a blue border + a 3 px `accent.ring`. */
  focusRing: { width: 2, offset: 2, color: BLUE.main, inputRing: 3 },
  layout: {
    phoneWidth: 390,
    /** 2a's content column: 1,440 design − 240 sidebar − 2 × 28 main padding. */
    maxContent: 1144,
    /** 2a's reading column (Settings' cards; a narrow page on a desktop). */
    readingMax: 820,
    bottomNavHeight: 64,
    /** Legacy desktop rail width (the 2a sidebar replaces the rail: `sidebarWidth`). */
    railWidth: 76,
    /** 2a sidebar and header. */
    sidebarWidth: 240,
    headerHeight: 56,
    /** 2a `main` padding: 24 top, 28 sides, 36 bottom. */
    mainPadding: { top: 24, x: 28, bottom: 36 },
    /** Scroll padding so a focused control never lands under the sticky top bar or the bottom nav + log button (WCAG 2.4.11). */
    scrollPadding: { top: 72, bottom: 152 },
  },
} as const

export type MetricKey = keyof typeof tokens.metric

/** The status tones a chip, badge or banner can take. */
export type Tone = 'success' | 'warning' | 'danger' | 'info' | 'neutral'

/** Media query for the reduced-motion preference (WCAG 2.3.3): no travel, short cross-fades instead. */
export const REDUCED_MOTION_QUERY = '(prefers-reduced-motion: reduce)'

/** Reduced transparency: a translucent surface turns opaque rather than blurring (`chromeSurface`/`sheetSurface`). */
export const REDUCED_TRANSPARENCY_QUERY = '(prefers-reduced-transparency: reduce)'

/** More contrast: a translucent surface turns opaque and gains a defined border. */
export const MORE_CONTRAST_QUERY = '(prefers-contrast: more)'

/** A touch screen: 44 px targets and 16 px input text apply here. */
export const COARSE_POINTER_QUERY = '@media (pointer: coarse)'

/** True when the viewer asked for reduced motion. Safe outside a browser (false). */
export function prefersReducedMotion(): boolean {
  return typeof window !== 'undefined' && typeof window.matchMedia === 'function' && window.matchMedia(REDUCED_MOTION_QUERY).matches
}

/** Scroll behaviour that honours the reduced-motion preference. */
export function scrollBehavior(): ScrollBehavior {
  return prefersReducedMotion() ? 'auto' : 'smooth'
}

/** Hex colour with alpha (0–1), e.g. the 12 % forecast band. */
export function withAlpha(hex: string, alpha: number): string {
  const a = Math.round(Math.min(1, Math.max(0, alpha)) * 255)
    .toString(16)
    .padStart(2, '0')
  return `${hex}${a}`
}

/** A metric's track tint (16 %): mini-bar days off target, a meal stack's lighter segment, a ring's track. */
export function metricTint(metric: MetricKey): string {
  return withAlpha(tokens.metric[metric], 0.16)
}

/** A metric's soft tint (12 %): an icon tile or a chip behind the metric colour. */
export function metricSoft(metric: MetricKey): string {
  return withAlpha(tokens.metric[metric], 0.12)
}

/** The CSS gradient for a legacy gradient metric card, left to right. */
export function metricGradient(metric: MetricKey): string {
  const [from, to] = tokens.gradient[metric]
  return `linear-gradient(135deg, ${from} 0%, ${to} 100%)`
}

/** True when the browser can animate with a `linear()` easing curve (the sheet spring). */
export function supportsSpring(): boolean {
  return SPRING !== null
}

/** The easing an entrance settles with: 2a's expo-out. Pair it with `enterDuration()`. */
export function enterEasing(): string {
  return EXPO_OUT
}

/** How long an entrance takes, ms (700). */
export function enterDuration(): number {
  return ENTER_DURATION
}

/**
 * The entrance to play when the viewer prefers reduced motion: a 200 ms cross-fade and no travel. Returns
 * `animation`'s shorthand value, `'none'` when motion is not reduced. Takes `reduced` rather than reading the media
 * query itself so a caller's `useMediaQuery` drives a re-render when the preference changes.
 */
export function reducedEntrance(delay: number, reduced: boolean): string {
  if (!reduced) return 'none'
  return `${tokens.motion.duration.fast}ms ${tokens.motion.easing.standard} ${delay}ms both crossFadeIn`
}

/** Properties that still aid comprehension under reduced motion (colour, opacity, elevation) keep a short transition. */
const REDUCED_MOTION_SURVIVORS = /^(opacity|color|background-color|border-color|outline-color|box-shadow|fill|stroke)$/

/**
 * A transition string for the given properties. Every hand-written transition goes through this, so the reduced-motion
 * preference cannot be forgotten in one place (WCAG 2.3.3): under it the colour/opacity/shadow changes stay (at the
 * instant step) and travel and scale are dropped.
 */
export function transitionOf(
  properties: string | readonly string[],
  duration: number = tokens.motion.duration.base,
  easing: string = tokens.motion.easing.standard,
): string {
  const list = typeof properties === 'string' ? [properties] : properties
  if (prefersReducedMotion()) {
    const kept = list
      .map((p) => p.trim())
      .filter((p) => REDUCED_MOTION_SURVIVORS.test(p))
      .map((p) => `${p} ${tokens.motion.duration.instant}ms ${tokens.motion.easing.standard}`)
    return kept.join(', ') || 'none'
  }
  return list.map((p) => `${p} ${duration}ms ${easing}`).join(', ')
}

/** The nav layer's surface (2a: white, near-opaque), spread into the `sx` of the fixed/sticky element that owns it. */
export const chromeSurface = {
  backgroundColor: tokens.material.chrome.fill,
  backdropFilter: tokens.material.chrome.blur,
  WebkitBackdropFilter: tokens.material.chrome.blur,
  '@media (prefers-reduced-transparency: reduce)': { backgroundColor: tokens.ink.card, backdropFilter: 'none', WebkitBackdropFilter: 'none' },
  '@media (prefers-contrast: more)': { backgroundColor: tokens.ink.card, borderColor: tokens.ink.text },
} as const

/** A sheet, the Ask AI panel, the command palette. Same fallbacks as the chrome. */
export const sheetSurface = {
  backgroundColor: tokens.material.sheet.fill,
  backdropFilter: tokens.material.sheet.blur,
  WebkitBackdropFilter: tokens.material.sheet.blur,
  '@media (prefers-reduced-transparency: reduce)': { backgroundColor: tokens.ink.card, backdropFilter: 'none', WebkitBackdropFilter: 'none' },
  '@media (prefers-contrast: more)': { backgroundColor: tokens.ink.card, borderColor: tokens.ink.text },
} as const

declare module '@mui/material/styles' {
  interface Palette {
    metric: typeof tokens.metric
    ink: typeof tokens.ink
    accent: typeof tokens.accent
    /** The dark button colour (`<Button variant="contained" color="dark">` — Accept). */
    dark: Palette['primary']
  }
  interface PaletteOptions {
    metric?: typeof tokens.metric
    ink?: typeof tokens.ink
    accent?: typeof tokens.accent
    dark?: PaletteOptions['primary']
  }
  interface TypographyVariants {
    sectionTitle: React.CSSProperties
  }
  interface TypographyVariantsOptions {
    sectionTitle?: React.CSSProperties
  }
}

declare module '@mui/material/Typography' {
  interface TypographyPropsVariantOverrides {
    sectionTitle: true
  }
}

declare module '@mui/material/Button' {
  interface ButtonPropsColorOverrides {
    dark: true
  }
  interface ButtonPropsSizeOverrides {
    /** 34 px, 13/500 — a card's own actions (a proposal's Accept / Reject). */
    dense: true
    /** 30 px, 12/500 — a row's action. */
    tiny: true
  }
}

declare module '@mui/material/IconButton' {
  interface IconButtonPropsSizeOverrides {
    /** 26 × 26 — a table row's action. */
    tiny: true
  }
}

const { ink, font, radius, accent, elevation, motion, material, tone } = tokens

/** On a touch screen, a target never drops under 44 px whatever its desktop size. */
const touchTarget = (extra: object = {}) => ({ [COARSE_POINTER_QUERY]: { minHeight: tokens.tapTarget, ...extra } })

/** A press state: instant, on pointer-down, never a ripple — and no scale under reduced motion. */
const press = (scale: number) => ({
  '&:active': { transform: `scale(${scale})` },
  '@media (prefers-reduced-motion: reduce)': { '&:active': { transform: 'none' } },
})

/** A badge's colours per tone: tint, text, weight. MUI's filled `<Chip>` and the kit's `StatusChip` both read it. */
export const CHIP_TONES = {
  neutral: { bg: tone.neutral.bg, text: tone.neutral.text, weight: font.weight.label },
  info: { bg: accent.soft, text: accent.deep, weight: font.weight.label },
  success: { bg: tone.success.bg, text: tone.success.text, weight: font.weight.heading },
  warning: { bg: tone.warning.bg, text: tone.warning.text, weight: font.weight.heading },
  danger: { bg: tone.danger.bg, text: tone.danger.text, weight: font.weight.heading },
} as const satisfies Record<Tone, { bg: string; text: string; weight: number }>

/** The tone each MUI colour name takes on a filled `<Chip>`. */
const CHIP_COLOUR_TONES = {
  default: 'neutral',
  primary: 'info',
  info: 'info',
  secondary: 'info',
  success: 'success',
  warning: 'warning',
  error: 'danger',
} as const satisfies Record<string, Tone>

/** A banner's look per tone: tint, border, text, icon. MUI's `<Alert>` and the kit's `Banner` both read it. */
export const BANNER_TONES = {
  info: { bg: tone.info.bg, border: tone.info.border, text: tone.info.text, icon: tone.info.icon },
  warning: { bg: tone.warning.bg, border: tone.warning.border, text: tone.warning.deep, icon: tone.warning.text },
  danger: { bg: tone.danger.soft, border: tone.danger.border, text: tone.danger.text, icon: tone.danger.text },
  success: { bg: tone.success.soft, border: tone.success.border, text: tone.success.text, icon: tone.success.solid },
} as const

const inputRing = `0 0 0 ${tokens.focusRing.inputRing}px ${accent.ring}`

export const theme = createTheme({
  cssVariables: true,
  // MUI 9's own keyboard ring, applied to every ButtonBase (and inset on clip-prone rows): 2 px accent, 2 px out.
  focusVisible: { outlineColor: tokens.focusRing.color, outlineWidth: tokens.focusRing.width, outlineOffset: tokens.focusRing.offset },
  palette: {
    mode: 'light',
    primary: { main: accent.main, dark: accent.deep, light: accent.bright, contrastText: WHITE },
    secondary: { main: tokens.metric.water },
    dark: { main: tokens.dark.bg, dark: tokens.dark.hover, light: tokens.dark.border, contrastText: tokens.dark.text },
    success: { main: tone.success.text, contrastText: WHITE },
    warning: { main: tone.warning.text, contrastText: WHITE },
    error: { main: tone.danger.text, contrastText: WHITE },
    info: { main: accent.main, contrastText: WHITE },
    text: { primary: ink.text, secondary: ink.secondary, disabled: ink.faint },
    divider: ink.border,
    background: { default: ink.page, paper: ink.card },
    action: {
      hover: ink.fill,
      selected: ink.fill,
      disabled: ink.faint,
      disabledBackground: ink.fill,
    },
    metric: tokens.metric,
    ink,
    accent,
  },
  shape: { borderRadius: radius.control },
  spacing: 4,
  typography: {
    fontFamily: font.family,
    fontSize: font.size.body,
    htmlFontSize: 16,
    fontWeightRegular: font.weight.body,
    fontWeightMedium: font.weight.label,
    fontWeightBold: font.weight.heading,
    h1: { fontSize: font.size.largeTitle, fontWeight: font.weight.heading, lineHeight: font.leading.largeTitle, letterSpacing: font.em.title },
    h2: { fontSize: font.size.title1, fontWeight: font.weight.heading, lineHeight: font.leading.title1, letterSpacing: font.tracking.title1 },
    h3: { fontSize: font.size.sectionTitle, fontWeight: font.weight.heading, lineHeight: font.leading.sectionTitle },
    h4: { fontSize: font.size.cardTitle, fontWeight: font.weight.heading, lineHeight: font.leading.cardTitle },
    h5: { fontSize: font.size.body, fontWeight: font.weight.heading, lineHeight: font.leading.body },
    h6: { fontSize: font.size.body, fontWeight: font.weight.heading, lineHeight: font.leading.body },
    subtitle1: { fontSize: font.size.body, fontWeight: font.weight.label, lineHeight: font.leading.body },
    subtitle2: { fontSize: font.size.small, fontWeight: font.weight.label, lineHeight: font.leading.small },
    body1: { fontSize: font.size.body, fontWeight: font.weight.body, lineHeight: font.leading.body },
    body2: { fontSize: font.size.small, fontWeight: font.weight.body, lineHeight: font.leading.small, color: ink.secondary },
    button: { fontSize: font.size.body, fontWeight: font.weight.label, textTransform: 'none', letterSpacing: 0, lineHeight: 1.4 },
    caption: { fontSize: font.size.caption, fontWeight: font.weight.body, lineHeight: font.leading.caption },
    overline: {
      fontSize: font.size.micro,
      fontWeight: font.weight.label,
      lineHeight: font.leading.micro,
      letterSpacing: font.em.micro,
      textTransform: 'uppercase',
    },
    sectionTitle: { fontSize: font.size.sectionTitle, fontWeight: font.weight.heading, lineHeight: font.leading.sectionTitle },
  },
  components: {
    MuiCssBaseline: {
      styleOverrides: {
        '*, *::before, *::after': { WebkitTapHighlightColor: 'transparent' },
        body: {
          backgroundColor: ink.page,
          color: ink.text,
          WebkitFontSmoothing: 'antialiased',
          MozOsxFontSmoothing: 'grayscale',
          textSizeAdjust: '100%',
        },
        '::selection': { backgroundColor: accent.ring },
        // A long press must not open a callout over a control (iOS Safari), the way it does over text.
        'button, a': { WebkitTouchCallout: 'none', textDecoration: 'none' },
        // The reduced-motion entrance (see `reducedEntrance`): a keyframe animation, so the cross-fade plays from the
        // element's first paint on the browser's own clock rather than waiting on a JavaScript frame.
        '@keyframes crossFadeIn': { from: { opacity: 0 }, to: { opacity: 1 } },
        // MUI's baseline squashes every animation to 0.01 ms under reduced motion; this gives the cross-fade above its
        // 200 ms back. The `html` prefix outranks MUI's `*` rule, which is emitted after this block.
        '@media (prefers-reduced-motion: reduce)': {
          'html *, html *::before, html *::after': { animationDuration: `${tokens.motion.duration.fast}ms !important` },
        },
      },
    },
    MuiButtonBase: {
      defaultProps: { disableRipple: true },
      // `fontFamily: 'inherit'`: a bare ButtonBase (the header's search field, an accordion summary) otherwise keeps the
      // browser's button font; Button, Tab, MenuItem and ToggleButton set their own type after this.
      styleOverrides: { root: { WebkitTapHighlightColor: 'transparent', fontFamily: 'inherit' } },
    },
    MuiPaper: {
      defaultProps: { elevation: 0 },
      styleOverrides: { outlined: { borderColor: ink.border, borderRadius: radius.card } },
    },
    // 2a card: white, 1 px #E4E4E7, radius 12, the card whisper. A card inside a card drops its shadow.
    MuiCard: {
      defaultProps: { elevation: 0 },
      styleOverrides: {
        root: {
          borderRadius: radius.card,
          border: `1px solid ${ink.border}`,
          backgroundColor: ink.card,
          boxShadow: elevation.card,
          '& &': { boxShadow: 'none' },
        },
      },
    },
    // Buttons (2a): primary blue, dark (Accept), outline, ghost (text), destructive (color="error"). Sizes 40 / 36 /
    // 34 (dense) / 32 (small) / 30 (tiny); 44 on a touch screen. 100 ms press to 0.98, no ripple.
    MuiButton: {
      defaultProps: { disableElevation: true },
      styleOverrides: {
        root: {
          minHeight: 36,
          minWidth: 0,
          padding: '4px 12px',
          gap: 0,
          borderRadius: radius.control,
          fontSize: font.size.body,
          fontWeight: font.weight.label,
          lineHeight: 1.4,
          whiteSpace: 'nowrap',
          transition: `background-color ${motion.duration.fast}ms ${motion.easing.standard}, border-color ${motion.duration.fast}ms ${motion.easing.standard}, color ${motion.duration.fast}ms ${motion.easing.standard}, transform ${motion.duration.instant}ms ${motion.easing.standard}`,
          ...press(0.98),
          ...touchTarget(),
        },
        startIcon: { marginLeft: -2, marginRight: 6, '& > *:nth-of-type(1)': { fontSize: 18 } },
        endIcon: { marginLeft: 4, marginRight: -2, '& > *:nth-of-type(1)': { fontSize: 18 } },
        contained: { boxShadow: elevation.button, '&:hover': { boxShadow: elevation.button } },
        outlined: {
          padding: '4px 12px',
          border: `1px solid ${ink.border}`,
          backgroundColor: ink.card,
          color: ink.text,
          '&:hover': { backgroundColor: ink.fill, borderColor: ink.border },
          '&.Mui-disabled': { borderColor: ink.border, backgroundColor: ink.card },
        },
        text: { padding: '4px 10px', '&:hover': { backgroundColor: ink.fill } },
        sizeSmall: {
          minHeight: 32,
          padding: '2px 10px',
          fontSize: font.size.small,
          '& .MuiButton-startIcon > *:nth-of-type(1), & .MuiButton-endIcon > *:nth-of-type(1)': { fontSize: 16 },
        },
        sizeLarge: { minHeight: 40, padding: '6px 16px', fontSize: font.size.body },
      },
      variants: [
        { props: { size: 'dense' }, style: { minHeight: 34, padding: '2px 14px', fontSize: font.size.small } },
        {
          props: { size: 'tiny' },
          style: {
            minHeight: 30,
            padding: '2px 10px',
            fontSize: font.size.caption,
            '& .MuiButton-startIcon > *:nth-of-type(1), & .MuiButton-endIcon > *:nth-of-type(1)': { fontSize: 16 },
          },
        },
        // The outline button stays neutral whatever its colour, except destructive, whose text turns red.
        { props: { variant: 'outlined', color: 'error' }, style: { color: tone.danger.text, '&:hover': { backgroundColor: tone.danger.soft } } },
        { props: { variant: 'text', color: 'error' }, style: { color: tone.danger.text, '&:hover': { backgroundColor: tone.danger.soft } } },
        { props: { variant: 'text', color: 'inherit' }, style: { '&:hover': { backgroundColor: ink.fill } } },
      ],
    },
    // Icon buttons: a square at the control radius, ghost by default — 36 / 30 (small) / 26 (tiny) / 40 (large).
    MuiIconButton: {
      styleOverrides: {
        root: {
          width: 36,
          height: 36,
          padding: 0,
          borderRadius: radius.control,
          color: ink.label,
          transition: `background-color ${motion.duration.fast}ms ${motion.easing.standard}, color ${motion.duration.fast}ms ${motion.easing.standard}, transform ${motion.duration.instant}ms ${motion.easing.standard}`,
          '&:hover': { backgroundColor: ink.fill, color: ink.text },
          ...press(0.96),
          [COARSE_POINTER_QUERY]: { minWidth: tokens.tapTarget, minHeight: tokens.tapTarget },
        },
        sizeSmall: { width: 30, height: 30 },
        sizeLarge: { width: 40, height: 40 },
        colorPrimary: { color: accent.main, '&:hover': { color: accent.deep } },
      },
      variants: [{ props: { size: 'tiny' }, style: { width: 26, height: 26, borderRadius: radius.inner } }],
    },
    // Chips are 2a badges: radius 6, 12/500 (11 small); coloured ones take their status tint and 600.
    MuiChip: {
      styleOverrides: {
        root: {
          height: 'auto',
          minHeight: 22,
          padding: '3px 8px',
          borderRadius: radius.badge,
          fontSize: font.size.caption,
          fontWeight: font.weight.label,
          lineHeight: '16px',
          letterSpacing: 0,
          transition: `background-color ${motion.duration.fast}ms ${motion.easing.standard}`,
        },
        label: { padding: 0, overflow: 'visible' },
        sizeSmall: {
          minHeight: 18,
          padding: '1px 6px',
          borderRadius: radius.badgeSmall,
          fontSize: font.size.micro,
          '& .MuiChip-icon': { fontSize: 12, marginLeft: -1, marginRight: 3 },
        },
        icon: { fontSize: 14, marginLeft: -2, marginRight: 4, color: 'inherit' },
        deleteIcon: { fontSize: 16, marginLeft: 4, marginRight: -4, color: 'inherit', opacity: 0.7, '&:hover': { color: 'inherit', opacity: 1 } },
        outlined: { border: `1px solid ${ink.border}`, backgroundColor: ink.card, color: ink.label },
        clickable: { ...touchTarget(), '&:active': { boxShadow: 'none' } },
      },
      variants: [
        ...(Object.entries(CHIP_COLOUR_TONES) as [keyof typeof CHIP_COLOUR_TONES, Tone][]).map(([color, chipTone]) => {
          const t = CHIP_TONES[chipTone]
          return {
            props: { variant: 'filled' as const, color },
            style: {
              backgroundColor: t.bg,
              color: t.text,
              fontWeight: t.weight,
              '&.MuiChip-clickable:hover, &.MuiChip-clickable.Mui-focusVisible': { backgroundColor: t.bg, filter: 'brightness(0.96)' },
            },
          }
        }),
        {
          props: { variant: 'outlined' as const },
          style: { '&.MuiChip-clickable:hover': { backgroundColor: ink.fill } },
        },
      ],
    },
    // Full-width menu rows: 32 px, radius 6 inside a 4 px list padding; 44 px on touch.
    MuiMenuItem: {
      styleOverrides: {
        root: {
          minHeight: 32,
          margin: '0 4px',
          padding: '6px 8px',
          borderRadius: radius.inner,
          fontSize: font.size.body,
          '&:hover': { backgroundColor: ink.fill },
          '&.Mui-selected, &.Mui-selected:hover': { backgroundColor: ink.fill },
          ...touchTarget(),
        },
      },
    },
    MuiListItemIcon: { styleOverrides: { root: { minWidth: 28, color: ink.secondary } } },
    MuiListItemButton: {
      styleOverrides: {
        root: {
          '&:hover': { backgroundColor: ink.panel },
          '&.Mui-selected, &.Mui-selected:hover': { backgroundColor: ink.fill },
          '&:active': { backgroundColor: material.press },
        },
      },
    },
    MuiListItemText: { styleOverrides: { primary: { fontSize: font.size.body }, secondary: { fontSize: font.size.caption, color: ink.secondary } } },
    MuiDivider: { styleOverrides: { root: { borderColor: ink.border } } },
    MuiLink: {
      defaultProps: { underline: 'hover' },
      styleOverrides: { root: { color: accent.main, fontWeight: font.weight.label, '&:hover': { color: accent.deep } } },
    },
    // Alerts are 2a banners: tint + 1 px border + text, radius 10, 13 px; the icon carries the colour.
    MuiAlert: {
      styleOverrides: {
        root: ({ ownerState }) => {
          const b = BANNER_TONES[ownerState.severity === 'error' ? 'danger' : (ownerState.severity ?? 'info')]
          if (ownerState.variant === 'filled') return { borderRadius: radius.panel }
          return {
            alignItems: 'flex-start',
            padding: '11px 14px',
            borderRadius: radius.panel,
            border: `1px solid ${b.border}`,
            backgroundColor: b.bg,
            color: b.text,
            fontSize: font.size.small,
            lineHeight: font.leading.small,
            '& .MuiAlert-icon': { color: b.icon, opacity: 1, padding: '1px 0', marginRight: 10, fontSize: 18 },
            '& .MuiAlert-message': { padding: '1px 0', minWidth: 0 },
            '& .MuiAlert-action': { padding: 0, marginRight: -6, alignSelf: 'center' },
            '& .MuiAlertTitle-root': { fontSize: font.size.small, fontWeight: font.weight.heading, margin: 0 },
          }
        },
      },
    },
    MuiInputBase: {
      styleOverrides: {
        root: { fontSize: font.size.body, [COARSE_POINTER_QUERY]: { fontSize: 16 } },
        input: { '&::placeholder': { color: ink.muted, opacity: 1 } },
      },
    },
    // Inputs (2a): radius 8, white, 1 px #E4E4E7; focus = blue border + 3 px #DBEAFE ring.
    MuiOutlinedInput: {
      styleOverrides: {
        root: {
          borderRadius: radius.control,
          backgroundColor: ink.card,
          transition: `box-shadow ${motion.duration.fast}ms ${motion.easing.standard}`,
          '& .MuiOutlinedInput-notchedOutline': { borderColor: ink.border, transition: `border-color ${motion.duration.fast}ms ${motion.easing.standard}` },
          '&:hover .MuiOutlinedInput-notchedOutline': { borderColor: ink.faint },
          '&.Mui-focused': { boxShadow: inputRing },
          '&.Mui-focused .MuiOutlinedInput-notchedOutline': { borderColor: accent.main, borderWidth: 1 },
          '&.Mui-error .MuiOutlinedInput-notchedOutline': { borderColor: tone.danger.text },
          '&.Mui-error.Mui-focused': { boxShadow: `0 0 0 ${tokens.focusRing.inputRing}px ${tone.danger.bg}` },
          '&.Mui-disabled': { backgroundColor: ink.panel },
          '&.Mui-disabled .MuiOutlinedInput-notchedOutline': { borderColor: ink.border },
        },
      },
    },
    MuiInputLabel: {
      styleOverrides: {
        root: { color: ink.secondary, '&.Mui-focused': { color: accent.main }, '&.Mui-error': { color: tone.danger.text } },
      },
    },
    MuiFormHelperText: { styleOverrides: { root: { fontSize: font.size.caption, marginLeft: 2, marginRight: 2 } } },
    MuiTextField: { defaultProps: { fullWidth: true, size: 'medium' } },
    // A segmented control (2a): a #F4F4F5 track, 3 px in, radius 9; segments 13/500 radius 7, the selected one white
    // with the segment shadow. The kit's `Segmented` adds the outline and dark variants.
    MuiToggleButtonGroup: {
      styleOverrides: {
        root: {
          gap: 2,
          padding: 3,
          borderRadius: radius.segmentTrack,
          backgroundColor: ink.fill,
          '& .MuiToggleButtonGroup-grouped, & .MuiToggleButtonGroup-firstButton, & .MuiToggleButtonGroup-middleButton, & .MuiToggleButtonGroup-lastButton':
            { margin: 0, border: 0, borderRadius: radius.segment },
        },
      },
    },
    MuiToggleButton: {
      styleOverrides: {
        root: {
          border: 0,
          padding: '6px 12px',
          borderRadius: radius.segment,
          fontSize: font.size.small,
          fontWeight: font.weight.label,
          lineHeight: 1.4,
          textTransform: 'none',
          color: ink.label,
          backgroundColor: 'transparent',
          transition: `background-color ${motion.duration.fast}ms ${motion.easing.standard}, color ${motion.duration.fast}ms ${motion.easing.standard}, box-shadow ${motion.duration.fast}ms ${motion.easing.standard}`,
          '&:hover': { backgroundColor: 'transparent', color: ink.text },
          '&.Mui-selected, &.Mui-selected:hover': { backgroundColor: ink.card, color: ink.text, boxShadow: elevation.segment },
          '&.Mui-disabled': { border: 0, color: ink.disabled },
          ...touchTarget(),
        },
        sizeSmall: { padding: '4px 10px', fontSize: font.size.caption },
        sizeLarge: { padding: '8px 16px', fontSize: font.size.body },
      },
    },
    // Switch (2a): a 40 × 22 pill, off #E4E4E7, on #166FE5, an 18 px white knob. On touch the hidden input grows to 44 px.
    MuiSwitch: {
      defaultProps: { disableRipple: true },
      styleOverrides: {
        root: {
          width: 40,
          height: 22,
          padding: 0,
          overflow: 'visible',
          flex: 'none',
          [COARSE_POINTER_QUERY]: { '& .MuiSwitch-input': { top: -11, height: 44 } },
        },
        switchBase: {
          padding: 2,
          '&.Mui-checked': { transform: 'translateX(18px)', color: WHITE },
          '&.Mui-checked + .MuiSwitch-track': { backgroundColor: accent.main, opacity: 1 },
          '&.Mui-disabled + .MuiSwitch-track': { opacity: 0.5 },
          '&:hover': { backgroundColor: 'transparent' },
        },
        thumb: { width: 18, height: 18, color: WHITE, boxShadow: elevation.knob },
        track: { borderRadius: 11, backgroundColor: ink.border, opacity: 1 },
      },
    },
    MuiCheckbox: { styleOverrides: { root: { color: ink.control, '&.Mui-checked': { color: accent.main } } } },
    MuiRadio: { styleOverrides: { root: { color: ink.control, '&.Mui-checked': { color: accent.main } } } },
    // Tables (2a): 13 px; the head 12/500 muted between two #E4E4E7 rules; #F4F4F5 row hairlines; the outer cells
    // padded to the card's 20 px gutter; numbers right-aligned in tabular figures.
    MuiTable: { styleOverrides: { root: { borderCollapse: 'collapse' } } },
    MuiTableCell: {
      styleOverrides: {
        root: {
          fontSize: font.size.small,
          lineHeight: font.leading.small,
          padding: '9px 12px',
          borderBottom: `1px solid ${ink.hairline}`,
          '&:first-of-type': { paddingLeft: tokens.pad.card.x },
          '&:last-of-type': { paddingRight: tokens.pad.card.x },
        },
        head: {
          fontSize: font.size.caption,
          fontWeight: font.weight.label,
          color: ink.secondary,
          padding: '8px 12px',
          borderTop: `1px solid ${ink.border}`,
          borderBottom: `1px solid ${ink.border}`,
        },
        alignRight: { fontVariantNumeric: 'tabular-nums' },
      },
    },
    // 2a: a table sits flush in its card, so its last row draws no hairline.
    MuiTableBody: { styleOverrides: { root: { '& tr:last-of-type td': { borderBottom: 0 } } } },
    MuiTableRow: { styleOverrides: { root: { '&.MuiTableRow-hover:hover': { backgroundColor: ink.panel } } } },
    // A dialog (2a): radius 12, hairline border, the overlay shadow; title 16/600; actions right with an 8 px gap.
    MuiDialog: {
      styleOverrides: {
        paper: { borderRadius: radius.card, border: `1px solid ${ink.border}`, boxShadow: elevation.overlay, backgroundImage: 'none' },
      },
    },
    MuiDialogTitle: {
      styleOverrides: {
        root: { fontSize: font.size.cardTitle, fontWeight: font.weight.heading, lineHeight: font.leading.cardTitle, padding: '20px 24px 8px' },
      },
    },
    MuiDialogContent: { styleOverrides: { root: { padding: '8px 24px', fontSize: font.size.body } } },
    MuiDialogContentText: { styleOverrides: { root: { fontSize: font.size.body, color: ink.secondary } } },
    MuiDialogActions: { styleOverrides: { root: { padding: '12px 24px 20px', gap: 8, '& > :not(style) ~ :not(style)': { marginLeft: 0 } } } },
    MuiBackdrop: { styleOverrides: { root: { '&:not(.MuiBackdrop-invisible)': { backgroundColor: material.scrim } } } },
    MuiDrawer: {
      styleOverrides: {
        paper: ({ ownerState }) => ({
          borderColor: ink.border,
          ...(ownerState.anchor === 'bottom' && { borderRadius: `${radius.card}px ${radius.card}px 0 0`, boxShadow: elevation.overlay }),
        }),
      },
    },
    MuiPopover: { styleOverrides: { paper: { borderRadius: radius.control, border: `1px solid ${ink.border}`, boxShadow: elevation.overlay } } },
    MuiMenu: {
      styleOverrides: {
        paper: { marginTop: 4, borderRadius: radius.control, border: `1px solid ${ink.border}`, boxShadow: elevation.overlay },
        list: { padding: '4px 0' },
      },
    },
    // Tooltip (2a): #09090B, white 12 px, radius 8, 6 × 10 padding, the tooltip shadow.
    MuiTooltip: {
      styleOverrides: {
        tooltip: {
          borderRadius: radius.control,
          backgroundColor: tokens.dark.bg,
          color: tokens.dark.text,
          fontSize: font.size.caption,
          fontWeight: font.weight.body,
          lineHeight: font.leading.caption,
          padding: '6px 10px',
          boxShadow: elevation.tooltip,
        },
        arrow: { color: tokens.dark.bg },
      },
    },
    // Loading shapes sit on the fill colour; a rounded skeleton takes the card radius.
    MuiSkeleton: {
      styleOverrides: {
        root: { backgroundColor: ink.fill },
        rounded: { borderRadius: radius.card },
        text: { borderRadius: 4 },
      },
    },
    MuiBottomNavigation: { styleOverrides: { root: { height: tokens.layout.bottomNavHeight, backgroundColor: 'transparent' } } },
    MuiBottomNavigationAction: {
      styleOverrides: {
        root: {
          minWidth: 0,
          paddingTop: 6,
          color: ink.secondary,
          '&.Mui-selected': { color: accent.main },
          '& .MuiSvgIcon-root': { transition: `transform ${motion.duration.fast}ms ${motion.easing.standard}` },
          '&:active .MuiSvgIcon-root': { transform: 'scale(0.88)' },
          '@media (prefers-reduced-motion: reduce)': { '&:active .MuiSvgIcon-root': { transform: 'none' } },
        },
        label: { fontSize: font.size.caption, '&.Mui-selected': { fontSize: font.size.caption } },
      },
    },
    // Progress tracks (2a): 6 px, fully round, #F4F4F5 under the colour.
    MuiLinearProgress: {
      styleOverrides: { root: { height: 6, borderRadius: radius.pill, backgroundColor: ink.fill }, bar: { borderRadius: radius.pill } },
    },
    // A bottom snackbar sits above the bottom nav and the home indicator at every width.
    MuiSnackbar: {
      styleOverrides: {
        root: ({ ownerState, theme }) => {
          if (ownerState.anchorOrigin?.vertical === 'top') return {}
          const bottom = `calc(${tokens.layout.bottomNavHeight + tokens.space(2)}px + env(safe-area-inset-bottom, 0px))`
          return { bottom, [theme.breakpoints.up('sm')]: { bottom } }
        },
      },
    },
    MuiSnackbarContent: {
      styleOverrides: {
        root: { borderRadius: radius.control, backgroundColor: tokens.dark.bg, color: tokens.dark.text, fontSize: font.size.body, boxShadow: elevation.tooltip },
      },
    },
  },
})
