// Owns: every visual token (SPEC §11) — ink, metric palette, semantic status colours, the type scale, spacing,
// radius hierarchy, materials, elevation, motion, chart style, muscle-map steps — and the MUI theme built from them.
// Nothing else in the app hard-codes a colour. Charts read `tokens` directly so SVG output carries literal hex
// colours for print and the PDF archive.
//
// Visual language (2026-10-06, "Apple HIG rebuild" — see docs/APPLE-DESIGN.md for the audit and the full decision
// log): the canvas is the platform's grouped grey, cards are white 16 px surfaces separated by surface contrast
// rather than by an outline, and the chrome (top bar, tabs, rail) is a translucent material content scrolls under.
// Type is the platform's own face — which ships optical sizing, tracking tables and legibility tuning — on a nine-step
// scale where tracking is size-specific and leading tracks size inversely. Motion is expressed Apple's way, as a
// *response* with a critically damped spring (`linear()` where the browser has it, the equivalent cubic-bézier
// otherwise — both generated by the solver in `motion/spring.ts`, so a curve and the duration it is given can never
// drift apart), and exit is the exact mirror of enter so a dismissal retraces its arrival. Bounce is spent only where
// a gesture carried momentum into the release, which is the one place an overshoot is earned; reduced motion keeps
// its cross-fades rather than losing them (see `transitionOf`).
//
// Colour (2026-10-06): the action colour is Facebook blue (#166FE5 — Meta's own blue, one step down from the
// #1877F2 brand fill so white text on a button measures 4.73:1 and clears AA; the brand fill itself is only 4.23:1).
// Values are unchanged by the rebuild — the change is restraint in *use*: chrome is neutral, and colour is spent on
// data and on the primary action. Every pair below was measured, not eyeballed: white on a metric gradient passes
// WCAG AA 4.5:1 at BOTH stops, and every metric colour clears 3:1 against both the card and the page.
import { createTheme } from '@mui/material/styles'
import { settleTime, springCurve, SPRING_DEFAULT } from './motion/spring'

/** The two surfaces the material tokens are mixed from — named here so nothing below hard-codes a white or an ink. */
const CARD_WHITE = '#FFFFFF'
const INK_BLACK = '#111827'

/**
 * The entrance spring — critically damped, response 0.35 s — as a CSS `linear()` curve, generated from the solver so
 * it cannot be a hand-typed approximation of a spring. It replaces a 21-stop sample that had been pasted in and then
 * given a 320 ms transition to run in: that curve needs about half a second, so every entrance in the app was being
 * cut off mid-settle and landing with a jolt. `enterDuration()` derives the length from the same spring, so the curve
 * and the time it is allowed can never disagree again. `null` where the browser cannot parse a `linear()` easing.
 */
const SPRING = springCurve(SPRING_DEFAULT)

/** The entrance's own settle time, in ms, rounded to the millisecond CSS takes. */
const ENTER_DURATION = Math.round(settleTime(SPRING_DEFAULT) * 1000)

export const tokens = {
  font: {
    /** The platform's own face. SF Pro on Apple hardware, Segoe UI on Windows, Roboto on Android — each already
     * carries its own optical sizing, tracking and legibility tuning, which is exactly what the HIG asks for and
     * what the self-hosted face it replaced could not do. */
    family:
      '-apple-system, BlinkMacSystemFont, "SF Pro Text", "Segoe UI Variable Text", "Segoe UI", system-ui, Roboto, "Helvetica Neue", Arial, sans-serif',
    /** Weights: 400 body, 500 labels and buttons, 600 headings and numbers — emphasis by weight, not by size. */
    weight: { body: 400, label: 500, heading: 600, number: 600 },
    /** The nine-step scale, in px at a 16 px root. Every step's own tracking and leading live in `tracking`/`leading`
     * beside it: a single letter-spacing value is wrong at some size, and leading tracks size inversely. */
    size: {
      largeTitle: 34,
      title1: 28,
      sectionTitle: 22,
      cardTitle: 18,
      body: 17,
      emphasis: 16,
      small: 15,
      label: 13,
      caption: 12,
      /** Number sizes: a stat card's value, the same on a phone, and the number on a metric card. */
      bigNumber: 34,
      bigNumberSmall: 30,
      bigNumberLarge: 40,
      statNumber: 40,
    },
    /** Size-specific tracking, in px. Large text tightens (letters read too far apart as they grow); small text
     * loosens slightly; body sits near zero. */
    tracking: {
      largeTitle: -0.6,
      title1: -0.5,
      sectionTitle: -0.35,
      cardTitle: -0.26,
      body: -0.24,
      emphasis: -0.2,
      small: -0.15,
      label: -0.08,
      caption: 0,
      /** A column of values is easier to scan when it is tight and tabular. */
      number: -0.8,
    },
    /** Leading, inversely tracking the size: tight on a heading, looser on body copy. */
    leading: {
      largeTitle: 1.2,
      title1: 1.21,
      sectionTitle: 1.27,
      cardTitle: 1.28,
      body: 1.29,
      emphasis: 1.31,
      small: 1.33,
      label: 1.38,
      caption: 1.33,
      number: 1.1,
    },
  },
  ink: {
    text: INK_BLACK,
    /** Deliberately darker than Apple's `secondaryLabel` (about 3.4:1): 4.91:1 on the grouped grey holds the AA the
     * rest of the app holds itself to, and the HIG's accessibility guidance outranks its colour picker. */
    secondary: '#5F6B7C',
    border: '#E7EAF0',
    /** Outline of a form control a value is typed into: ≥3:1 on card, page and chart grid (WCAG 1.4.11). */
    control: '#7C8698',
    card: CARD_WHITE,
    /** The platform's grouped background. */
    page: '#F2F2F7',
    /** A slightly raised surface inside a card — list rows, wells, the month cells. */
    sunken: '#F7F8FB',
  },
  /** The action colour: Facebook blue. `main` is deep enough for white text (4.73:1); `bright` is for icons,
   * gradients and accents where nothing sits on top of it, and must never carry text. */
  accent: {
    main: '#166FE5',
    bright: '#3B82F6',
    /** Tinted chip/background; it carries `deep` text at 6.34:1 (`main` on it is only 4.12:1). */
    soft: '#E8F0FE',
    /** Hover/active of `main`. */
    deep: '#0B5FCE',
  },
  /** One colour per metric, used identically in rings, charts, the report and legends. The weight family is the
   * brand blue; the rest are the same meanings in a colder, more saturated set so no chart reads as a rainbow.
   * The iOS system colours were rejected here: `systemGreen` #34C759 is 2.28:1 on white and `systemOrange` #FF9500
   * is 2.06:1, both below the 3:1 floor a chart line or a ring needs (WCAG 1.4.11). */
  metric: {
    weight: '#166FE5',
    calories: '#C2410C',
    protein: '#7C3AED',
    carbs: '#A16207',
    fat: '#0E7490',
    water: '#0369A1',
    steps: '#15803D',
    sleep: '#4338CA',
    fatMass: '#9D174D',
    lean: '#047857',
    fasting: '#475569',
  },
  /** The gradient a metric card is filled with, [from, to] left to right. White text passes 4.5:1 at both stops.
   * One surface per screen carries it (the Dashboard hero): everywhere else a metric is a tasteful accent. */
  gradient: {
    weight: ['#0B4FC4', '#166FE5'],
    calories: ['#9A3412', '#C2410C'],
    protein: ['#5B21B6', '#7C3AED'],
    carbs: ['#713F12', '#A16207'],
    fat: ['#155E75', '#0E7490'],
    water: ['#0C4A6E', '#0369A1'],
    steps: ['#14532D', '#15803D'],
    sleep: ['#312E81', '#4338CA'],
    fatMass: ['#831843', '#9D174D'],
    lean: ['#064E3B', '#047857'],
    fasting: ['#1E293B', '#475569'],
  },
  /** Status only — never used for a metric. Each is ≥4.5:1 on white both ways (as text, and white text on it). */
  status: { good: '#15803D', warning: '#B45309', flag: '#DC2626' },
  /** The printed report (SPEC §11 print: black text on white): body text, secondary text, the running header. */
  print: { text: '#000000', secondary: '#333333', header: '#444444', page: '#FFFFFF' },
  chart: {
    grid: '#EDF0F5',
    lineWidth: 2,
    areaOpacity: 0.12,
    bandOpacity: 0.12,
    barRadius: 6,
    target: '#9CA3AF',
    targetDash: '4 4',
    axis: '#5F6B7C',
    axisFontSize: 12,
  },
  /** Muscle map: light grey body and four solid blue steps (12/40/70/100 % of the brand blue over the grey). */
  muscleMap: {
    body: '#E5E7EB',
    stroke: '#FFFFFF',
    steps: ['#D6E4FB', '#A8C6F5', '#5E9CEF', '#166FE5'] as const,
  },
  /** A defined radius hierarchy, not one value everywhere: a card is the largest, a control inside it steps down,
   * and a chip or a pill is fully round. Roughly Apple's continuous corners; `corner-shape: squircle` is not yet
   * broadly supported, so a plain radius is the closest available. */
  radius: { card: 16, control: 10, inner: 8, chip: 999 },
  /**
   * Translucent materials — a floating functional layer that brings structure without stealing focus. Each has a
   * solid fallback for `prefers-reduced-transparency` (see `chromeSurface`/`sheetSurface` below and the MUI
   * overrides) and a defined edge for `prefers-contrast: more`. Never stack a light material on another: over the
   * grouped grey the sheet sits on, legibility holds because only one layer is translucent.
   */
  material: {
    /** The nav layer: top bar, bottom tabs, rail. Light enough to read through, heavy enough to hold a title. */
    chrome: { fill: 'rgba(255,255,255,0.74)', blur: 'blur(20px) saturate(180%)' },
    /** A sheet or a menu: the thicker material, which also reads as the closer layer. */
    sheet: { fill: 'rgba(255,255,255,0.88)', blur: 'blur(30px) saturate(180%)' },
    /** Behind a modal task: dim to focus. */
    scrim: 'rgba(0,0,0,0.32)',
    /** The row/card press state — a highlight on pointer-DOWN, never a ripple. */
    press: 'rgba(17,24,39,0.05)',
    /** The bright top edge where light catches the material. */
    edge: 'rgba(255,255,255,0.6)',
  },
  /** Depth is surface contrast first: on the grouped grey a white card needs only a whisper of a shadow, and only
   * genuinely floating layers (sheets, menus, the quick-log button) get a real one. */
  elevation: {
    card: '0 1px 3px rgba(16,24,40,0.04), 0 8px 24px -20px rgba(16,24,40,0.14)',
    raised: '0 2px 6px rgba(16,24,40,0.05), 0 14px 34px -20px rgba(16,24,40,0.16)',
    overlay: '0 24px 64px -24px rgba(16,24,40,0.30)',
    /** Under the one floating control (the quick-log button) and the active rail tile. Neutral, not a coloured
     * glow: a coloured shadow reads as decoration rather than depth. */
    floating: '0 6px 18px -6px rgba(16,24,40,0.32), 0 2px 4px rgba(16,24,40,0.08)',
    /** Kept for the blue surfaces that still want to lift (the active rail tile). */
    accent: '0 6px 18px -8px rgba(22,111,229,0.35)',
  },
  /**
   * Motion, in Apple's terms: a *response* in seconds (a spring has no fixed duration — its settle time emerges
   * from its parameters) rather than a prescribed length. `base` is the default response of 0.32 s; the values stay
   * as milliseconds because that is what CSS takes. Nothing animates a layout property — only `opacity` and
   * `transform` — so an entrance can never shift content and cost CLS. Under `prefers-reduced-motion` the helpers
   * below keep a short cross-fade and drop the movement, because reduced motion asks for a gentler equivalent rather
   * than for nothing.
   */
  motion: {
    duration: { instant: 100, fast: 200, base: 320, slow: 420, slower: 560 },
    easing: {
      /** A strong decelerate: something entering or settling. */
      enter: 'cubic-bezier(0.32, 0.72, 0, 1)',
      /** Its exact mirror — the outbound path retraces the return path, so a reversible transition never jumps. */
      exit: 'cubic-bezier(1, 0, 0.68, 0.28)',
      /** A value changing in place. */
      standard: 'cubic-bezier(0.4, 0, 0.2, 1)',
    },
    /** The entrance spring's curve, or `null` where the browser takes no `linear()`. Read it through the
     * `enterEasing()` + `enterDuration()` pair rather than directly: those two are what must agree. */
    spring: SPRING,
    /** How long that spring takes to settle, derived from its own parameters. */
    enterDuration: ENTER_DURATION,
    /** How far an entering element rises, in px. Small on purpose: a large travel reads as a slideshow. */
    rise: 10,
  },
  /** 4 px base spacing scale, with the rhythm the layouts are actually built on named. */
  space: (n: number) => n * 4,
  /** Membership is spacing: inside a control, between rows of one group, between blocks, between sections, between
   * the page's major groups. */
  rhythm: { tight: 8, group: 16, block: 24, section: 32, page: 48 },
  tapTarget: 44,
  /** Keyboard focus ring (WCAG 2.4.7): ink, never a data colour. */
  focusRing: { width: 2, offset: 2 },
  layout: {
    phoneWidth: 390,
    maxContent: 1120,
    bottomNavHeight: 64,
    /** The desktop navigation rail's width (mobile keeps the bottom bar). */
    railWidth: 76,
    /** Scroll padding so a focused control never lands under the sticky top bar or the bottom nav + log button (WCAG 2.4.11). */
    scrollPadding: { top: 72, bottom: 152 },
  },
} as const

export type MetricKey = keyof typeof tokens.metric

/** Media query for the reduced-motion preference (WCAG 2.3.3): no springs or slides, short cross-fades instead. */
export const REDUCED_MOTION_QUERY = '(prefers-reduced-motion: reduce)'

/** Reduced transparency: a translucent surface turns opaque rather than blurring (`chromeSurface`/`sheetSurface`). */
export const REDUCED_TRANSPARENCY_QUERY = '(prefers-reduced-transparency: reduce)'

/** More contrast: a translucent surface turns opaque and gains a defined border. */
export const MORE_CONTRAST_QUERY = '(prefers-contrast: more)'

/** True when the viewer asked for reduced motion. Safe outside a browser (false). */
export function prefersReducedMotion(): boolean {
  return typeof window !== 'undefined' && typeof window.matchMedia === 'function' && window.matchMedia(REDUCED_MOTION_QUERY).matches
}

/** Scroll behaviour that honours the reduced-motion preference. */
export function scrollBehavior(): ScrollBehavior {
  return prefersReducedMotion() ? 'auto' : 'smooth'
}

/** Hex colour with alpha (0–1), e.g. the 12 % forecast band. */
export function withAlpha(hex: string, alpha: number): string {
  const a = Math.round(Math.min(1, Math.max(0, alpha)) * 255)
    .toString(16)
    .padStart(2, '0')
  return `${hex}${a}`
}

/** The CSS gradient for a metric card, left to right. */
export function metricGradient(metric: MetricKey): string {
  const [from, to] = tokens.gradient[metric]
  return `linear-gradient(135deg, ${from} 0%, ${to} 100%)`
}

/**
 * True when the browser can animate with a `linear()` easing curve (Safari 17.2+, Chrome 113+). The probe itself
 * happened once, when `SPRING` was built at module load, so this is only a read.
 */
export function supportsSpring(): boolean {
  return SPRING !== null
}

/**
 * The easing an entrance settles with: a real critically damped spring where the browser takes `linear()`, and the
 * equivalent strong-decelerate cubic-bézier where it doesn't. `easing.exit` is the exact mirror of the fallback, so
 * a reversible transition still retraces its path either way.
 */
export function enterEasing(): string {
  return SPRING ?? tokens.motion.easing.enter
}

/**
 * How long an entrance takes: the settle time the spring derives from its own parameters, never a number chosen for
 * it. Always pair this with `enterEasing()` — a spring curve given less time than it needs is cut off mid-settle, and
 * one given more sits motionless at the end of its travel while the user waits for it.
 */
export function enterDuration(): number {
  return ENTER_DURATION
}

/**
 * The entrance to play when the viewer prefers reduced motion: a short cross-fade and no travel at all, where a
 * spring would have risen and settled. Returns `animation`'s shorthand value, so a caller can pass it straight through
 * either way — `'none'` when motion is not reduced. Takes `reduced` rather than reading the media query itself so a
 * caller's `useMediaQuery` is what drives a re-render when the preference changes.
 */
export function reducedEntrance(delay: number, reduced: boolean): string {
  if (!reduced) return 'none'
  return `${tokens.motion.duration.fast}ms ${tokens.motion.easing.standard} ${delay}ms both crossFadeIn`
}

/**
 * The properties that still aid comprehension when motion is reduced, so they keep a short cross-fade instead of
 * losing their transition: colour, opacity and elevation carry meaning on their own. Travel and scale (`transform`,
 * `width`) are the opposite — they are exactly what a motion-sensitive viewer asked to be spared.
 */
const REDUCED_MOTION_SURVIVORS = /^(opacity|color|background-color|border-color|outline-color|box-shadow|fill|stroke)$/

/**
 * A transition string for the given properties. Every hand-written transition in the app goes through this, so the
 * reduced-motion preference cannot be forgotten in one place (WCAG 2.3.3).
 *
 * Reduced motion means a *gentler equivalent*, not the absence of one: the HIG asks for cross-fades in place of
 * slides and springs. So under the preference this keeps the changes that still help — a colour, an opacity, a shadow —
 * at the instant step, and drops only the movement. (It previously returned `none` for everything, which quietly
 * deleted the cross-fades the app had promised to keep.)
 *
 * Note that MUI's CssBaseline squashes *every* transition duration to 0.01 ms under this same preference, so in the
 * running app those survivors arrive instantly rather than over `instant`. That is left as it is, deliberately: what
 * remains after the movement is dropped is a colour or an opacity, which reads correctly as an immediate change, and
 * relaxing the blanket rule would put MUI's own drawer and popover travel back on screen. The policy is still stated
 * here, so it survives a change to the baseline underneath it.
 */
export function transitionOf(
  properties: string | readonly string[],
  duration: number = tokens.motion.duration.base,
  easing: string = tokens.motion.easing.standard,
): string {
  const list = typeof properties === 'string' ? [properties] : properties
  if (prefersReducedMotion()) {
    const kept = list
      .map((p) => p.trim())
      .filter((p) => REDUCED_MOTION_SURVIVORS.test(p))
      .map((p) => `${p} ${tokens.motion.duration.instant}ms ${tokens.motion.easing.standard}`)
    return kept.join(', ') || 'none'
  }
  return list.map((p) => `${p} ${duration}ms ${easing}`).join(', ')
}

/**
 * The nav layer's material, spread into the `sx` of the element that owns the fixed/sticky box (not an inner bar, so
 * the blur covers the safe-area inset too). Under reduced transparency it becomes opaque, and under more contrast
 * opaque with a defined divider — the two preferences a translucent chrome would otherwise ignore.
 */
export const chromeSurface = {
  backgroundColor: tokens.material.chrome.fill,
  backdropFilter: tokens.material.chrome.blur,
  WebkitBackdropFilter: tokens.material.chrome.blur,
  '@media (prefers-reduced-transparency: reduce)': { backgroundColor: tokens.ink.card, backdropFilter: 'none', WebkitBackdropFilter: 'none' },
  '@media (prefers-contrast: more)': { backgroundColor: tokens.ink.card, borderColor: tokens.ink.text },
} as const

/** The thicker material: a sheet, the Ask AI panel, the command palette. Same fallbacks as the chrome. */
export const sheetSurface = {
  backgroundColor: tokens.material.sheet.fill,
  backdropFilter: tokens.material.sheet.blur,
  WebkitBackdropFilter: tokens.material.sheet.blur,
  '@media (prefers-reduced-transparency: reduce)': { backgroundColor: tokens.ink.card, backdropFilter: 'none', WebkitBackdropFilter: 'none' },
  '@media (prefers-contrast: more)': { backgroundColor: tokens.ink.card, borderColor: tokens.ink.text },
} as const

declare module '@mui/material/styles' {
  interface Palette {
    metric: typeof tokens.metric
    ink: typeof tokens.ink
    accent: typeof tokens.accent
  }
  interface PaletteOptions {
    metric?: typeof tokens.metric
    ink?: typeof tokens.ink
    accent?: typeof tokens.accent
  }
  interface TypographyVariants {
    bigNumber: React.CSSProperties
    label: React.CSSProperties
    sectionTitle: React.CSSProperties
  }
  interface TypographyVariantsOptions {
    bigNumber?: React.CSSProperties
    label?: React.CSSProperties
    sectionTitle?: React.CSSProperties
  }
}

declare module '@mui/material/Typography' {
  interface TypographyPropsVariantOverrides {
    bigNumber: true
    label: true
    sectionTitle: true
  }
}

const { ink, font, radius, accent, elevation, motion, material } = tokens

/** A press state: instant, on pointer-DOWN, and never a ripple. Removed under reduced motion, because a scale is
 * exactly the vestibular feedback that preference asks us to drop. */
const press = (transform: string, background?: string) => ({
  '&:active': { transform, ...(background ? { backgroundColor: background } : {}) },
  '@media (prefers-reduced-motion: reduce)': { '&:active': { transform: 'none' } },
})

export const theme = createTheme({
  cssVariables: true,
  palette: {
    mode: 'light',
    primary: { main: accent.main, dark: accent.deep, light: accent.bright, contrastText: '#FFFFFF' },
    secondary: { main: tokens.metric.water },
    success: { main: tokens.status.good },
    warning: { main: tokens.status.warning },
    error: { main: tokens.status.flag },
    text: { primary: ink.text, secondary: ink.secondary },
    divider: ink.border,
    background: { default: ink.page, paper: ink.card },
    // MUI's own defaults here are pure-black alphas — the only colours in the app that would not come from `ink`. They
    // are derived from the ink token instead, and lifted enough that an unavailable control is still legible (≈3.2:1 on
    // white) rather than a ghost. WCAG 1.4.3 exempts inactive controls from the contrast requirement; this is a choice
    // about which greys the app is made of, not a rule being satisfied.
    action: { disabled: withAlpha(ink.text, 0.5), disabledBackground: withAlpha(ink.text, 0.12) },
    metric: tokens.metric,
    ink,
    accent,
  },
  shape: { borderRadius: radius.control },
  spacing: 4,
  typography: {
    fontFamily: font.family,
    fontSize: font.size.body,
    htmlFontSize: 16,
    // Size, weight, leading and tracking as one decision per step, never size alone. The heading variants carry the
    // scale's top four steps, so `h1`/`h2`/`h3`/`h4` stay the app's names for Large Title / Title 1 / Title 2 / Title 3.
    body1: { fontSize: font.size.body, fontWeight: font.weight.body, lineHeight: font.leading.body, letterSpacing: font.tracking.body },
    body2: { fontSize: font.size.small, fontWeight: font.weight.body, lineHeight: font.leading.small, letterSpacing: font.tracking.small, color: ink.secondary },
    button: { fontWeight: font.weight.label, textTransform: 'none', fontSize: font.size.emphasis, letterSpacing: font.tracking.emphasis },
    h1: { fontSize: font.size.largeTitle, fontWeight: font.weight.heading, lineHeight: font.leading.largeTitle, letterSpacing: font.tracking.largeTitle },
    h2: { fontSize: font.size.title1, fontWeight: font.weight.heading, lineHeight: font.leading.title1, letterSpacing: font.tracking.title1 },
    h3: { fontSize: font.size.sectionTitle, fontWeight: font.weight.heading, lineHeight: font.leading.sectionTitle, letterSpacing: font.tracking.sectionTitle },
    h4: { fontSize: font.size.cardTitle, fontWeight: font.weight.heading, lineHeight: font.leading.cardTitle, letterSpacing: font.tracking.cardTitle },
    sectionTitle: {
      fontSize: font.size.sectionTitle,
      fontWeight: font.weight.heading,
      lineHeight: font.leading.sectionTitle,
      letterSpacing: font.tracking.sectionTitle,
    },
    label: { fontSize: font.size.label, fontWeight: font.weight.label, lineHeight: font.leading.label, letterSpacing: font.tracking.label, color: ink.secondary },
    caption: { fontSize: font.size.caption, fontWeight: font.weight.body, lineHeight: font.leading.caption, letterSpacing: font.tracking.caption },
    bigNumber: {
      fontSize: font.size.bigNumber,
      fontWeight: font.weight.number,
      lineHeight: font.leading.number,
      letterSpacing: font.tracking.number,
      fontVariantNumeric: 'tabular-nums',
      fontFeatureSettings: '"tnum"',
    },
  },
  components: {
    MuiCssBaseline: {
      styleOverrides: {
        // The grey tap flash is the web's ripple: gone. Touch feedback is the press state each control owns.
        '*, *::before, *::after': { WebkitTapHighlightColor: 'transparent' },
        body: {
          backgroundColor: ink.page,
          color: ink.text,
          WebkitFontSmoothing: 'antialiased',
          // The system face already varies its design with size; asking for it explicitly keeps that behaviour when a
          // weight or a feature setting changes the face underneath.
          fontOpticalSizing: 'auto',
          textSizeAdjust: '100%',
          // The canvas is a soft tint, so the document itself should not paint a white gutter behind it (overscroll).
          backgroundAttachment: 'fixed',
        },
        // A long press must not open a callout over a control (iOS Safari), the way it does over text.
        'button, a': { WebkitTouchCallout: 'none', textDecoration: 'none' },
        // The reduced-motion entrance, global because more than one primitive plays it (see `reducedEntrance`). It is
        // a keyframe animation rather than a transition on purpose: an animation plays from the element's first paint
        // on the browser's own clock, so this cross-fade does not wait on a JavaScript frame that a throttled or
        // non-compositing window may never deliver.
        '@keyframes crossFadeIn': { from: { opacity: 0 }, to: { opacity: 1 } },
        // MUI's own baseline squashes every animation and transition to 0.01 ms under this preference — a blanket
        // removal, which is the one thing the HIG is explicit that reduced motion must *not* be: it asks for
        // cross-fades in place of slides and springs. This gives the keyframe above back the time it was built for.
        // Transition durations are deliberately left squashed: everything the app keeps there is a colour or an
        // opacity, which reads correctly as an instant change, whereas relaxing them would put MUI's own drawer and
        // popover travel back on screen at a time the viewer asked not to see it.
        // The `html` prefix is load-bearing: MUI's rule is `*` with `!important` and it is emitted after this block,
        // so an equally specific selector here would lose. One element ahead of the universal selector wins outright.
        '@media (prefers-reduced-motion: reduce)': {
          'html *, html *::before, html *::after': { animationDuration: `${tokens.motion.duration.fast}ms !important` },
        },
      },
    },
    // Every custom button (ButtonBase in an sx) gets the same visible keyboard focus ring; MUI's own buttons keep their
    // focus tint underneath it. The ripple is off app-wide: a Material ripple is the one interaction the HIG would
    // never do, and each control below replaces it with an instant press state.
    MuiButtonBase: {
      defaultProps: { disableRipple: true },
      styleOverrides: {
        root: {
          WebkitTapHighlightColor: 'transparent',
          '&.Mui-focusVisible': { outline: `${tokens.focusRing.width}px solid ${ink.text}`, outlineOffset: tokens.focusRing.offset },
        },
      },
    },
    MuiPaper: { defaultProps: { elevation: 0 } },
    // Surfaces are separated by depth, not by an outline: the grouped grey behind a white card is the separation, and
    // the shadow stays a whisper. A hairline is kept only for the printed report and for a card sitting on a card
    // (`& &`), where a shadow would read as a stack of floating panels.
    MuiCard: {
      defaultProps: { elevation: 0 },
      styleOverrides: {
        root: {
          borderRadius: radius.card,
          border: 'none',
          backgroundColor: ink.card,
          boxShadow: elevation.card,
          '& &': { boxShadow: 'none', border: `1px solid ${ink.border}` },
        },
      },
    },
    // Apple's four button styles, mapped onto the three variants the app already uses: `contained` is filled,
    // `outlined` is the neutral grey one (a quiet secondary action next to the one filled button on screen), and
    // `text` is plain — accent text, no surface. A 1 px outline is none of them.
    MuiButton: {
      defaultProps: { disableElevation: true },
      styleOverrides: {
        root: {
          minHeight: tokens.tapTarget,
          borderRadius: radius.control,
          fontWeight: font.weight.label,
          paddingLeft: tokens.space(4),
          paddingRight: tokens.space(4),
          transition: `background-color ${motion.duration.fast}ms ${motion.easing.standard}, transform ${motion.duration.instant}ms ${motion.easing.standard}, box-shadow ${motion.duration.fast}ms ${motion.easing.standard}`,
          ...press('scale(0.97)'),
        },
        // MUI derives the hover shade for a contained button from `palette.primary.dark`, so the blue deepens on
        // hover without a colour-specific override here. A filled button does not float.
        contained: { boxShadow: 'none', '&:hover': { boxShadow: 'none' } },
        outlined: {
          border: 'none',
          backgroundColor: withAlpha(ink.text, 0.06),
          color: ink.text,
          '@media (hover: hover)': { '&:hover': { backgroundColor: withAlpha(ink.text, 0.1) } },
        },
        text: { '@media (hover: hover)': { '&:hover': { backgroundColor: withAlpha(accent.main, 0.08) } } },
        // A small button keeps the 44 px floor from `root` (SPEC §11) and only tightens its padding and text: a 36 px
        // target is under the minimum the rest of the app holds itself to.
        sizeSmall: { paddingLeft: tokens.space(3), paddingRight: tokens.space(3), fontSize: font.size.small },
        sizeLarge: { minHeight: 50, fontSize: font.size.body },
      },
    },
    // An icon button is a circular target: a tinted circle on hover, a slightly deeper one on press, never a square
    // ripple. The circle is drawn from the ink so it reads on a card and on the grey page alike.
    MuiIconButton: {
      styleOverrides: {
        root: {
          minWidth: tokens.tapTarget,
          minHeight: tokens.tapTarget,
          borderRadius: '50%',
          transition: `background-color ${motion.duration.fast}ms ${motion.easing.standard}, transform ${motion.duration.instant}ms ${motion.easing.standard}`,
          '@media (hover: hover)': { '&:hover': { backgroundColor: withAlpha(ink.text, 0.06) } },
          ...press('scale(0.94)', withAlpha(ink.text, 0.1)),
        },
      },
    },
    // A tappable chip or menu row is a tap target too (SPEC §11: 44 px), whatever size an sx asks for. An outlined
    // chip becomes the neutral grey pill the HIG uses for a non-semantic tag; a coloured (filled) chip keeps its
    // colour, because there it means something.
    MuiChip: {
      styleOverrides: {
        root: {
          fontWeight: font.weight.label,
          fontSize: font.size.label,
          letterSpacing: font.tracking.label,
          borderRadius: radius.chip,
          transition: `background-color ${motion.duration.fast}ms ${motion.easing.standard}`,
        },
        outlined: { border: 'none', backgroundColor: withAlpha(ink.text, 0.06), color: ink.text },
        clickable: { minHeight: tokens.tapTarget, '@media (hover: hover)': { '&:hover': { backgroundColor: withAlpha(ink.text, 0.1) } } },
      },
    },
    // Full-width rows sit flush with a scrolling (clipping) parent, so their focus ring is drawn inside the row.
    MuiMenuItem: {
      styleOverrides: {
        root: {
          minHeight: tokens.tapTarget,
          '&.Mui-focusVisible': { outlineOffset: -tokens.focusRing.width },
          '@media (hover: hover)': { '&:hover': { backgroundColor: withAlpha(ink.text, 0.06) } },
        },
      },
    },
    MuiListItemButton: {
      styleOverrides: {
        root: {
          '&.Mui-focusVisible': { outlineOffset: -tokens.focusRing.width },
          ...press('none', material.press),
        },
      },
    },
    MuiCardActionArea: { styleOverrides: { root: { '&.Mui-focusVisible': { outlineOffset: -tokens.focusRing.width } } } },
    // An alert is a *tinted* surface, not a rule: the severity shows as a low-alpha wash of its own colour, with the
    // icon carrying the hue and the text at full ink. The outlined variant (a failed read) takes the same wash rather
    // than a 1 px border, which was the last Material separator left in the app.
    MuiAlert: {
      styleOverrides: {
        root: {
          borderRadius: radius.card,
          fontSize: font.size.small,
          letterSpacing: font.tracking.small,
          alignItems: 'center',
        },
        outlined: ({ ownerState, theme }) => {
          const tone = theme.palette[ownerState.severity ?? 'info'].main
          return {
            border: 'none',
            backgroundColor: withAlpha(tone, 0.12),
            color: ink.text,
            '& .MuiAlert-icon': { color: tone },
          }
        },
      },
    },
    MuiOutlinedInput: {
      styleOverrides: {
        root: {
          borderRadius: radius.control,
          backgroundColor: ink.card,
          transition: `box-shadow ${motion.duration.fast}ms ${motion.easing.standard}`,
        },
      },
    },
    // A dialog is a sheet with a scrim: the paper takes the card radius and the overlay shadow, and the scrim is the
    // app's own token rather than MUI's pure black at 50 %.
    MuiDialog: { styleOverrides: { paper: { borderRadius: radius.card, boxShadow: elevation.overlay } } },
    MuiBackdrop: { styleOverrides: { root: { backgroundColor: material.scrim } } },
    MuiDrawer: {
      styleOverrides: {
        paper: { borderRadius: `${radius.card}px ${radius.card}px 0 0`, boxShadow: elevation.overlay },
      },
    },
    MuiPopover: { styleOverrides: { paper: { borderRadius: radius.card, boxShadow: elevation.overlay, border: `1px solid ${withAlpha(ink.text, 0.06)}` } } },
    MuiMenu: { styleOverrides: { paper: { borderRadius: radius.card, boxShadow: elevation.overlay, border: `1px solid ${withAlpha(ink.text, 0.06)}` } } },
    MuiTooltip: { styleOverrides: { tooltip: { borderRadius: radius.inner, backgroundColor: ink.text, fontSize: font.size.label, letterSpacing: font.tracking.label } } },
    MuiTextField: { defaultProps: { fullWidth: true, size: 'medium' } },
    // A switch's touch target (its input fills the thumb's button) is 44 px tall, not MUI's 38: the button gets 12 px
    // around the 20 px thumb, the track (34 × 14) keeps its place centred under it, so it looks the same.
    MuiSwitch: {
      styleOverrides: {
        root: {
          '&.MuiSwitch-sizeMedium': {
            width: 34 + 2 * 15,
            height: tokens.tapTarget,
            padding: 15,
            '& .MuiSwitch-switchBase': { padding: (tokens.tapTarget - 20) / 2 },
          },
        },
      },
    },
    // The bars are a translucent material owned by the fixed element around them (BottomTabs/NavRail), so the MUI
    // root itself is flat and borderless: no hairline separator, just the material and the active item's tint.
    MuiBottomNavigation: { styleOverrides: { root: { height: tokens.layout.bottomNavHeight, backgroundColor: 'transparent' } } },
    MuiBottomNavigationAction: {
      styleOverrides: {
        root: {
          minWidth: 0,
          paddingTop: 6,
          '&.Mui-focusVisible': { outlineOffset: -tokens.focusRing.width },
          color: ink.secondary,
          '&.Mui-selected': { color: accent.main },
          // Feedback on the press, and on the glyph rather than the row, so the label never shifts.
          '& .MuiSvgIcon-root': { transition: `transform ${motion.duration.fast}ms ${motion.easing.standard}` },
          '&:active .MuiSvgIcon-root': { transform: 'scale(0.88)' },
          '@media (prefers-reduced-motion: reduce)': { '&:active .MuiSvgIcon-root': { transform: 'none' } },
        },
        label: { fontSize: font.size.caption, letterSpacing: font.tracking.caption, '&.Mui-selected': { fontSize: font.size.caption } },
      },
    },
    MuiLinearProgress: {
      styleOverrides: { root: { borderRadius: radius.chip, height: 6 }, bar: { borderRadius: radius.chip } },
    },
    // A bottom snackbar sits above the bottom nav and the home indicator, never over the tabs (at every width: MUI's
    // own wider-screen offset is replaced too). It is the thicker material, so it reads as floating over the page.
    MuiSnackbar: {
      styleOverrides: {
        root: ({ ownerState, theme }) => {
          if (ownerState.anchorOrigin?.vertical === 'top') return {}
          const bottom = `calc(${tokens.layout.bottomNavHeight + tokens.space(2)}px + env(safe-area-inset-bottom, 0px))`
          return { bottom, [theme.breakpoints.up('sm')]: { bottom } }
        },
      },
    },
    MuiSnackbarContent: { styleOverrides: { root: { borderRadius: radius.control, backgroundColor: ink.text, color: ink.card } } },
  },
})
