-- Owns: the equipment profile and exercise exclusions of a database seeded before 2026-10-06, moved onto the
-- machines at Anytime Fitness Lacombe (seed/equipment/anytime-fitness.json) — 47 machines grouped by area, the
-- library values he does and does not have, and the exercises that follow from it.
-- GENERATED by apps/worker/scripts/build-equipment-inventory.ts (pnpm db:equipment). Do not edit by hand.

INSERT OR IGNORE INTO equipment_profile (id, equipment, kind, status, note, area)
SELECT v.column1, v.column2, v.column3, v.column4, v.column5, v.column6 FROM (VALUES
  ('475135d3-ba89-5982-8f11-7e29dfd6f9ba', 'barbell', 'library', 'have', 'Olympic bars and plates at the squat rack platform.', NULL),
  ('d63b4f7e-3387-5e43-ba61-0fcefdb76f18', 'dumbbell', 'library', 'have', 'Hammer Strength rack, 2.5–75+ lb.', NULL),
  ('af7d8240-faed-5cc7-8f59-5c4236a7217b', 'cable', 'library', 'have', 'Four cable stations: crossover, dual pulley, adjustable pulley, four-stack tower.', NULL),
  ('d738e68b-9778-5c10-8e9f-028fa3da42c8', 'machine', 'library', 'have', 'Hammer Strength plate-loaded, MTS and selectorized line.', NULL),
  ('adf619c4-644a-5045-9502-5b4d4a39008e', 'kettlebells', 'library', 'have', 'Stored on the functional training rig.', NULL),
  ('faab7192-178e-5f8d-8f16-fa1936acf760', 'medicine ball', 'library', 'have', 'Stored on the functional training rig.', NULL),
  ('6d169883-7141-5146-91e2-790315f6c3f7', 'e-z curl bar', 'library', 'have', 'Fixed Hammer Strength rack, 20–110 lb.', NULL),
  ('a8bab55b-40da-5293-ab02-1998ddfab565', 'other', 'library', 'have', 'Plates, benches and bars; implements the gym does not have are excluded by name.', NULL),
  ('2554acf8-a7a8-5793-ab14-f03e9358cd90', 'bands', 'library', 'dont_have', 'No resistance bands on the floor.', NULL),
  ('58e72610-b424-577b-87e0-898bc8866373', 'exercise ball', 'library', 'dont_have', 'No exercise balls on the floor.', NULL),
  ('e90fb8cf-1094-5353-b63f-b31ebff4756c', 'foam roll', 'library', 'dont_have', 'No foam rollers on the floor.', NULL),
  ('34c7be46-4530-52b7-8c30-c6274d148103', 'body only', 'library', 'have', 'Bodyweight moves are excluded by default (see exclusions), not by status.', NULL),
  ('d2f16fe9-0bb0-5c2a-aedb-82005efddd72', 'low row', 'machine', 'have', 'Seated, selectorized.', 'Life Fitness'),
  ('cb3577d9-4ca3-58e9-8fa5-1e8d2ab1bcd8', 'lat pulldown', 'machine', 'have', 'Selectorized.', 'Life Fitness'),
  ('e38f4d12-d7cc-5842-a9e0-1baa4a4f170d', 'dual pulley pulldown', 'machine', 'have', 'Dual weight stacks.', 'Life Fitness'),
  ('54fe891a-de4f-57b3-8781-6c1fdbdf87b1', 'dual pulley row', 'machine', 'have', 'Dual weight stacks.', 'Life Fitness'),
  ('6647e47a-5dc5-56bd-a9ec-30e19d803a73', 'cable crossover', 'machine', 'have', 'Two adjustable pulleys.', 'Life Fitness'),
  ('8eb04ce9-3876-528c-9f45-a379c6d650d0', 'cable (adjustable pulley station)', 'machine', 'have', 'Pulley height adjusts; ankle straps for kickbacks and glute work.', 'Life Fitness'),
  ('7b37a44b-16df-55ef-bb87-1af9a55292fc', 'multi-station cable tower', 'machine', 'have', 'Four weight stacks.', 'Life Fitness'),
  ('1e370a6a-b49e-5d5e-9dc5-8f7ffe1a2a80', 'assist dip / chin', 'machine', 'have', 'Assisted pull-up and dip; stands in for hanging work.', 'Life Fitness'),
  ('5fa1572a-1726-500e-ad96-8ef5a6da2b86', 'linear leg press', 'machine', 'have', 'Calf press on the same machine.', 'Life Fitness'),
  ('48160be2-230d-5e87-91da-8f88f7deb206', 'smith machine', 'machine', 'have', 'Guided bar; a bench in it covers most barbell presses.', 'Life Fitness'),
  ('68f33453-8269-53e3-8236-13884cd041b2', 'hip abduction / adduction', 'machine', 'have', 'One machine, both directions.', 'Life Fitness'),
  ('6ff4522d-1b11-5472-ae4b-f50dbbe041b1', 'abdominal crunch', 'machine', 'have', 'Plate-loaded.', 'Hammer Strength'),
  ('28c33844-fb43-5a28-9af2-fd180f0ddbbb', 'iso-lateral row', 'machine', 'have', 'Plate-loaded; covers iso and high rows.', 'Hammer Strength'),
  ('3272cbef-b040-5736-a1c0-7fa47cc0e083', 'iso-lateral shoulder press', 'machine', 'have', 'Plate-loaded.', 'Hammer Strength'),
  ('b9acfcd5-fd75-5cc0-a679-5957952c7a8c', 'iso-lateral horizontal bench press', 'machine', 'have', 'Plate-loaded.', 'Hammer Strength'),
  ('b380a506-8ede-5eb3-a4ca-11ca9721573c', 'iso-lateral incline press', 'machine', 'have', 'Plate-loaded.', 'Hammer Strength'),
  ('1372c929-2531-5268-a0a2-d637dfaadcf4', 'v-squat', 'machine', 'have', 'Plate-loaded; stands in for the hack squat.', 'Hammer Strength'),
  ('0639e5fb-1c11-5639-b853-cf11aade973c', 'seated arm curl (preacher)', 'machine', 'have', 'Plate-loaded preacher station.', 'Hammer Strength'),
  ('d5aab323-e2de-52fe-b49c-5f54ea76de56', 'mts biceps curl', 'machine', 'have', 'MTS, selectorized.', 'Hammer Strength'),
  ('6db7990b-5c37-55da-8101-f16f6072cbc3', 'mts triceps extension', 'machine', 'have', 'MTS, selectorized.', 'Hammer Strength'),
  ('9f38fa62-b3ba-57d6-a6aa-10e039a507a8', 'mts decline press', 'machine', 'have', 'MTS, selectorized.', 'Hammer Strength'),
  ('429cc83a-2de4-59bd-ac16-a265ce40e3d5', 'mts incline press', 'machine', 'have', 'MTS, selectorized.', 'Hammer Strength'),
  ('d8c59680-ec06-51d2-9a45-7bbf58160018', 'chest press', 'machine', 'have', 'Selectorized.', 'Hammer Strength'),
  ('b21ee0fd-3fa6-5ba1-996a-da2788dfc968', 'seated leg press', 'machine', 'have', 'Selectorized; calf press on the footplate.', 'Hammer Strength'),
  ('7f5ee2c5-4fe3-58d8-9460-f2faedb75c05', 'seated leg curl', 'machine', 'have', 'Selectorized.', 'Hammer Strength'),
  ('18e39812-1c54-55fc-bef3-b55057cc4df4', 'lying leg curl', 'machine', 'have', 'Selectorized.', 'Hammer Strength'),
  ('6bef2e81-afcf-5ff7-8ae2-bcd5cdf2cd23', 'leg extension', 'machine', 'have', 'Selectorized.', 'Hammer Strength'),
  ('e7b37290-2f65-5852-987d-2af5ded02f68', 'standing calf raise', 'machine', 'have', 'Selectorized, standing only (no seated calf machine); shoulder pads take calf-machine shrugs.', 'Hammer Strength'),
  ('1b599766-10dc-5126-82b4-9701573a73bc', 'hip & glute', 'machine', 'have', 'Plate-loaded; hip extension and glute kickback.', 'Hammer Strength'),
  ('98013420-93c1-5ab3-8004-df46eef8a45d', 'pectoral fly / rear deltoid', 'machine', 'have', 'Pec deck and reverse fly.', 'Hammer Strength'),
  ('3352e19d-33d7-5507-9111-7db731e6c444', 'shoulder press (selectorized)', 'machine', 'have', 'Selectorized.', 'Hammer Strength'),
  ('c018df82-84dd-5702-a186-15c92e7ba29d', 'squat rack / power rack (with platform)', 'machine', 'have', 'Olympic bars and plates; deadlift platform.', 'Racks & rigs'),
  ('82501242-3520-5250-a37a-24775b266f76', 'half rack', 'machine', 'have', 'Multi-grip pull-up bar.', 'Racks & rigs'),
  ('fba2047d-b531-5771-b713-c4da46c227fb', 'power rack (functional area)', 'machine', 'have', NULL, 'Racks & rigs'),
  ('6389fa9b-56e3-5b14-9625-d8827f59b361', 'functional training rig', 'machine', 'have', 'Kettlebells and medicine balls stored here.', 'Racks & rigs'),
  ('a0eaa643-c2b0-5fe3-8d9e-ef2f7a3b2237', 'synergy360', 'machine', 'have', 'Life Fitness functional cable station.', 'Racks & rigs'),
  ('920412ae-169c-5fc0-8cb2-bcc027f2bc02', 'dumbbell rack', 'machine', 'have', 'Hammer Strength, 2.5–75+ lb.', 'Free weights'),
  ('7df55b49-04a3-5f0f-8e41-cee34f6d3200', 'fixed ez curl bar rack', 'machine', 'have', 'Hammer Strength, 20–110 lb.', 'Free weights')
) AS v WHERE EXISTS (SELECT 1 FROM exercises);
--> statement-breakpoint
INSERT OR IGNORE INTO equipment_profile (id, equipment, kind, status, note, area)
SELECT v.column1, v.column2, v.column3, v.column4, v.column5, v.column6 FROM (VALUES
  ('e19cab59-c9f6-555a-a447-d342448ea8e1', 'fixed straight barbell rack', 'machine', 'have', 'Life Fitness.', 'Free weights'),
  ('70563038-5abb-5007-8dfe-b90ea9d46313', 'adjustable bench', 'machine', 'have', 'Flat, incline and decline (not on Aaron''s list; assumed with the racks).', 'Free weights'),
  ('812b29b7-e2f9-5a9a-a618-5613745b768f', 'curved manual treadmill', 'machine', 'have', 'Self-powered, no motor.', 'Cardio'),
  ('23650c8a-96bf-5c52-aded-b3c55a335774', 'treadmill', 'machine', 'have', 'Life Fitness.', 'Cardio'),
  ('47c57ed3-145f-5d97-9a63-205e0630e69b', 'stair climber', 'machine', 'have', 'Life Fitness PowerMill.', 'Cardio'),
  ('df1e8057-5c7c-5352-ac89-763ea7703eef', 'upright bike', 'machine', 'have', 'Life Fitness Lifecycle.', 'Cardio'),
  ('274a19dd-fe9d-5892-9725-69f5b7d59e9e', 'indoor cycling bike', 'machine', 'have', 'Life Fitness.', 'Cardio'),
  ('2eb655cf-947c-5857-b866-94f9c154471c', 'indoor rower', 'machine', 'have', 'Life Fitness Row GX.', 'Cardio'),
  ('19b25cb8-7e57-50d0-a367-fe83a79cdee1', 'sparc arc trainer', 'machine', 'have', 'Hammer Strength.', 'Cardio'),
  ('f84a7b8e-9b95-57f3-b2df-b9b02101ad1d', 'air bike', 'machine', 'have', 'Hammer Strength fan bike.', 'Cardio'),
  ('f559e95c-3fb2-59c3-aa91-7ecb5f76172c', 't-bar row', 'machine', 'dont_have', 'No T-bar or landmine at your gym; row on the cables or the iso-lateral row.', NULL),
  ('b37321bb-a8f6-520f-8a50-58368af827ab', 'glute ham raise', 'machine', 'dont_have', 'No glute-ham developer.', NULL),
  ('9e1ec941-64e6-5e04-a4d1-6243eb48317d', 'reverse hyperextension', 'machine', 'dont_have', 'No reverse hyper.', NULL),
  ('8fbfd015-6ee0-51cd-b197-f4e55121d0b9', 'back extension', 'machine', 'dont_have', 'No back-extension bench.', NULL),
  ('860ff0f6-3dff-567d-82b7-753da793be19', 'lying machine squat', 'machine', 'dont_have', 'Squat in the rack or on the V-Squat.', NULL),
  ('56082cfb-bbbf-5060-9b79-0d2003556eb0', 'standing leg curl', 'machine', 'dont_have', 'Seated and lying leg curl only.', NULL),
  ('35868317-2d2e-5904-9379-9f1fdfa2b8a9', 'chair squat', 'machine', 'dont_have', 'No chair-squat station.', NULL),
  ('0d5d34a8-a36d-595b-bafe-3873bf213596', 'elliptical', 'machine', 'dont_have', 'Arc trainer and air bike instead.', NULL)
) AS v WHERE EXISTS (SELECT 1 FROM exercises);
--> statement-breakpoint
UPDATE `equipment_profile` SET `kind` = 'library', `note` = 'Olympic bars and plates at the squat rack platform.', `area` = NULL, `updated_at` = strftime('%Y-%m-%dT%H:%M:%fZ', 'now') WHERE `equipment` = 'barbell' AND EXISTS (SELECT 1 FROM exercises);
--> statement-breakpoint
UPDATE `equipment_profile` SET `kind` = 'library', `note` = 'Hammer Strength rack, 2.5–75+ lb.', `area` = NULL, `updated_at` = strftime('%Y-%m-%dT%H:%M:%fZ', 'now') WHERE `equipment` = 'dumbbell' AND EXISTS (SELECT 1 FROM exercises);
--> statement-breakpoint
UPDATE `equipment_profile` SET `kind` = 'library', `note` = 'Four cable stations: crossover, dual pulley, adjustable pulley, four-stack tower.', `area` = NULL, `updated_at` = strftime('%Y-%m-%dT%H:%M:%fZ', 'now') WHERE `equipment` = 'cable' AND EXISTS (SELECT 1 FROM exercises);
--> statement-breakpoint
UPDATE `equipment_profile` SET `kind` = 'library', `note` = 'Hammer Strength plate-loaded, MTS and selectorized line.', `area` = NULL, `updated_at` = strftime('%Y-%m-%dT%H:%M:%fZ', 'now') WHERE `equipment` = 'machine' AND EXISTS (SELECT 1 FROM exercises);
--> statement-breakpoint
UPDATE `equipment_profile` SET `kind` = 'library', `note` = 'Stored on the functional training rig.', `area` = NULL, `updated_at` = strftime('%Y-%m-%dT%H:%M:%fZ', 'now') WHERE `equipment` = 'kettlebells' AND EXISTS (SELECT 1 FROM exercises);
--> statement-breakpoint
UPDATE `equipment_profile` SET `kind` = 'library', `note` = 'Stored on the functional training rig.', `area` = NULL, `updated_at` = strftime('%Y-%m-%dT%H:%M:%fZ', 'now') WHERE `equipment` = 'medicine ball' AND EXISTS (SELECT 1 FROM exercises);
--> statement-breakpoint
UPDATE `equipment_profile` SET `kind` = 'library', `note` = 'Fixed Hammer Strength rack, 20–110 lb.', `area` = NULL, `updated_at` = strftime('%Y-%m-%dT%H:%M:%fZ', 'now') WHERE `equipment` = 'e-z curl bar' AND EXISTS (SELECT 1 FROM exercises);
--> statement-breakpoint
UPDATE `equipment_profile` SET `kind` = 'library', `note` = 'Plates, benches and bars; implements the gym does not have are excluded by name.', `area` = NULL, `updated_at` = strftime('%Y-%m-%dT%H:%M:%fZ', 'now') WHERE `equipment` = 'other' AND EXISTS (SELECT 1 FROM exercises);
--> statement-breakpoint
UPDATE `equipment_profile` SET `kind` = 'library', `note` = 'No resistance bands on the floor.', `area` = NULL, `status` = 'dont_have', `updated_at` = strftime('%Y-%m-%dT%H:%M:%fZ', 'now') WHERE `equipment` = 'bands' AND EXISTS (SELECT 1 FROM exercises);
--> statement-breakpoint
UPDATE `equipment_profile` SET `kind` = 'library', `note` = 'No exercise balls on the floor.', `area` = NULL, `status` = 'dont_have', `updated_at` = strftime('%Y-%m-%dT%H:%M:%fZ', 'now') WHERE `equipment` = 'exercise ball' AND EXISTS (SELECT 1 FROM exercises);
--> statement-breakpoint
UPDATE `equipment_profile` SET `kind` = 'library', `note` = 'No foam rollers on the floor.', `area` = NULL, `status` = 'dont_have', `updated_at` = strftime('%Y-%m-%dT%H:%M:%fZ', 'now') WHERE `equipment` = 'foam roll' AND EXISTS (SELECT 1 FROM exercises);
--> statement-breakpoint
UPDATE `equipment_profile` SET `kind` = 'library', `note` = 'Bodyweight moves are excluded by default (see exclusions), not by status.', `area` = NULL, `updated_at` = strftime('%Y-%m-%dT%H:%M:%fZ', 'now') WHERE `equipment` = 'body only' AND EXISTS (SELECT 1 FROM exercises);
--> statement-breakpoint
UPDATE `equipment_profile` SET `kind` = 'machine', `note` = 'Seated, selectorized.', `area` = 'Life Fitness', `updated_at` = strftime('%Y-%m-%dT%H:%M:%fZ', 'now') WHERE `equipment` = 'low row' AND EXISTS (SELECT 1 FROM exercises);
--> statement-breakpoint
UPDATE `equipment_profile` SET `kind` = 'machine', `note` = 'Selectorized.', `area` = 'Life Fitness', `updated_at` = strftime('%Y-%m-%dT%H:%M:%fZ', 'now') WHERE `equipment` = 'lat pulldown' AND EXISTS (SELECT 1 FROM exercises);
--> statement-breakpoint
UPDATE `equipment_profile` SET `kind` = 'machine', `note` = 'Dual weight stacks.', `area` = 'Life Fitness', `updated_at` = strftime('%Y-%m-%dT%H:%M:%fZ', 'now') WHERE `equipment` = 'dual pulley pulldown' AND EXISTS (SELECT 1 FROM exercises);
--> statement-breakpoint
UPDATE `equipment_profile` SET `kind` = 'machine', `note` = 'Dual weight stacks.', `area` = 'Life Fitness', `updated_at` = strftime('%Y-%m-%dT%H:%M:%fZ', 'now') WHERE `equipment` = 'dual pulley row' AND EXISTS (SELECT 1 FROM exercises);
--> statement-breakpoint
UPDATE `equipment_profile` SET `kind` = 'machine', `note` = 'Two adjustable pulleys.', `area` = 'Life Fitness', `updated_at` = strftime('%Y-%m-%dT%H:%M:%fZ', 'now') WHERE `equipment` = 'cable crossover' AND EXISTS (SELECT 1 FROM exercises);
--> statement-breakpoint
UPDATE `equipment_profile` SET `kind` = 'machine', `note` = 'Pulley height adjusts; ankle straps for kickbacks and glute work.', `area` = 'Life Fitness', `updated_at` = strftime('%Y-%m-%dT%H:%M:%fZ', 'now') WHERE `equipment` = 'cable (adjustable pulley station)' AND EXISTS (SELECT 1 FROM exercises);
--> statement-breakpoint
UPDATE `equipment_profile` SET `kind` = 'machine', `note` = 'Four weight stacks.', `area` = 'Life Fitness', `updated_at` = strftime('%Y-%m-%dT%H:%M:%fZ', 'now') WHERE `equipment` = 'multi-station cable tower' AND EXISTS (SELECT 1 FROM exercises);
--> statement-breakpoint
UPDATE `equipment_profile` SET `kind` = 'machine', `note` = 'Assisted pull-up and dip; stands in for hanging work.', `area` = 'Life Fitness', `updated_at` = strftime('%Y-%m-%dT%H:%M:%fZ', 'now') WHERE `equipment` = 'assist dip / chin' AND EXISTS (SELECT 1 FROM exercises);
--> statement-breakpoint
UPDATE `equipment_profile` SET `kind` = 'machine', `note` = 'Calf press on the same machine.', `area` = 'Life Fitness', `updated_at` = strftime('%Y-%m-%dT%H:%M:%fZ', 'now') WHERE `equipment` = 'linear leg press' AND EXISTS (SELECT 1 FROM exercises);
--> statement-breakpoint
UPDATE `equipment_profile` SET `kind` = 'machine', `note` = 'Guided bar; a bench in it covers most barbell presses.', `area` = 'Life Fitness', `updated_at` = strftime('%Y-%m-%dT%H:%M:%fZ', 'now') WHERE `equipment` = 'smith machine' AND EXISTS (SELECT 1 FROM exercises);
--> statement-breakpoint
UPDATE `equipment_profile` SET `kind` = 'machine', `note` = 'One machine, both directions.', `area` = 'Life Fitness', `updated_at` = strftime('%Y-%m-%dT%H:%M:%fZ', 'now') WHERE `equipment` = 'hip abduction / adduction' AND EXISTS (SELECT 1 FROM exercises);
--> statement-breakpoint
UPDATE `equipment_profile` SET `kind` = 'machine', `note` = 'Plate-loaded.', `area` = 'Hammer Strength', `updated_at` = strftime('%Y-%m-%dT%H:%M:%fZ', 'now') WHERE `equipment` = 'abdominal crunch' AND EXISTS (SELECT 1 FROM exercises);
--> statement-breakpoint
UPDATE `equipment_profile` SET `kind` = 'machine', `note` = 'Plate-loaded; covers iso and high rows.', `area` = 'Hammer Strength', `updated_at` = strftime('%Y-%m-%dT%H:%M:%fZ', 'now') WHERE `equipment` = 'iso-lateral row' AND EXISTS (SELECT 1 FROM exercises);
--> statement-breakpoint
UPDATE `equipment_profile` SET `kind` = 'machine', `note` = 'Plate-loaded.', `area` = 'Hammer Strength', `updated_at` = strftime('%Y-%m-%dT%H:%M:%fZ', 'now') WHERE `equipment` = 'iso-lateral shoulder press' AND EXISTS (SELECT 1 FROM exercises);
--> statement-breakpoint
UPDATE `equipment_profile` SET `kind` = 'machine', `note` = 'Plate-loaded.', `area` = 'Hammer Strength', `updated_at` = strftime('%Y-%m-%dT%H:%M:%fZ', 'now') WHERE `equipment` = 'iso-lateral horizontal bench press' AND EXISTS (SELECT 1 FROM exercises);
--> statement-breakpoint
UPDATE `equipment_profile` SET `kind` = 'machine', `note` = 'Plate-loaded.', `area` = 'Hammer Strength', `updated_at` = strftime('%Y-%m-%dT%H:%M:%fZ', 'now') WHERE `equipment` = 'iso-lateral incline press' AND EXISTS (SELECT 1 FROM exercises);
--> statement-breakpoint
UPDATE `equipment_profile` SET `kind` = 'machine', `note` = 'Plate-loaded; stands in for the hack squat.', `area` = 'Hammer Strength', `updated_at` = strftime('%Y-%m-%dT%H:%M:%fZ', 'now') WHERE `equipment` = 'v-squat' AND EXISTS (SELECT 1 FROM exercises);
--> statement-breakpoint
UPDATE `equipment_profile` SET `kind` = 'machine', `note` = 'Plate-loaded preacher station.', `area` = 'Hammer Strength', `updated_at` = strftime('%Y-%m-%dT%H:%M:%fZ', 'now') WHERE `equipment` = 'seated arm curl (preacher)' AND EXISTS (SELECT 1 FROM exercises);
--> statement-breakpoint
UPDATE `equipment_profile` SET `kind` = 'machine', `note` = 'MTS, selectorized.', `area` = 'Hammer Strength', `updated_at` = strftime('%Y-%m-%dT%H:%M:%fZ', 'now') WHERE `equipment` = 'mts biceps curl' AND EXISTS (SELECT 1 FROM exercises);
--> statement-breakpoint
UPDATE `equipment_profile` SET `kind` = 'machine', `note` = 'MTS, selectorized.', `area` = 'Hammer Strength', `updated_at` = strftime('%Y-%m-%dT%H:%M:%fZ', 'now') WHERE `equipment` = 'mts triceps extension' AND EXISTS (SELECT 1 FROM exercises);
--> statement-breakpoint
UPDATE `equipment_profile` SET `kind` = 'machine', `note` = 'MTS, selectorized.', `area` = 'Hammer Strength', `updated_at` = strftime('%Y-%m-%dT%H:%M:%fZ', 'now') WHERE `equipment` = 'mts decline press' AND EXISTS (SELECT 1 FROM exercises);
--> statement-breakpoint
UPDATE `equipment_profile` SET `kind` = 'machine', `note` = 'MTS, selectorized.', `area` = 'Hammer Strength', `updated_at` = strftime('%Y-%m-%dT%H:%M:%fZ', 'now') WHERE `equipment` = 'mts incline press' AND EXISTS (SELECT 1 FROM exercises);
--> statement-breakpoint
UPDATE `equipment_profile` SET `kind` = 'machine', `note` = 'Selectorized.', `area` = 'Hammer Strength', `updated_at` = strftime('%Y-%m-%dT%H:%M:%fZ', 'now') WHERE `equipment` = 'chest press' AND EXISTS (SELECT 1 FROM exercises);
--> statement-breakpoint
UPDATE `equipment_profile` SET `kind` = 'machine', `note` = 'Selectorized; calf press on the footplate.', `area` = 'Hammer Strength', `updated_at` = strftime('%Y-%m-%dT%H:%M:%fZ', 'now') WHERE `equipment` = 'seated leg press' AND EXISTS (SELECT 1 FROM exercises);
--> statement-breakpoint
UPDATE `equipment_profile` SET `kind` = 'machine', `note` = 'Selectorized.', `area` = 'Hammer Strength', `updated_at` = strftime('%Y-%m-%dT%H:%M:%fZ', 'now') WHERE `equipment` = 'seated leg curl' AND EXISTS (SELECT 1 FROM exercises);
--> statement-breakpoint
UPDATE `equipment_profile` SET `kind` = 'machine', `note` = 'Selectorized.', `area` = 'Hammer Strength', `updated_at` = strftime('%Y-%m-%dT%H:%M:%fZ', 'now') WHERE `equipment` = 'lying leg curl' AND EXISTS (SELECT 1 FROM exercises);
--> statement-breakpoint
UPDATE `equipment_profile` SET `kind` = 'machine', `note` = 'Selectorized.', `area` = 'Hammer Strength', `updated_at` = strftime('%Y-%m-%dT%H:%M:%fZ', 'now') WHERE `equipment` = 'leg extension' AND EXISTS (SELECT 1 FROM exercises);
--> statement-breakpoint
UPDATE `equipment_profile` SET `kind` = 'machine', `note` = 'Selectorized, standing only (no seated calf machine); shoulder pads take calf-machine shrugs.', `area` = 'Hammer Strength', `updated_at` = strftime('%Y-%m-%dT%H:%M:%fZ', 'now') WHERE `equipment` = 'standing calf raise' AND EXISTS (SELECT 1 FROM exercises);
--> statement-breakpoint
UPDATE `equipment_profile` SET `kind` = 'machine', `note` = 'Plate-loaded; hip extension and glute kickback.', `area` = 'Hammer Strength', `updated_at` = strftime('%Y-%m-%dT%H:%M:%fZ', 'now') WHERE `equipment` = 'hip & glute' AND EXISTS (SELECT 1 FROM exercises);
--> statement-breakpoint
UPDATE `equipment_profile` SET `kind` = 'machine', `note` = 'Pec deck and reverse fly.', `area` = 'Hammer Strength', `updated_at` = strftime('%Y-%m-%dT%H:%M:%fZ', 'now') WHERE `equipment` = 'pectoral fly / rear deltoid' AND EXISTS (SELECT 1 FROM exercises);
--> statement-breakpoint
UPDATE `equipment_profile` SET `kind` = 'machine', `note` = 'Selectorized.', `area` = 'Hammer Strength', `updated_at` = strftime('%Y-%m-%dT%H:%M:%fZ', 'now') WHERE `equipment` = 'shoulder press (selectorized)' AND EXISTS (SELECT 1 FROM exercises);
--> statement-breakpoint
UPDATE `equipment_profile` SET `kind` = 'machine', `note` = 'Olympic bars and plates; deadlift platform.', `area` = 'Racks & rigs', `updated_at` = strftime('%Y-%m-%dT%H:%M:%fZ', 'now') WHERE `equipment` = 'squat rack / power rack (with platform)' AND EXISTS (SELECT 1 FROM exercises);
--> statement-breakpoint
UPDATE `equipment_profile` SET `kind` = 'machine', `note` = 'Multi-grip pull-up bar.', `area` = 'Racks & rigs', `updated_at` = strftime('%Y-%m-%dT%H:%M:%fZ', 'now') WHERE `equipment` = 'half rack' AND EXISTS (SELECT 1 FROM exercises);
--> statement-breakpoint
UPDATE `equipment_profile` SET `kind` = 'machine', `note` = NULL, `area` = 'Racks & rigs', `updated_at` = strftime('%Y-%m-%dT%H:%M:%fZ', 'now') WHERE `equipment` = 'power rack (functional area)' AND EXISTS (SELECT 1 FROM exercises);
--> statement-breakpoint
UPDATE `equipment_profile` SET `kind` = 'machine', `note` = 'Kettlebells and medicine balls stored here.', `area` = 'Racks & rigs', `updated_at` = strftime('%Y-%m-%dT%H:%M:%fZ', 'now') WHERE `equipment` = 'functional training rig' AND EXISTS (SELECT 1 FROM exercises);
--> statement-breakpoint
UPDATE `equipment_profile` SET `kind` = 'machine', `note` = 'Life Fitness functional cable station.', `area` = 'Racks & rigs', `updated_at` = strftime('%Y-%m-%dT%H:%M:%fZ', 'now') WHERE `equipment` = 'synergy360' AND EXISTS (SELECT 1 FROM exercises);
--> statement-breakpoint
UPDATE `equipment_profile` SET `kind` = 'machine', `note` = 'Hammer Strength, 2.5–75+ lb.', `area` = 'Free weights', `updated_at` = strftime('%Y-%m-%dT%H:%M:%fZ', 'now') WHERE `equipment` = 'dumbbell rack' AND EXISTS (SELECT 1 FROM exercises);
--> statement-breakpoint
UPDATE `equipment_profile` SET `kind` = 'machine', `note` = 'Hammer Strength, 20–110 lb.', `area` = 'Free weights', `updated_at` = strftime('%Y-%m-%dT%H:%M:%fZ', 'now') WHERE `equipment` = 'fixed ez curl bar rack' AND EXISTS (SELECT 1 FROM exercises);
--> statement-breakpoint
UPDATE `equipment_profile` SET `kind` = 'machine', `note` = 'Life Fitness.', `area` = 'Free weights', `updated_at` = strftime('%Y-%m-%dT%H:%M:%fZ', 'now') WHERE `equipment` = 'fixed straight barbell rack' AND EXISTS (SELECT 1 FROM exercises);
--> statement-breakpoint
UPDATE `equipment_profile` SET `kind` = 'machine', `note` = 'Flat, incline and decline (not on Aaron''s list; assumed with the racks).', `area` = 'Free weights', `updated_at` = strftime('%Y-%m-%dT%H:%M:%fZ', 'now') WHERE `equipment` = 'adjustable bench' AND EXISTS (SELECT 1 FROM exercises);
--> statement-breakpoint
UPDATE `equipment_profile` SET `kind` = 'machine', `note` = 'Self-powered, no motor.', `area` = 'Cardio', `updated_at` = strftime('%Y-%m-%dT%H:%M:%fZ', 'now') WHERE `equipment` = 'curved manual treadmill' AND EXISTS (SELECT 1 FROM exercises);
--> statement-breakpoint
UPDATE `equipment_profile` SET `kind` = 'machine', `note` = 'Life Fitness.', `area` = 'Cardio', `updated_at` = strftime('%Y-%m-%dT%H:%M:%fZ', 'now') WHERE `equipment` = 'treadmill' AND EXISTS (SELECT 1 FROM exercises);
--> statement-breakpoint
UPDATE `equipment_profile` SET `kind` = 'machine', `note` = 'Life Fitness PowerMill.', `area` = 'Cardio', `updated_at` = strftime('%Y-%m-%dT%H:%M:%fZ', 'now') WHERE `equipment` = 'stair climber' AND EXISTS (SELECT 1 FROM exercises);
--> statement-breakpoint
UPDATE `equipment_profile` SET `kind` = 'machine', `note` = 'Life Fitness Lifecycle.', `area` = 'Cardio', `updated_at` = strftime('%Y-%m-%dT%H:%M:%fZ', 'now') WHERE `equipment` = 'upright bike' AND EXISTS (SELECT 1 FROM exercises);
--> statement-breakpoint
UPDATE `equipment_profile` SET `kind` = 'machine', `note` = 'Life Fitness.', `area` = 'Cardio', `updated_at` = strftime('%Y-%m-%dT%H:%M:%fZ', 'now') WHERE `equipment` = 'indoor cycling bike' AND EXISTS (SELECT 1 FROM exercises);
--> statement-breakpoint
UPDATE `equipment_profile` SET `kind` = 'machine', `note` = 'Life Fitness Row GX.', `area` = 'Cardio', `updated_at` = strftime('%Y-%m-%dT%H:%M:%fZ', 'now') WHERE `equipment` = 'indoor rower' AND EXISTS (SELECT 1 FROM exercises);
--> statement-breakpoint
UPDATE `equipment_profile` SET `kind` = 'machine', `note` = 'Hammer Strength.', `area` = 'Cardio', `updated_at` = strftime('%Y-%m-%dT%H:%M:%fZ', 'now') WHERE `equipment` = 'sparc arc trainer' AND EXISTS (SELECT 1 FROM exercises);
--> statement-breakpoint
UPDATE `equipment_profile` SET `kind` = 'machine', `note` = 'Hammer Strength fan bike.', `area` = 'Cardio', `updated_at` = strftime('%Y-%m-%dT%H:%M:%fZ', 'now') WHERE `equipment` = 'air bike' AND EXISTS (SELECT 1 FROM exercises);
--> statement-breakpoint
UPDATE `equipment_profile` SET `kind` = 'machine', `note` = 'No T-bar or landmine at your gym; row on the cables or the iso-lateral row.', `area` = NULL, `status` = 'dont_have', `updated_at` = strftime('%Y-%m-%dT%H:%M:%fZ', 'now') WHERE `equipment` = 't-bar row' AND EXISTS (SELECT 1 FROM exercises);
--> statement-breakpoint
UPDATE `equipment_profile` SET `kind` = 'machine', `note` = 'No glute-ham developer.', `area` = NULL, `status` = 'dont_have', `updated_at` = strftime('%Y-%m-%dT%H:%M:%fZ', 'now') WHERE `equipment` = 'glute ham raise' AND EXISTS (SELECT 1 FROM exercises);
--> statement-breakpoint
UPDATE `equipment_profile` SET `kind` = 'machine', `note` = 'No reverse hyper.', `area` = NULL, `status` = 'dont_have', `updated_at` = strftime('%Y-%m-%dT%H:%M:%fZ', 'now') WHERE `equipment` = 'reverse hyperextension' AND EXISTS (SELECT 1 FROM exercises);
--> statement-breakpoint
UPDATE `equipment_profile` SET `kind` = 'machine', `note` = 'No back-extension bench.', `area` = NULL, `status` = 'dont_have', `updated_at` = strftime('%Y-%m-%dT%H:%M:%fZ', 'now') WHERE `equipment` = 'back extension' AND EXISTS (SELECT 1 FROM exercises);
--> statement-breakpoint
UPDATE `equipment_profile` SET `kind` = 'machine', `note` = 'Squat in the rack or on the V-Squat.', `area` = NULL, `status` = 'dont_have', `updated_at` = strftime('%Y-%m-%dT%H:%M:%fZ', 'now') WHERE `equipment` = 'lying machine squat' AND EXISTS (SELECT 1 FROM exercises);
--> statement-breakpoint
UPDATE `equipment_profile` SET `kind` = 'machine', `note` = 'Seated and lying leg curl only.', `area` = NULL, `status` = 'dont_have', `updated_at` = strftime('%Y-%m-%dT%H:%M:%fZ', 'now') WHERE `equipment` = 'standing leg curl' AND EXISTS (SELECT 1 FROM exercises);
--> statement-breakpoint
UPDATE `equipment_profile` SET `kind` = 'machine', `note` = 'No chair-squat station.', `area` = NULL, `status` = 'dont_have', `updated_at` = strftime('%Y-%m-%dT%H:%M:%fZ', 'now') WHERE `equipment` = 'chair squat' AND EXISTS (SELECT 1 FROM exercises);
--> statement-breakpoint
UPDATE `equipment_profile` SET `kind` = 'machine', `note` = 'Arc trainer and air bike instead.', `area` = NULL, `status` = 'dont_have', `updated_at` = strftime('%Y-%m-%dT%H:%M:%fZ', 'now') WHERE `equipment` = 'elliptical' AND EXISTS (SELECT 1 FROM exercises);
--> statement-breakpoint
DELETE FROM `equipment_profile` WHERE `equipment` IN ('leg press', 'hack squat', 'squat rack', 'seated cable row', 'pec deck', 'chest press machine', 'shoulder press machine', 'hip abductor', 'hip adductor', 'seated calf raise', 'functional trainer', 'preacher curl bench', 'assisted pull-up / dip machine', 'ab crunch machine', 'back extension bench', 'glute kickback machine', 'stationary bike', 'rowing machine') AND EXISTS (SELECT 1 FROM exercises);
--> statement-breakpoint
INSERT OR IGNORE INTO exercise_exclusions (id, exercise_id, reason)
SELECT v.column1, v.column2, v.column3 FROM (VALUES
  ('6438a3ee-ea28-5fbe-81a1-ff0cf942d039', '9a2a7214-2b51-5291-bcd0-c6b94255ddc0', 'Floor sit-up.'),
  ('6f75ce8b-c840-5a9d-9109-ade70c8c2d4e', 'e4933d83-7319-59c3-8863-21c3118c4dfa', 'Mobility and stretching, mostly on the floor; not part of the lifting plan.'),
  ('970e2adc-1981-5cbd-b680-3241794004cc', 'a15583c2-4c60-5108-b090-46f4b44661d2', 'Kneeling roll-out on the floor.'),
  ('9fc60ec5-bc1c-56a7-a7d2-9f3028ffb3c6', 'b2e90958-ad49-5bc2-9a5a-cfd5e8010a9a', 'Mobility and stretching, mostly on the floor; not part of the lifting plan.'),
  ('2172bd59-1e0a-5108-abb1-07c58aa81c64', '85b6c7e2-61d0-5599-bb4c-d4993ec5173e', 'Mobility and stretching, mostly on the floor; not part of the lifting plan.'),
  ('722a34b1-7020-548e-b34e-e27601de9d0f', '5c04bdae-0b66-5ccd-9a6b-ad71b9b0e330', 'Bodyweight exercise; Aaron trains with machines and free weights only (SPEC §2).'),
  ('74f16788-cef6-51ee-9df6-c6b9e20cc522', '65e61c34-8fcf-5baa-acbf-231db81c4b76', 'Mobility and stretching, mostly on the floor; not part of the lifting plan.'),
  ('e0260a14-5de4-57e9-b7f2-d0ae4d6b7d0e', '12546883-6cc1-58a1-9583-20a2a0dfec85', 'Bodyweight exercise; Aaron trains with machines and free weights only (SPEC §2).'),
  ('b5c57b62-c12a-597e-9b8f-2968f884258d', 'c345b6dd-a05a-586c-bfcb-4426c8b3f9b2', 'Jumps, throws and sprint drills: bodyweight or explosive, outside machines and free weights.'),
  ('8e6c59cb-a7ad-5d70-b807-657d92a49bce', '7e1a7512-d33a-50eb-aa25-3d526857c985', 'Performed lying on the floor.'),
  ('0d73537e-2d8a-5b81-8f62-7031bb8a4117', '51b4dc50-a8ac-577f-9756-acf2df5d3ed7', 'Plank-position row on the floor.'),
  ('2b4847aa-4670-5d32-9345-b556437aab85', '79cbcc06-0f93-5b2a-ad9a-e2298896b8df', 'Mobility and stretching, mostly on the floor; not part of the lifting plan.'),
  ('ffb9dbd1-17f2-5110-a417-fd7f68133f09', 'ea338a4d-48f3-51cb-bce5-060af19368ad', 'Mobility and stretching, mostly on the floor; not part of the lifting plan.'),
  ('0b85011d-216e-5945-a0d1-4f8f6be91c86', '02d963ea-5900-5bce-8231-0f2e6edd342f', 'Mobility and stretching, mostly on the floor; not part of the lifting plan.'),
  ('dc4e5cc7-e259-57b9-ba4f-d3bfeba29f38', '76ac1776-d93d-5042-8461-12cbcd54c89e', 'Mobility and stretching, mostly on the floor; not part of the lifting plan.'),
  ('45f9f873-61fe-5f6c-b7d3-397a8ec5b151', '4b108984-4d49-5472-a1cb-937aa42bae34', 'Strongman implements (stones, yokes, tyres, logs, sleds) are not at your gym.'),
  ('bb91b8c8-6ac6-52ab-b7ca-8d36841d367f', '3e1b0633-231b-5642-8849-c1c50f89f8bc', 'Strongman implements (stones, yokes, tyres, logs, sleds) are not at your gym.'),
  ('198b5f0e-5077-56a8-81f3-c9f0818ccd2f', '0dbe30a7-c284-5eea-8538-cb2f0d10c845', 'Strongman implements (stones, yokes, tyres, logs, sleds) are not at your gym.'),
  ('41fb98f4-e643-5ccb-9ac6-eb09c9e79cc6', '7394265d-31ef-5104-a4ee-396b9c899df8', 'Strongman implements (stones, yokes, tyres, logs, sleds) are not at your gym.'),
  ('f3a8a7e8-8f6c-5b44-bd5b-937769caadcc', '1be7d933-546f-5904-9ff3-e7f28e25d236', 'Jumps, throws and sprint drills: bodyweight or explosive, outside machines and free weights.'),
  ('3b20ef11-dd0e-5ce6-9ff1-acf9964aedd7', 'a78600e8-8409-5d48-a6ce-2d59c3a6fddf', 'No balance board at your gym.'),
  ('3d6c9ca6-d743-570c-bfdf-a85214a60089', '5eb748f4-49c3-5a51-877d-3dadc8a4686b', 'Leg curl lying on the floor, feet on a ball.'),
  ('c9d293ea-dd46-57b7-9864-17e1984cda65', 'eb711ff3-599c-5093-97c1-d4cc84f884d5', 'Bodyweight hang or dip; use the assisted pull-up/dip machine or lat pulldown instead.'),
  ('a9aeaac7-8d7f-587d-b5b2-34fe3302de37', 'b53e3e4c-dc12-5b33-adf2-6141a0826bdf', 'Resistance bands are not at your gym.'),
  ('f20026de-ba0b-58ba-b0f2-6b25c4f55b67', '6253187b-be4c-5fb6-a56d-7864191bae89', 'Resistance bands are not at your gym.'),
  ('0b8640d7-cef6-5938-b6a4-e6c45a7fc847', 'a1aa2412-44e3-53e9-8393-bc1d3504a341', 'Resistance bands are not at your gym.'),
  ('059f9df8-b73e-5700-a85f-454de2e7197b', '2522be85-c9c2-50de-b77a-a50344a54320', 'Resistance bands are not at your gym.'),
  ('9701c365-defc-5209-9a11-271202436507', 'a269418d-5444-506e-8719-b98865f26084', 'Resistance bands are not at your gym.'),
  ('5ad64201-feb9-5f3a-aeed-4cc9af39cfa7', 'bdc0c6e1-9382-56bc-903d-9aae8519fca8', 'Kneeling roll-out on the floor.'),
  ('82fbcc98-5d9b-5680-aac1-ad8840ba6a6d', '982c13c5-4d68-5f8b-ba5a-b747d4f3b6c4', 'Kneeling roll-out on the floor.'),
  ('6a0e5eb3-ccd4-5e35-9a7b-ff4268c3d49c', 'eb6bc414-fe59-5c80-966c-f107750386ca', 'Glute or hip bridge on the floor.'),
  ('3c56d428-6e8a-5ee4-8a85-4b1185780e11', 'a360d730-0cda-5c18-886c-0732426896d2', 'Lunges are excluded by default (SPEC §2).'),
  ('b578a359-4ff0-547f-9ddb-ed854efdb3ba', 'e3b4d461-f9f9-512b-87a6-ecc1bc43f71e', 'Kneeling roll-out on the floor.'),
  ('27bf8fa9-a2d5-5dc4-aae1-2119da040e60', '44b434b2-ddb9-5232-9b12-76d039566234', 'Lunges are excluded by default (SPEC §2).'),
  ('d844c7d4-6686-5c4d-ab0d-abf7b2e2ad1a', '213f5d83-0932-5ff4-ad19-1f2ba9ebe6d8', 'No battling ropes at your gym.'),
  ('adfdacb2-b5be-59e5-95d5-d88847c090c8', '9b9ef8e5-9eda-51b1-aa33-1caeca27aa8f', 'Strongman implements (stones, yokes, tyres, logs, sleds) are not at your gym.'),
  ('2d328aa9-f049-5fb6-a14e-a3a440017e18', '9deb1ca8-94c2-55ff-936d-5183f61d263a', 'Mobility and stretching, mostly on the floor; not part of the lifting plan.'),
  ('bcd2e81c-51a3-59eb-ade4-103a1a4224a5', 'a8a360dc-d612-527f-bdab-1010de5c7a5f', 'Bodyweight hang or dip; use the assisted pull-up/dip machine or lat pulldown instead.'),
  ('51de989d-d13b-55b5-9a93-7df245bde9c2', '5f38def0-6a81-5125-bc9e-f56fa9f8e9f7', 'Jumps, throws and sprint drills: bodyweight or explosive, outside machines and free weights.'),
  ('b1ad7fe5-15c2-5b88-81b6-d1dd55921dfd', '3450ae19-57d6-51b1-99f0-4f9a34ebf01a', 'No chains at your gym; the racks and plates cover the same lifts.'),
  ('f39be58a-6a9a-5c45-85ba-3dd38dcdeccf', 'a0c04796-350b-527b-ac23-9064b3262129', 'Jumps, throws and sprint drills: bodyweight or explosive, outside machines and free weights.'),
  ('99484bf7-7fcf-5eca-8980-3412aaf39ce5', '672da93e-afad-5f4c-a89f-7dcc045c2344', 'Bodyweight exercise; Aaron trains with machines and free weights only (SPEC §2).'),
  ('df9fa92c-3a56-5270-8e72-f09286df1dc0', 'eb2e2cbf-af95-55b3-99c1-5443c1aff1e5', 'Bodyweight exercise; Aaron trains with machines and free weights only (SPEC §2).'),
  ('871c2d7a-61e7-5240-a4b3-129eec300908', 'fd8e80ad-672e-564b-9cd2-588c6e3f8915', 'Bodyweight exercise; Aaron trains with machines and free weights only (SPEC §2).'),
  ('a21406b4-4721-5b26-a70a-7cbcc1f9eb15', '8f1df5f1-0fb2-5463-b545-a384a17b8866', 'Bodyweight fly from a push-up position on the floor.'),
  ('99f06aab-25a8-5921-aa19-a441cd4f42b3', 'acee257c-af52-53fe-9db0-686d203ae12e', 'Bodyweight move (SPEC §2).'),
  ('e1557e01-25e2-5c11-b570-719630b67963', 'ec89ffe3-2fd4-5239-8149-15e3cf26d166', 'Bodyweight move (SPEC §2).'),
  ('0d605ce3-7fd0-5e8b-be26-3ea4221dee52', '76331cbf-be6d-5073-bdca-7bdf195f9724', 'Lunges are excluded by default (SPEC §2).'),
  ('3b8cec02-d34d-5cfd-80ea-50cda72a4a96', '2f7fcc97-a0c9-53d1-8bc2-320b273c3df8', 'Bodyweight exercise; Aaron trains with machines and free weights only (SPEC §2).'),
  ('a62ed222-a0f0-5d1b-8afa-42dbe651d811', '55ca8984-8388-57d9-a015-768b17e06f24', 'Jumps, throws and sprint drills: bodyweight or explosive, outside machines and free weights.')
) AS v JOIN exercises e ON e.id = v.column2;
--> statement-breakpoint
INSERT OR IGNORE INTO exercise_exclusions (id, exercise_id, reason)
SELECT v.column1, v.column2, v.column3 FROM (VALUES
  ('19a8c3d3-09c9-57ca-be32-833d4792ab1a', '599d022b-1559-5d50-81c2-fa967043cf1d', 'Jumps, throws and sprint drills: bodyweight or explosive, outside machines and free weights.'),
  ('74f1db2b-0884-5d2a-9beb-42c9f55d7966', '933d9d33-32b6-57cb-894f-3b642a966c6b', 'No chains at your gym; the racks and plates cover the same lifts.'),
  ('2c18d7a2-08b7-5401-9fa7-c1d8260cff0a', 'd579895a-9613-5089-833d-0ce147176956', 'Mobility and stretching, mostly on the floor; not part of the lifting plan.'),
  ('06f9c54f-f688-5479-9ad1-7984e52f165a', '651f75d5-f7d2-505d-a31e-170c804a5fc9', 'Bodyweight exercise; Aaron trains with machines and free weights only (SPEC §2).'),
  ('765d017c-8768-580a-89d6-41a4cf76b561', 'd0549382-7699-55bb-a3ee-890470a7dfc9', 'Glute or hip bridge on the floor.'),
  ('ce2d2685-86f6-523b-b465-407cf5ee61b4', 'fdae37c5-2de8-514d-959a-252350a0250d', 'Reverse crunch lying on the floor (cable too).'),
  ('8e8f40fb-f4f9-530c-a16d-656a0c69c89c', '4c58b160-72b2-547b-a227-a6085ec420e8', 'Mobility and stretching, mostly on the floor; not part of the lifting plan.'),
  ('f9a9de6a-b454-5b25-85e5-b4a4970b97ce', '5ec30fd6-c918-57b8-89d5-38d09f57828e', 'Mobility and stretching, mostly on the floor; not part of the lifting plan.'),
  ('ab301345-283b-5fc8-b1e4-a14976d397cd', '996d7f8d-52be-5c18-a31d-eb084502f0e6', 'Mobility and stretching, mostly on the floor; not part of the lifting plan.'),
  ('2da14751-e732-51f5-a25e-4cf8cfc7aed1', '05dcd733-3b5e-5803-b765-b9725d974059', 'Strongman implements (stones, yokes, tyres, logs, sleds) are not at your gym.'),
  ('4322877e-85d6-527d-b3da-a6ba75993821', '992188a7-ba71-5e7d-a4a9-6120813acfc3', 'Jumps, throws and sprint drills: bodyweight or explosive, outside machines and free weights.'),
  ('76ff2d6e-f6b0-59ae-9cb6-eb43e0087d1e', '1ff8c04f-8fbc-5c7e-a434-91961bdc7535', 'Mobility and stretching, mostly on the floor; not part of the lifting plan.'),
  ('7185d258-a942-57a3-8cad-c82c851b2405', '3cfa123f-8784-5f48-93b0-a207ae205962', 'Jumps, throws and sprint drills: bodyweight or explosive, outside machines and free weights.'),
  ('965ab6ca-0133-5069-a30c-d01e8129b9d4', '454c493d-a5fb-584a-8eb0-d4bef8a84bd6', 'No chains at your gym; the racks and plates cover the same lifts.'),
  ('2e9a9862-df04-5f83-91b1-5936e526bb07', 'aa9fddfa-12f1-523d-8ac8-7f47e7a2827c', 'No chains at your gym; the racks and plates cover the same lifts.'),
  ('68afff33-88af-5a6c-b84a-829cfca47042', '93895e15-f922-5f64-ab97-91b40d8e9a67', 'Mobility and stretching, mostly on the floor; not part of the lifting plan.'),
  ('69291bd4-e936-5bb2-a649-b257fc9f0d4b', 'f7d5d220-93e0-5a2b-b7bb-f73384924bca', 'Mobility and stretching, mostly on the floor; not part of the lifting plan.'),
  ('b85dbf11-7d3e-52fe-9806-0fa52f5da1f8', '8bc3c711-0229-5bf7-9a00-6366aba13c7f', 'Mobility and stretching, mostly on the floor; not part of the lifting plan.'),
  ('ce3a8148-3dff-53ce-a775-369cdc386fac', '54df6f6e-f3b9-5324-b759-4e5da0df96ad', 'Mobility and stretching, mostly on the floor; not part of the lifting plan.'),
  ('a4a444d8-3114-51e1-ae2d-f59cae888db0', 'a24bf643-fef6-5d41-8a5c-f3dde0295ec7', 'Jumps, throws and sprint drills: bodyweight or explosive, outside machines and free weights.'),
  ('a4d89b4b-8a56-509a-9070-0038fb3db0d1', '445983ff-6c84-5758-948b-2789b0c29390', 'Jumps, throws and sprint drills: bodyweight or explosive, outside machines and free weights.'),
  ('403cc5f1-7ad6-53f8-8457-cacc06c88091', 'cfcadcc5-793e-553d-b964-e8a500a51cef', 'Jumps, throws and sprint drills: bodyweight or explosive, outside machines and free weights.'),
  ('16e264ff-06a7-533b-9ce2-d9dce1d8f48b', 'b965d6c3-ef86-5d60-aa01-20b908cd969f', 'Jumps, throws and sprint drills: bodyweight or explosive, outside machines and free weights.'),
  ('3a285b2f-3069-5adc-96fa-9e6eb65f8e70', '27287b42-c98e-51b2-bb0d-90cbe5c65a80', 'Mobility and stretching, mostly on the floor; not part of the lifting plan.'),
  ('bfb8a393-cc74-5889-805b-4c96d09ab654', 'e0ee718a-d546-5537-aec0-376f6b54b3c0', 'Mobility and stretching, mostly on the floor; not part of the lifting plan.'),
  ('01d6fd81-1e7b-5891-8f71-9c71d3783abc', 'e6ec151e-3cc0-5049-9cfc-daad0288261b', 'Bodyweight hang or dip; use the assisted pull-up/dip machine or lat pulldown instead.'),
  ('de072beb-3888-5e13-938f-363c669167da', '752535c4-2e1e-5d49-9db6-1cf8545d81e9', 'Bodyweight hang or dip; use the assisted pull-up/dip machine or lat pulldown instead.'),
  ('b533f4fe-17bc-5894-8033-59b34da63b34', '101ba8d8-020e-5cd8-b4b3-aaba7642fa60', 'Strongman implements (stones, yokes, tyres, logs, sleds) are not at your gym.'),
  ('45be10fd-a525-5162-a11d-3f9c61abfbfb', 'fd34cb6a-cc88-5be3-8c19-48083b88a5f2', 'Bodyweight push-up.'),
  ('cec518b8-3294-5653-bc66-09c46a4adaa5', '57587e8c-8b48-5b68-9fc9-1d90547faae6', 'Resistance bands are not at your gym.'),
  ('135fbd44-de37-5c1c-81bf-62b7b7b07840', '93e708bc-34f0-504e-9c78-ee50dcec99b8', 'Bodyweight push-up.'),
  ('77fee9bb-e22d-5397-ad27-0e3a567b2dd3', 'dad7fe5f-1aac-5302-9d34-82ac73597ba3', 'Bodyweight exercise; Aaron trains with machines and free weights only (SPEC §2).'),
  ('38db9ce5-144d-5317-b040-63695d6c55e2', '347e01fb-e60f-5f1d-b902-b7e724a5bac5', 'Strongman implements (stones, yokes, tyres, logs, sleds) are not at your gym.'),
  ('6f89e582-12d9-52d6-8911-5490f377237c', '534cef67-851e-58f6-b2cf-568f953aeeea', 'Floor crunch; cable and machine crunches stay allowed.'),
  ('95f99353-b220-532c-b40f-81b6c0c57b67', 'cfd295bd-3adb-59d4-a21b-1c9888098e6b', 'Lunges are excluded by default (SPEC §2).'),
  ('ba55d139-1e7f-501b-a8b6-537f22cd8305', '239be8c3-6b5c-5288-b9fa-2265bf855f95', 'Strongman implements (stones, yokes, tyres, logs, sleds) are not at your gym.'),
  ('96b29692-43bc-5ec5-9200-c5b86e9905d1', '23853600-dee5-512d-ba27-77f5ac6e4662', 'Floor crunch; cable and machine crunches stay allowed.'),
  ('00510a27-25ce-544b-9ea5-2e0efbb48c37', '6130d3b1-d6f9-5879-bad8-66327ab401c5', 'Floor crunch; cable and machine crunches stay allowed.'),
  ('cbf9bfdc-c0df-52b1-8258-3a006e270f3e', 'a98c834c-54fc-5441-915b-67bb1c584f88', 'Floor crunch; cable and machine crunches stay allowed.'),
  ('1505bd01-4c5c-51e1-bcce-31aed05c7575', '7de91c9c-285a-58e4-9f66-db9c02dce31e', 'Mobility and stretching, mostly on the floor; not part of the lifting plan.'),
  ('5ae520e5-ae1c-5eaf-a8cb-74dd20a3fa39', 'cdae3231-7e67-5090-9ffb-76a33d9232e3', 'Bodyweight exercise; Aaron trains with machines and free weights only (SPEC §2).'),
  ('6288001e-b633-526c-b1b2-d5e7ce9f3e8d', '0ab211d8-f16e-5b1b-8dca-17203c99c6ab', 'No chains at your gym; the racks and plates cover the same lifts.'),
  ('152af6d4-2e58-5bc0-ad96-369daae459d4', '4102309d-ca4d-59c8-810a-2402e4d02c6f', 'Floor crunch; cable and machine crunches stay allowed.'),
  ('dc35ec94-9741-5ecf-a3ec-edd77a4d25ec', '5edfc733-f5ca-58ac-80d3-67428f75fbf4', 'Floor crunch; cable and machine crunches stay allowed.'),
  ('e61972ed-4ae4-5ecf-bb23-50515c5e32ab', '1d09bfdc-b010-5e56-94bd-cc4014e2db91', 'Bodyweight push-up.'),
  ('663070fd-416c-53a1-ae91-b7457ac529c8', 'f02d8b05-ca71-5a0c-8153-1d40f7247910', 'Floor crunch; cable and machine crunches stay allowed.'),
  ('a0a74d56-e392-5410-b65b-c4fb623a26bb', '35cd20f2-de88-53b5-a8b1-969e30ecb2bf', 'Jumps, throws and sprint drills: bodyweight or explosive, outside machines and free weights.'),
  ('251c4060-e0bb-558a-8359-08bb645ed2df', '45b08bd4-8857-5ac3-9902-98fb372004d4', 'Bodyweight hang or dip; use the assisted pull-up/dip machine or lat pulldown instead.'),
  ('c9190f9d-8507-536f-9374-019ff3593ebb', 'b6b5596a-399b-52a4-90f8-a01f0c36c5a5', 'Bodyweight hang or dip; use the assisted pull-up/dip machine or lat pulldown instead.'),
  ('808a2663-2c0c-570d-a4ec-017d6d9874da', '6c3c9f8b-666f-5bbe-9bd8-64f9aa844002', 'No donkey calf station; use the standing calf raise.')
) AS v JOIN exercises e ON e.id = v.column2;
--> statement-breakpoint
INSERT OR IGNORE INTO exercise_exclusions (id, exercise_id, reason)
SELECT v.column1, v.column2, v.column3 FROM (VALUES
  ('710a418c-cd0f-58f1-b186-1e5453e7807a', '3cf8f640-49db-5a89-970a-19110d397763', 'Jumps, throws and sprint drills: bodyweight or explosive, outside machines and free weights.'),
  ('6b6473e6-e906-5e40-b7ef-c6836f288cc7', '6deb295c-9c68-58ba-9f38-f4333e2e211a', 'Jumps, throws and sprint drills: bodyweight or explosive, outside machines and free weights.'),
  ('53da8c7e-55a5-5319-be4e-4937a887d8b8', 'f5feede1-fed1-59b3-b97d-f7bb9189beba', 'Performed lying on the floor.'),
  ('288570d5-9354-5a5b-98b5-632b737db211', '8c8c9838-a7e6-56b2-b909-6fc5332e8669', 'Lunges are excluded by default (SPEC §2).'),
  ('0749d330-3cc2-5510-93fe-e7b3fbf280c4', 'd7d06b60-c74d-5273-9aa7-f605c9a11b68', 'Lunges are excluded by default (SPEC §2).'),
  ('2bf5427b-7c7c-5806-8ed1-11d8666a67a6', 'c069cc59-d8b4-5a1f-9570-ccb0ec4645df', 'Jumps, throws and sprint drills: bodyweight or explosive, outside machines and free weights.'),
  ('07971c88-9ff8-530a-a956-95dae46560f0', 'c7e1d45e-2c77-5406-8871-3d7b5c4c4416', 'Mobility and stretching, mostly on the floor; not part of the lifting plan.'),
  ('0d5dd135-557d-53b7-89e0-836e8a67a4eb', '7c5a1638-b540-5f40-9bcd-9fbcbe9759d4', 'Mobility and stretching, mostly on the floor; not part of the lifting plan.'),
  ('c721d638-2463-54f4-9540-216c2f88cc62', '9ab7e831-8142-50d3-8461-a1de7f1f0bd3', 'Mobility and stretching, mostly on the floor; not part of the lifting plan.'),
  ('ba7e43c9-dd83-5e92-86f8-a3e266bc069a', '3f9599ec-f9a1-5f04-b026-4f5f1749869e', 'Bodyweight exercise; Aaron trains with machines and free weights only (SPEC §2).'),
  ('2cce152b-c70c-5cb3-bfef-08ba68e24dd4', '587b73a9-36d1-585a-b5a8-39b068f02334', 'Mobility and stretching, mostly on the floor; not part of the lifting plan.'),
  ('758713ab-6568-5153-8b94-9e6642720738', 'f19c4505-8ea8-5fac-a1b5-2dbecf955f1b', 'Lunges are excluded by default (SPEC §2).'),
  ('4a1332e1-1fd5-5c85-9d87-8736aef7fb8c', 'aaf61bdc-c909-50db-b339-f5afb1884d7b', 'Floor crunch; cable and machine crunches stay allowed.'),
  ('a39261da-0bfd-5682-8899-e5e75cf915dd', '2ae134ef-7748-5d00-b93b-5cb5e8ebc548', 'Plank on a ball, hands on the floor.'),
  ('240898f3-49c7-566e-af93-5cecaa54057f', '4780f70e-7ebc-592d-a52f-18fd26a15b09', 'Performed lying on the floor.'),
  ('94fb99d9-7deb-5f6b-8896-33f721b9d2d2', '28928a5e-68d6-5884-8cfc-5e0a287a99fb', 'Resistance bands are not at your gym.'),
  ('23a351da-6951-51b7-aec0-c92114bd129d', '57468614-7672-5351-94e1-34d341772758', 'Strongman implements (stones, yokes, tyres, logs, sleds) are not at your gym.'),
  ('d717f0c9-3abb-57ab-a337-db154a150895', 'fcd1cd88-74fc-5a73-8d8e-0092d9d13e63', 'Jumps, throws and sprint drills: bodyweight or explosive, outside machines and free weights.'),
  ('e06629f4-8ca3-5faa-b3bd-d58dfde822d8', 'a81d7978-b069-58eb-bb3d-d79cd7061d4c', 'Bodyweight exercise; Aaron trains with machines and free weights only (SPEC §2).'),
  ('20d5e6ca-3a0c-576f-b6c7-5c2d38e0792c', '3cad44cb-d379-5ba1-a5f6-411a5b5fda42', 'Bodyweight exercise; Aaron trains with machines and free weights only (SPEC §2).'),
  ('b924cccb-b0cb-5e3a-b2f8-7c8bfdc9c9b7', 'd974dba5-9951-59d0-8c36-6ba497c21172', 'Performed lying on the floor.'),
  ('619bb18d-a8c4-550f-bfc4-eeae64562203', '59c7dc18-7407-54b4-9714-9470120f79dc', 'Performed lying on the floor.'),
  ('67cfffab-e187-5520-9381-3c3e5f80dfd2', '62cb053e-493c-5a97-b494-95edca2e5c54', 'Performed lying on the floor.'),
  ('9ecff4d8-e369-5cfe-b152-f2c5a53e1eca', '5847d1d5-a305-5136-ac8d-ee619d41ef86', 'Floor core move (flutter kick).'),
  ('b0553904-2307-5aee-bc69-0c4ba3e53e53', 'cdda3422-90f5-517a-b5a7-ed9eeb2cd205', 'Mobility and stretching, mostly on the floor; not part of the lifting plan.'),
  ('d454f321-5519-5add-9e68-6b9c04b6eb69', '76cc2527-6667-529e-8289-2e4d0581cba6', 'Strongman implements (stones, yokes, tyres, logs, sleds) are not at your gym.'),
  ('e128644c-6e95-5c27-886b-6c7535f40e28', '9e24f655-fb40-50a6-986a-d9adafab9bb1', 'Bodyweight exercise; Aaron trains with machines and free weights only (SPEC §2).'),
  ('a2dbbe71-b136-526d-ac61-63240f85f48f', '80dec500-8615-5283-aefc-80aa088886ec', 'Mobility and stretching, mostly on the floor; not part of the lifting plan.'),
  ('3cf98e42-a4e8-53c2-b1ee-5afaa256bd48', '8918f537-8588-5b41-89e2-33919a991e08', 'Floor sit-up.'),
  ('c73bf2c4-1875-5055-b0af-58391ca52bf9', '9f5e0332-f912-5c13-9a00-1a30921f80cd', 'Jumps, throws and sprint drills: bodyweight or explosive, outside machines and free weights.'),
  ('abec2813-4aad-5678-8b6b-b517ac9f7889', '700f2de5-3824-585e-876c-328fe3f065c4', 'Jumps, throws and sprint drills: bodyweight or explosive, outside machines and free weights.'),
  ('b358840a-594b-52cd-bed8-e7e52eef9d3a', '12bb535f-549e-56b5-aa1f-c36e05bf3f29', 'Mobility and stretching, mostly on the floor; not part of the lifting plan.'),
  ('73617520-569f-5cff-8994-37cfbb356d69', 'c9f5d69e-254e-5059-9305-fa81cd738dd9', 'Bodyweight hang or dip; use the assisted pull-up/dip machine or lat pulldown instead.'),
  ('f212a249-55db-5570-be61-c205b3a24cee', '7ff57cab-210f-5c0e-8fa4-c8eb695f2d46', 'Bodyweight exercise; Aaron trains with machines and free weights only (SPEC §2).'),
  ('4ed9e340-eddc-5299-bfbd-f2ad769b8927', 'd66eb8d3-c138-5525-9407-a6787fb93482', 'Floor crunch; cable and machine crunches stay allowed.'),
  ('b99aff91-665c-5c30-be61-9b642702721e', '26ee04c5-bd11-5e7d-809f-9fb473758b04', 'Mobility and stretching, mostly on the floor; not part of the lifting plan.'),
  ('86db4c2a-f33b-56e8-aae4-319aa8b6b8b4', '7684637e-f692-54cb-92b6-9854a03c3dc7', 'Mobility and stretching, mostly on the floor; not part of the lifting plan.'),
  ('77ded2fe-ea7d-5359-b691-6c056ba28f7b', 'c17348c2-7760-5745-97fb-dd5410247bd6', 'Mobility and stretching, mostly on the floor; not part of the lifting plan.'),
  ('40e4fe15-68af-5d23-9982-f3cf5907646b', '66ae4d8a-bac1-5757-a985-fd7e80d55e0d', 'Mobility and stretching, mostly on the floor; not part of the lifting plan.'),
  ('457feaab-7434-5ac0-ae49-fe25c6e448a2', '73d3a842-7e22-5621-a446-a4849fb0e69c', 'Bodyweight push-up.'),
  ('dd496414-537f-58bb-9e52-e5cc3de6f2e2', '1fded52a-2ad9-5daf-acb4-9f5695f4d005', 'Bodyweight exercise; Aaron trains with machines and free weights only (SPEC §2).'),
  ('45cf5719-c5df-5147-a7b0-b7ed55e97f39', '13cd275c-73b5-504d-86fc-a0d0b5ef409a', 'Bodyweight exercise; Aaron trains with machines and free weights only (SPEC §2).'),
  ('671d05b0-0a57-5d3c-8902-42f1d656d6c2', '1e33f272-84ae-5ab4-b5a9-492998137e40', 'Jumps, throws and sprint drills: bodyweight or explosive, outside machines and free weights.'),
  ('8d4ecbd4-a175-57d8-9812-b8778574f149', '7b8af620-50be-5edd-8531-4d708d90a9a1', 'Mobility and stretching, mostly on the floor; not part of the lifting plan.'),
  ('e04bd1d5-82d5-5887-8007-db638522614e', '7cb5b27c-1044-52d2-a79f-bcb22f9a11b4', 'Resistance bands are not at your gym.'),
  ('5ec8c504-104f-5ff6-a7b5-f4d0e2298325', '0c1fc018-d0af-5286-bf14-73151c3987d4', 'Hip lift lying on the floor.'),
  ('f6a24511-828a-5278-990b-dec8ba9459af', 'c9a55c7a-10b1-54e5-a4d9-e900dc1575e4', 'Mobility and stretching, mostly on the floor; not part of the lifting plan.'),
  ('f85245ad-a7f8-5484-a8c7-bb8ff7d761ce', 'acbecda0-3c74-5f63-a4e3-e930450143c1', 'Mobility and stretching, mostly on the floor; not part of the lifting plan.'),
  ('92044411-a66f-558d-9465-b0afffaf3e0b', '6ca25c2a-8033-56d6-aa56-2df1feb6f58b', 'Jumps, throws and sprint drills: bodyweight or explosive, outside machines and free weights.'),
  ('ec7674f9-4672-591e-a1de-efe05b34f006', 'cc427c7d-b0a5-500e-be2e-eb894a366321', 'Bodyweight exercise; Aaron trains with machines and free weights only (SPEC §2).')
) AS v JOIN exercises e ON e.id = v.column2;
--> statement-breakpoint
INSERT OR IGNORE INTO exercise_exclusions (id, exercise_id, reason)
SELECT v.column1, v.column2, v.column3 FROM (VALUES
  ('98f1a8ae-1e7f-55db-8d8f-5c077d8629e2', '0510b834-a789-5ddb-a1e2-543e9c6d6e9b', 'Resistance bands are not at your gym.'),
  ('32b1728d-331f-5082-a8d6-eda3f51bb9c7', 'c4b5230e-357b-5707-ad63-936f8bb410ce', 'Mobility and stretching, mostly on the floor; not part of the lifting plan.'),
  ('bbcde61b-26ae-5a04-9467-7131bf4049b1', 'decf2d89-f01a-58c4-99e3-2e22413f4bdf', 'Mobility and stretching, mostly on the floor; not part of the lifting plan.'),
  ('1e559232-2259-598c-9109-43b4b5348a19', 'e4c5b38d-68d5-550b-a367-0e18014e55ab', 'Bodyweight push-up.'),
  ('a959bb6d-a932-597f-9662-fcfa603ecbe8', 'be115b93-d1b9-50dc-a5e2-d463aaef43f1', 'Bodyweight push-up.'),
  ('749ce426-3c06-51ab-8089-684689bea371', 'fa15af85-45f6-522c-b148-3034f054deef', 'Bodyweight push-up.'),
  ('5ff49086-eaf4-56de-993e-93f56cb9c7cf', 'c640df95-e031-5a7c-9e3e-cb921a07124b', 'Bodyweight push-up.'),
  ('7f11f05c-49a6-5bd8-a936-1826fef9534d', '739fd006-624a-5509-befd-6219357319b7', 'Bodyweight push-up.'),
  ('1ebb3496-a13e-564e-85b0-316eeac083e4', '0eaf4cf3-dbc4-563a-a1fa-0e8a61cb20c5', 'Bodyweight push-up.'),
  ('0e97a223-584e-582b-b938-c324f3f035c9', 'c00ba81b-2f8d-5912-9160-f95ca9aca2eb', 'Mobility and stretching, mostly on the floor; not part of the lifting plan.'),
  ('e9d144ec-75d1-53bd-9198-be344c4ee412', 'c60df794-85bd-536c-8e91-edde7559dc7d', 'Mobility and stretching, mostly on the floor; not part of the lifting plan.'),
  ('8600cb80-dec2-5833-9278-9d1c619050db', '7040a2a5-424a-5cd1-9e82-88a8691c3ced', 'Resistance bands are not at your gym.'),
  ('75ec4291-e873-53c3-b7c1-e2918958f566', '69f80d66-dcce-57fd-9ce7-a66826033788', 'No suspension trainer or straps at your gym.'),
  ('2d1a552e-3380-5651-8554-4fe5c4e2a900', '160bbc42-0581-5bb0-98c9-491eea617538', 'No suspension trainer or straps at your gym.'),
  ('1888e1cd-6103-57a5-b766-d437611a9fc7', 'c01e0809-bdfb-5f2c-8a2b-34a1ea1b8000', 'Mobility and stretching, mostly on the floor; not part of the lifting plan.'),
  ('4c41c155-0ed1-5357-a5e2-cfcd9cb8c831', '4b450244-ead1-5ae9-85c6-eb3311fe6f74', 'Jumps, throws and sprint drills: bodyweight or explosive, outside machines and free weights.'),
  ('72f1e0bb-e7c5-5647-970f-b17cc3d8936a', 'e9c63be6-6ba1-5e6d-af8a-0b8dcee99731', 'Bodyweight exercise; Aaron trains with machines and free weights only (SPEC §2).'),
  ('be175e28-2f01-578a-a1b8-acb2888d3d79', '37c27667-a8f7-54be-b082-4aa4b8b7e9ba', 'Bodyweight exercise; Aaron trains with machines and free weights only (SPEC §2).'),
  ('44a06175-782d-5ad5-a9ae-b1bb1a085280', '2f835867-3060-51ff-951a-1db403bf81e9', 'Bodyweight exercise; Aaron trains with machines and free weights only (SPEC §2).'),
  ('4321aeb0-77f5-5e84-93fa-bd74583ae10f', 'b5edf0ad-9188-577a-8b5b-f687780350c3', 'Floor sit-up.'),
  ('14786d37-e4d2-55fd-9e5f-856219bdca7c', '89405487-e59e-5c40-a299-955a106bb344', 'Floor sit-up.'),
  ('b516342b-f28b-5ff7-9334-2c938e0346d3', '591ced7f-f0d4-5be5-bdce-16c97ce3abf8', 'Strongman implements (stones, yokes, tyres, logs, sleds) are not at your gym.'),
  ('5cf9ae4c-43a5-5866-8b9f-d9422f5db890', 'dd7bd189-97e7-58c9-bf39-408baa43b07b', 'Press seated on the floor.'),
  ('e4d226ab-75cf-5ba9-a44e-bc1f06d509c7', '22e30e12-a94f-54ab-8f17-ce80190fd6c1', 'Lunges are excluded by default (SPEC §2).'),
  ('0978f3cc-5a6f-52a0-b3a5-caf5f4a2dff7', 'e164310a-3831-56f4-9d98-1a2c84b0f721', 'Get-up from lying on the floor.'),
  ('a376e4ca-6977-59e7-a354-cb4e010711fb', '0497dac8-f739-588e-861d-31bf554ea235', 'Bodyweight hang or dip; use the assisted pull-up/dip machine or lat pulldown instead.'),
  ('525f39a9-7479-5c5a-9556-1168197ca607', '4bbabae3-c94a-5f21-bd31-504c520140c8', 'Mobility and stretching, mostly on the floor; not part of the lifting plan.'),
  ('fc3ed106-2214-579a-a51e-e27d2766f01e', '70dca214-dadb-517f-8297-d2cd9eb79742', 'Mobility and stretching, mostly on the floor; not part of the lifting plan.'),
  ('194ac007-b986-5e61-94b5-b93c2119c230', '7fac69ed-8666-5482-808a-2c3aab38fb0d', 'Bodyweight hang or dip; use the assisted pull-up/dip machine or lat pulldown instead.'),
  ('4d90f182-81ef-51e3-a79a-8e6885de05ca', 'aa2e00de-de0e-5091-a5ba-0b6a7531a82c', 'Jumps, throws and sprint drills: bodyweight or explosive, outside machines and free weights.'),
  ('a0222787-cf98-52b9-acd0-c40778609f92', 'b939244c-2415-5250-be9c-4b19972c9e1a', 'Jumps, throws and sprint drills: bodyweight or explosive, outside machines and free weights.'),
  ('a472bee5-c043-5338-aae6-f9f147cb6db6', '7f4722d7-c2d2-54f6-aac2-ade90d3023f6', 'Mobility and stretching, mostly on the floor; not part of the lifting plan.'),
  ('b7f256be-a684-5827-bef2-f53acd5fd4ab', '7e68dc2c-28de-5787-90d9-be47d4297d0e', 'Mobility and stretching, mostly on the floor; not part of the lifting plan.'),
  ('7c27227e-96ff-5b5c-bb53-e9e666da05ed', 'd39f920d-c37d-5aed-bd4b-2a0a2df8b0b6', 'Jump from kneeling on the floor.'),
  ('2d8f2a17-1ef0-5c5d-812f-fb72219c4d3a', 'c734f1bf-1957-5307-a34d-1a2295193cc4', 'Jumps, throws and sprint drills: bodyweight or explosive, outside machines and free weights.'),
  ('9467ba0f-97f9-57f1-ac56-62b4618e35b0', '5a6b12dd-63d0-541f-a8f1-bda04b49fe56', 'Jumps, throws and sprint drills: bodyweight or explosive, outside machines and free weights.'),
  ('39048035-2f53-5f0a-b795-0b949c3e9f6e', '206abb30-7612-5593-b5a0-8c1413e65ef3', 'Jumps, throws and sprint drills: bodyweight or explosive, outside machines and free weights.'),
  ('571d07d6-e8cd-514d-b354-1f55e046b15f', 'ef00aa84-2e6f-5964-aa33-f9c5eea2792c', 'Mobility and stretching, mostly on the floor; not part of the lifting plan.'),
  ('9929f6e5-2a50-5d2b-824e-8aac75ac8b2c', '4ccb66b0-c00f-56ca-a339-70ceb0731b99', 'Performed lying on the floor.'),
  ('560030c1-8761-5094-a9e9-d36e9f931e08', '0361d724-fc94-5ca1-966a-8f8e98f2997d', 'Mobility and stretching, mostly on the floor; not part of the lifting plan.'),
  ('7494773c-8eab-54f7-9a4b-67284040c86e', '9e43ff28-d64d-5129-801f-aec0df7bae6d', 'Bodyweight exercise; Aaron trains with machines and free weights only (SPEC §2).'),
  ('e985d3c1-2e10-5597-9314-d8882b6c8773', '1c5b51ac-9319-5f44-b319-d66ea9b08786', 'Bodyweight exercise; Aaron trains with machines and free weights only (SPEC §2).'),
  ('076d6efe-6d6c-5e6c-8197-41207e3d4ed7', '43ab1547-bf0c-5a4b-bda3-7b0f11d74245', 'Jumps, throws and sprint drills: bodyweight or explosive, outside machines and free weights.'),
  ('ae026039-08ee-5862-8b1e-b5d3b6526d25', 'ee532974-6642-5e58-b57b-65351121191f', 'Jumps, throws and sprint drills: bodyweight or explosive, outside machines and free weights.'),
  ('99301f16-3b31-520f-81d0-c89da698a83c', 'ae1a4cdc-e2c3-5162-bc9a-7760e85e0776', 'Jumps, throws and sprint drills: bodyweight or explosive, outside machines and free weights.'),
  ('f005fc59-3e33-56f9-ad09-59064a99662b', 'c1b887d4-4b97-581a-be35-e6950661317c', 'Strongman implements (stones, yokes, tyres, logs, sleds) are not at your gym.'),
  ('c107011d-d8b6-5801-bfac-c9c434ee4b7f', '7d0c9c68-86d8-5cc0-9cd8-199b3c8fe055', 'Glute or hip bridge on the floor.'),
  ('f90b6d1b-baae-5b12-ae2e-842245ea19d2', '46702db1-cfce-5db4-a9a9-489de78854dd', 'Mobility and stretching, mostly on the floor; not part of the lifting plan.'),
  ('c108d7d4-6117-5b7e-bd6e-acb929e00b35', '8438a525-e052-5ab6-9882-8e828fd3abf2', 'Mobility and stretching, mostly on the floor; not part of the lifting plan.'),
  ('327eedd8-c949-5cb5-a73a-06b5b5f53251', 'f16868c9-40a2-5938-aab8-8f19e1f7749f', 'Mobility and stretching, mostly on the floor; not part of the lifting plan.')
) AS v JOIN exercises e ON e.id = v.column2;
--> statement-breakpoint
INSERT OR IGNORE INTO exercise_exclusions (id, exercise_id, reason)
SELECT v.column1, v.column2, v.column3 FROM (VALUES
  ('7eafa22b-e558-5995-9230-37b7b1050df0', 'edfa26f3-bb37-5ad4-83fd-e2776362effd', 'Lunges are excluded by default (SPEC §2).'),
  ('c8c524fa-0559-5ffe-a9cb-57c04c9f0861', '9cc68ba5-fd9f-5e74-906c-8f2b36a1b96b', 'Lunges are excluded by default (SPEC §2).'),
  ('a92fc88b-2fbd-56b9-bd97-19fae9f175c8', 'b321daf7-f848-542d-bcb5-73b5db416e55', 'Mobility and stretching, mostly on the floor; not part of the lifting plan.'),
  ('68ef0b6c-594d-55af-aedb-94e065d65c1d', '6d782876-e10e-53ed-8bcb-bb1d9f0acc2f', 'Mobility and stretching, mostly on the floor; not part of the lifting plan.'),
  ('0bdc93a6-77aa-5861-821e-3f0fb714b48c', 'c091a04d-e369-596e-afdd-5daf0d691ccc', 'No head harness for neck work.'),
  ('4abbcdec-0ea5-5df4-8701-7193a0d12e7b', 'f8ff9239-b84c-5b01-9310-6275e94c211b', 'No head harness for neck work.'),
  ('b2e8e3dc-f14d-54ea-b9b7-6418e4a75b04', '581ab31c-86ed-5145-ae7c-238c8afd97e0', 'Mobility and stretching, mostly on the floor; not part of the lifting plan.'),
  ('80841da5-aaf1-565c-a911-b59cff681f96', '55539f72-2b45-5d9f-ba77-b3b257f8b5aa', 'Mobility and stretching, mostly on the floor; not part of the lifting plan.'),
  ('0b363467-291a-5694-b82f-96925215127f', '5dd68d73-793b-59ee-8a5e-06c3ad80a14e', 'Mobility and stretching, mostly on the floor; not part of the lifting plan.'),
  ('7d1abcd6-1f09-5dec-a217-3800658c7b01', '077164db-086c-56e0-ae6b-1273c36ed0f4', 'Jumps, throws and sprint drills: bodyweight or explosive, outside machines and free weights.'),
  ('8dc55513-63d4-5f22-85d8-40fc2575ca23', 'a1ec9a9d-1942-5261-9b49-950d098d85dd', 'Jumps, throws and sprint drills: bodyweight or explosive, outside machines and free weights.'),
  ('7fe9e361-938e-5ddb-a3fa-0d3e43b15a8a', '832975d0-c8cd-51dd-9db4-2805347e8bb4', 'Jumps, throws and sprint drills: bodyweight or explosive, outside machines and free weights.'),
  ('399569f1-3b48-57ed-a6d5-c529401a15fe', '9ea4ecc2-e968-554d-bd27-7baafd1ae322', 'Mobility and stretching, mostly on the floor; not part of the lifting plan.'),
  ('43b89689-0c1a-5492-805a-de13a59c2c12', 'eb57e998-c018-58c2-a9b4-e5423f8df640', 'Bodyweight hang or dip; use the assisted pull-up/dip machine or lat pulldown instead.'),
  ('3a563504-5d1c-5092-a923-6c0e90f05b95', '5f8b88ce-aa35-5dfd-abe4-f18984a70386', 'Bodyweight floor move (mountain climber).'),
  ('3f7fafbe-8e5c-5bfb-aa2e-609546bbd5b1', '3847b4cf-9c7f-5e1f-bb0e-f87fb8998b58', 'Jumps, throws and sprint drills: bodyweight or explosive, outside machines and free weights.'),
  ('ba644e29-1c2b-5fa6-82d0-417d5393c274', '25ba28c7-c36b-5868-b7b8-1f29fc35f1c2', 'Bodyweight hang or dip; use the assisted pull-up/dip machine or lat pulldown instead.'),
  ('59ff1a68-9cf8-5c8b-a9b7-c92984a68756', 'b8bafdc4-8790-5240-bfb0-756f75a20138', 'Bodyweight exercise; Aaron trains with machines and free weights only (SPEC §2).'),
  ('2058c905-05c1-5215-9cc3-b9b1da8c3ed3', '7335eb20-7d14-5184-a0aa-b040c3df0de4', 'Mobility and stretching, mostly on the floor; not part of the lifting plan.'),
  ('550426e5-b709-5655-bca5-52ec688dc497', '219f1013-9ba9-5696-8d61-b1651b3b67a3', 'Floor crunch; cable and machine crunches stay allowed.'),
  ('3c82134e-5701-5a07-9cab-57b1e742ac2f', '3bc2eceb-7a5a-5bd2-ae56-06b60e778d48', 'Floor crunch; cable and machine crunches stay allowed.'),
  ('20fd2e2e-8d17-51fc-805d-d03423adc48f', 'eafaf9df-1664-5fa8-98a2-21013809ec14', 'Mobility and stretching, mostly on the floor; not part of the lifting plan.'),
  ('8e9bc5e2-bfbd-5e33-a3f9-454697feb971', '84c92ef0-6c41-5eea-9981-6778fc36eb99', 'Mobility and stretching, mostly on the floor; not part of the lifting plan.'),
  ('a68375d2-cdd7-5a82-a707-4fb2db3ee1a5', '24cf0257-a6fc-5348-94e8-4e3eb292f327', 'Performed lying on the floor.'),
  ('c329d30b-92cc-5ce9-8823-323992b227c2', '466d4a4c-863a-5998-9211-1fd3f7abb999', 'Mobility and stretching, mostly on the floor; not part of the lifting plan.'),
  ('e9d68fe4-7b2d-57af-b64c-6c3e5c9cfde1', '840dc2bb-c94b-52e7-89d9-979a7fe179ce', 'Bodyweight hang or dip; use the assisted pull-up/dip machine or lat pulldown instead.'),
  ('c1b278e4-39b8-57d3-9f36-7cfdd32c5742', '5ff4a2bf-bb0f-5399-8cc4-32dd049bbeab', 'Performed lying on the floor.'),
  ('b60d9f5e-2a5a-570d-a959-dfb1cab4c66b', '83fa8ae9-dcc5-52eb-ad75-2b98431623c4', 'Mobility and stretching, mostly on the floor; not part of the lifting plan.'),
  ('1edbcb93-6ff8-5000-b71d-2b2966d987d2', 'c3951476-eaee-5f3f-85c9-fc90e0ffdd40', 'Mobility and stretching, mostly on the floor; not part of the lifting plan.'),
  ('18cd62ac-1cde-53d6-bd0d-ee1faa0807cb', '01d801a8-b7f3-59f7-ae1e-c8196c807bff', 'Mobility and stretching, mostly on the floor; not part of the lifting plan.'),
  ('a673b155-51df-5ecf-9d30-7f06bce5aa71', '9cbca38d-5e77-526d-898b-6b08ff411d8e', 'Floor sit-up holding a plate.'),
  ('47eabf09-10b3-57a5-8357-dc7318418ffa', '0feb3e2b-e977-586e-a37b-505e3aee4a84', 'Mobility and stretching, mostly on the floor; not part of the lifting plan.'),
  ('5e69bc28-2712-5202-bfba-4e5ef40b3718', 'ef5b08c1-801a-5fb9-ba55-e1cd98b29e6f', 'Jumps, throws and sprint drills: bodyweight or explosive, outside machines and free weights.'),
  ('3a0ca69a-282e-56d9-9c0a-ff2157cdaad4', 'ca6ef948-cbba-51c9-8de0-16b85612fd2b', 'Mobility and stretching, mostly on the floor; not part of the lifting plan.'),
  ('13797f83-7e09-5d49-9e86-ce72b2c20621', '1343de72-65ec-599b-b077-676b1970c2e7', 'Mobility and stretching, mostly on the floor; not part of the lifting plan.'),
  ('c5270efe-0aca-5ebd-8877-538b28b705eb', '5289626d-3bf6-5e13-a582-3bd58bc2a0bf', 'Bodyweight hang or dip; use the assisted pull-up/dip machine or lat pulldown instead.'),
  ('e59fa325-74d9-59c7-a85f-caa8f919b98c', '61b41ff0-e719-5060-9270-169a58759e07', 'Glute or hip bridge on the floor.'),
  ('442b3e69-fd03-52fc-a48f-a99f9baaba9d', '59375f2c-014b-538c-8a7e-6db422baff28', 'Mobility and stretching, mostly on the floor; not part of the lifting plan.'),
  ('a1c1bd3d-0ad2-574b-922d-536f70b474ee', '52ee858d-4461-5bf7-984e-1dcbd6b2106a', 'Mobility and stretching, mostly on the floor; not part of the lifting plan.'),
  ('a9c9e0e0-6a9e-561b-8267-4896a39c364f', '90ee1830-6351-5cfd-8b65-823df4d45d4a', 'Glute or hip bridge on the floor.'),
  ('556d2aa6-4cef-5e07-881a-ec736c4e879e', 'c8f13646-fd2f-565d-ad27-74601011cace', 'Mobility and stretching, mostly on the floor; not part of the lifting plan.'),
  ('e116b470-0138-5079-96ff-0889d636ad39', 'b74d3f43-a48a-5408-8193-2c51af829463', 'Floor hold (plank).'),
  ('1c209d08-4051-55c2-9de7-61624fde00ff', '93fc043c-0d20-5f0e-88c8-56539addcfca', 'Twist lying on the floor.'),
  ('a5f2d49c-3d3d-51ba-9e22-05f3bd96979e', 'e10d0acc-b666-5a0f-8b04-c1dfd44bbbae', 'Slides are floor work.'),
  ('581b7c2f-26d1-5fcd-aafd-a045ed2be2b5', 'c751e663-621f-5b1d-af3a-491b42444a09', 'Bodyweight push-up.'),
  ('47479464-93cd-591a-9a10-ebdcb0e0f31f', 'aecb0f91-f5ae-57f8-862e-e4158ac54aab', 'Bodyweight push-up.'),
  ('96b1cee4-194c-5a58-b56a-76c6a5a7ecb4', 'a79d7462-87a8-58d7-a04d-0d24efafe31b', 'Mobility and stretching, mostly on the floor; not part of the lifting plan.'),
  ('d7315415-5327-58c3-b654-845a622884d5', '486e0b37-60f8-5fb7-89bb-2c77e244b02b', 'Strongman implements (stones, yokes, tyres, logs, sleds) are not at your gym.'),
  ('605ef66f-4956-51ec-b654-e45fb087b175', '68aefb8b-c47a-588a-a1e6-5ae60c4e2e8e', 'Floor sit-up.'),
  ('a7baa5af-5a63-5932-8c72-6b78416d1552', '41635ae4-0416-5629-a3be-697ab8803a78', 'Bodyweight exercise; Aaron trains with machines and free weights only (SPEC §2).')
) AS v JOIN exercises e ON e.id = v.column2;
--> statement-breakpoint
INSERT OR IGNORE INTO exercise_exclusions (id, exercise_id, reason)
SELECT v.column1, v.column2, v.column3 FROM (VALUES
  ('42eea1be-d8eb-5665-b045-59e31edbb0db', '77285c88-2886-5195-b79c-de8efeceb5d7', 'No sled or prowler at your gym.'),
  ('ab43dd79-f15e-54e7-a067-c3f255d77b8e', '8ab042c0-b37b-50bf-a095-cb79f4aa2234', 'Bodyweight hang or dip; use the assisted pull-up/dip machine or lat pulldown instead.'),
  ('92c72b18-2779-549a-bc90-e9f91c73269a', '939ea623-6677-5ee7-9937-23ca571f0a0b', 'Bodyweight push-up.'),
  ('2a25902f-678a-56b2-ac3f-5bfcb60ce3a9', 'ff847e10-c02c-5601-a66e-d54bc9258c85', 'Bodyweight push-up.'),
  ('dd6c45ec-b6d5-5b38-a3fd-d4bc18e9aec2', 'd9f11ddb-3b8f-5e46-8bd6-7abb5ebf433b', 'Bodyweight push-up.'),
  ('629f91fd-b133-5d7e-981f-df29430b29e1', '521dd7d2-ab86-5b10-ad8f-633025038d1a', 'Bodyweight push-up.'),
  ('c97cd53a-fd9d-57a7-903c-1f219073d170', '8cf92de5-9c4e-550c-aaa2-54cf0efc57d1', 'Floor hold (plank).'),
  ('094d3c43-46e1-5fda-a1f0-0702d1f43ec6', 'b1d33ff6-9b32-5a79-9098-3cdab5e5b15a', 'Bodyweight push-up.'),
  ('f4c3b935-33f5-511f-a717-9b1a71c828c1', '4163421d-ca59-580b-846c-bb7cce62cc6c', 'Bodyweight push-up.'),
  ('513f4842-b80b-523c-a1e6-f1675eb15a9a', '374237f8-0821-5ecb-ab84-b8554678742c', 'Mobility and stretching, mostly on the floor; not part of the lifting plan.'),
  ('a72a00a5-7032-50d9-8b6e-14766affa22e', '459da493-a229-5ab7-99b0-b1b98e7d41e2', 'Mobility and stretching, mostly on the floor; not part of the lifting plan.'),
  ('464135fd-7a3c-55be-8af2-7a9b96361745', 'cfa573ce-5d6d-50b2-a436-c4cb98f1b93f', 'Mobility and stretching, mostly on the floor; not part of the lifting plan.'),
  ('f04420b5-4b49-58aa-b080-1fea943b0239', '5325ff56-2425-5344-9c0a-a892f30e13b8', 'Jumps, throws and sprint drills: bodyweight or explosive, outside machines and free weights.'),
  ('2a1eb2ce-fd0d-576a-95da-69d8ab027942', '4ad6dc01-8319-50a4-9262-51e8da8742e0', 'Mobility and stretching, mostly on the floor; not part of the lifting plan.'),
  ('b1e9ed65-32fd-5203-9e50-865245c04925', '661507f9-f5d9-510b-bb16-286a813f2f5d', 'Jumps, throws and sprint drills: bodyweight or explosive, outside machines and free weights.'),
  ('9c9a6f3e-2620-5d5e-b3a5-300d24580ea8', '95dc9de9-e8bb-5c05-8d9f-d1e4b916e052', 'Resistance bands are not at your gym.'),
  ('8ada8480-ebb5-562d-badb-c70a3f2488c6', '81c67a24-b660-5dee-ae8c-6ebe8797e510', 'Resistance bands are not at your gym.'),
  ('27227619-8258-5fc5-84b6-80a0734b1b66', '8c5a755e-5a40-5356-b84d-997b08f166c4', 'Resistance bands are not at your gym.'),
  ('fa04f319-2db7-50c5-90a4-8f99e52b7c30', '5cda78ab-c8a3-583c-b931-a6adbd086681', 'Resistance bands are not at your gym.'),
  ('122fda44-57af-552d-a270-d3f9c5db9151', 'e83715bc-98b5-58ce-a98d-30ce341220ba', 'Resistance bands are not at your gym.'),
  ('6bdca15a-5b27-5340-9f6a-fb67db471b0f', 'ee0f9d1c-69e4-5403-8091-06aad41c5bba', 'Floor crunch; cable and machine crunches stay allowed.'),
  ('ec086f7c-51b9-5362-9261-1d5aa0cadcbc', '4038fa95-a309-53a2-8abb-9d9848d9fd16', 'Mobility and stretching, mostly on the floor; not part of the lifting plan.'),
  ('e532f5bb-0d79-5068-b430-6309e5331ab1', 'efcf4978-be60-51c7-8d79-329c7be67800', 'Strongman implements (stones, yokes, tyres, logs, sleds) are not at your gym.'),
  ('d71913f2-8199-5a67-aeb4-d44400f50b76', 'd4bcee5d-a0ca-51e1-b89c-8d8bd1ff2771', 'Strongman implements (stones, yokes, tyres, logs, sleds) are not at your gym.'),
  ('9a7abef9-1481-51bc-877a-027d22ab64dc', 'fce5d102-5d8a-5391-aba8-1f2b5231dcbe', 'Bodyweight hang or dip; use the assisted pull-up/dip machine or lat pulldown instead.'),
  ('208b8f06-b408-5cb8-9c8e-b3b51e028965', '613d23da-831c-5dbd-bba2-08537b616b45', 'Jumps, throws and sprint drills: bodyweight or explosive, outside machines and free weights.'),
  ('62dd84a2-983f-5d63-9db3-0c09387d5d9b', '2960c2f8-93e0-567d-b1a1-fa8c2af9a8a2', 'Bodyweight hang or dip; use the assisted pull-up/dip machine or lat pulldown instead.'),
  ('2cc2b238-25f1-5392-aa4d-8de282e21577', 'd23321f4-3700-55d3-bf62-409c2779af2e', 'No climbing rope at your gym.'),
  ('061f0066-6fb9-5017-ae5a-d9b112362274', '022e10be-a16f-5883-bbd1-babdd48a7154', 'Mobility and stretching, mostly on the floor; not part of the lifting plan.'),
  ('1131382f-ee5d-5e7d-bc9d-720c7fd20c25', 'e8c0a8b1-4e59-53eb-85be-d37a42daa12d', 'Mobility and stretching, mostly on the floor; not part of the lifting plan.'),
  ('51f4f53b-ffca-55d8-8aa2-0a12207019b8', '0fe7c9fe-a375-53b0-b59f-45ac7f644e04', 'Bodyweight exercise; Aaron trains with machines and free weights only (SPEC §2).'),
  ('01a3c4de-e747-5f68-a1dd-2f98d54581ca', '9fa51704-d113-5710-85d1-cbe1b8a3e8b2', 'Strongman implements (stones, yokes, tyres, logs, sleds) are not at your gym.'),
  ('ed1a2b12-1962-5189-897e-5dd83e28d550', '1d0d9309-06ad-529d-819d-ec6ed0290d07', 'Bodyweight hang or dip; use the assisted pull-up/dip machine or lat pulldown instead.'),
  ('0b8457f5-b367-5d2c-bd96-b47cff091a7e', 'eba326e0-bff1-53c0-807e-d1bd10af61d2', 'Mobility and stretching, mostly on the floor; not part of the lifting plan.'),
  ('dc75d2ea-7294-5f94-b571-caeb4574a1c8', '19712e9e-dcad-56c2-b094-937d4f431204', 'Jumps, throws and sprint drills: bodyweight or explosive, outside machines and free weights.'),
  ('69b800c4-fcd7-58d2-9ea1-7dedadc3a3af', '8955c150-1eb2-59ff-b530-4e182b9d8c58', 'Resistance bands are not at your gym.'),
  ('3be556d2-b541-5784-a6b7-eb87dede6346', 'b0ab24f0-ff4c-5c76-aa35-437f765b300b', 'Mobility and stretching, mostly on the floor; not part of the lifting plan.'),
  ('c81a0426-fabc-5965-92d9-8b65f573326a', '0f2297b8-7d5c-57e9-90a4-02a738dec34e', 'No seated calf machine: standing calf raise and the leg press footplate cover it (a barbell seated calf raise is still allowed).'),
  ('e40db6f4-5e3e-55e3-929d-466af4025e02', 'ab40431c-b0b2-5aa5-9cda-8b001a64a457', 'Mobility and stretching, mostly on the floor; not part of the lifting plan.'),
  ('10a5b643-939d-51d5-a2ed-d7d80acb9a9b', 'fc191cbe-c370-507a-bcb9-c07eac5985ff', 'Bodyweight exercise; Aaron trains with machines and free weights only (SPEC §2).'),
  ('3e121e31-9d5c-54b0-b5ef-848110b000bf', 'f5260069-798f-57d9-bedb-0e64a34b705c', 'Performed lying on the floor.'),
  ('8f39dd02-23b2-597e-b217-17f5808089d5', 'b72c408d-1cae-5b54-8a3c-e50149bd8d88', 'Mobility and stretching, mostly on the floor; not part of the lifting plan.'),
  ('b78d5990-9d95-5b05-92d5-5f756438a37d', 'df68ad35-a81c-514b-bb02-4efc55d03fd2', 'Mobility and stretching, mostly on the floor; not part of the lifting plan.'),
  ('8c20587b-7d42-5738-8908-e500f79c469b', '29d8357c-2d93-57da-b480-81b506e1272d', 'Mobility and stretching, mostly on the floor; not part of the lifting plan.'),
  ('5d6d83f3-53fd-5101-ac19-f1adf00703d3', 'a4badedf-77e9-5b83-ad81-44ae6199b6da', 'Mobility and stretching, mostly on the floor; not part of the lifting plan.'),
  ('de3dccdb-37b0-5cf5-bd13-0b4d0c08c143', 'bb88f6f9-8543-53b3-827b-8f68fbc37209', 'No head harness for neck work.'),
  ('d66a0ce5-6637-5169-a5e0-eb7974703ab3', 'f30989a7-99c6-5995-9e58-314529d59ea9', 'Bodyweight exercise; Aaron trains with machines and free weights only (SPEC §2).'),
  ('634f00ab-0b27-56a4-94d6-285256088801', 'f718e795-eef9-537f-9911-5afb69784964', 'Mobility and stretching, mostly on the floor; not part of the lifting plan.'),
  ('6b505459-9f9e-5293-b89d-e87637592f93', '8d66dd35-6da0-5f93-bc32-2e01c42c2b7d', 'Mobility and stretching, mostly on the floor; not part of the lifting plan.'),
  ('c14e252f-c013-59af-9de7-4e3ae05721be', '1670ceb3-9cb4-5b94-8b77-66f115ce8b57', 'Mobility and stretching, mostly on the floor; not part of the lifting plan.')
) AS v JOIN exercises e ON e.id = v.column2;
--> statement-breakpoint
INSERT OR IGNORE INTO exercise_exclusions (id, exercise_id, reason)
SELECT v.column1, v.column2, v.column3 FROM (VALUES
  ('2f780607-4bfa-5068-acf6-d27d889f741e', '7fd8c0b2-afe4-5664-bea1-2ac27440bdfa', 'Mobility and stretching, mostly on the floor; not part of the lifting plan.'),
  ('279739da-4211-511f-a7cc-4861c7eb0665', '3d9296a0-690b-5cf0-9996-cf0940a4f0d3', 'Performed lying on the floor.'),
  ('bf1ed87e-ec1b-5987-b9a0-71d4ffc0fc7c', 'cbdecacf-a4e9-5290-a111-3183f6a319f8', 'Glute or hip bridge on the floor.'),
  ('2d0f802b-18fc-5433-b921-914803e86766', 'ecee7a5e-2773-51cb-b778-c39df32e6398', 'Jumps, throws and sprint drills: bodyweight or explosive, outside machines and free weights.'),
  ('8fb516cc-be9c-572e-b3e4-892a9cde9856', '4d026d23-d30c-5fc2-8021-1d0bab3a6357', 'Bodyweight exercise; Aaron trains with machines and free weights only (SPEC §2).'),
  ('2a9b51fa-469a-5448-8e0e-e6939a88e678', 'cc053c37-affc-50ee-b370-74f6bfd5f273', 'Mobility and stretching, mostly on the floor; not part of the lifting plan.'),
  ('1793e445-88e1-58d4-a1be-ed0527c03151', '5aadab22-18de-5504-801f-2c495df57b53', 'Mobility and stretching, mostly on the floor; not part of the lifting plan.'),
  ('970fada8-9ec9-59a8-8a81-ba714f1a989d', '4cf4b8ff-fb00-51b7-8536-60498e31e661', 'Mobility and stretching, mostly on the floor; not part of the lifting plan.'),
  ('0182e8b0-a0e2-5def-838f-cb09209a1f15', '25314ef3-02d8-59ad-a7af-1cd9d592ce41', 'Jumps, throws and sprint drills: bodyweight or explosive, outside machines and free weights.'),
  ('d3fed24f-b289-5447-85e3-b1f88e0d2521', 'ef7a9237-4019-5292-8ef4-82e8008624b5', 'Bodyweight hang or dip; use the assisted pull-up/dip machine or lat pulldown instead.'),
  ('8a5c1d0e-1006-5d71-a39b-f49a606f94b3', '3a6ddf1d-3dae-589d-916a-495015152bf2', 'Mobility and stretching, mostly on the floor; not part of the lifting plan.'),
  ('359b1a49-c500-5b06-82d5-1fef48ae40e4', 'f9e2ec02-a22d-5b98-beb6-58f4a942d284', 'Jumps, throws and sprint drills: bodyweight or explosive, outside machines and free weights.'),
  ('ca315eb0-503b-5721-acec-6aa30e3c851c', '0661443b-35b3-5eee-8888-5df589cf4d7c', 'Bodyweight push-up.'),
  ('548eaf02-0c98-5e2e-b0e3-63239a327e8c', 'e10ac205-facc-53eb-8816-036b506fef3b', 'Jumps, throws and sprint drills: bodyweight or explosive, outside machines and free weights.'),
  ('acfdc295-711c-59c7-a685-c7102d251d40', 'bcc70d7f-1f57-52e7-b590-65dc5f7791b9', 'No plyo box at your gym.'),
  ('dee840f7-4603-5503-9f18-0a8fa1d88856', 'df09f36f-8e72-5367-8f2c-a2e24fc3efe9', 'Jumps, throws and sprint drills: bodyweight or explosive, outside machines and free weights.'),
  ('ed85b385-55a2-5519-aaeb-dae4d523f662', '9474e856-79d4-56cc-82c9-296e411f4d74', 'Jumps, throws and sprint drills: bodyweight or explosive, outside machines and free weights.'),
  ('4b0f64fe-6653-5444-8c15-7004a1b03aff', 'fd8d11d1-a99d-5278-8894-ed50dd329f14', 'Jumps, throws and sprint drills: bodyweight or explosive, outside machines and free weights.'),
  ('aa98380d-c0f6-518c-ba0a-8591ef266f09', '1239a31f-8225-560a-bf6d-f8c7c4220128', 'Jumps, throws and sprint drills: bodyweight or explosive, outside machines and free weights.'),
  ('b2d09ae4-b110-52c3-a4a4-5b817af98177', 'f83d622c-f61e-53de-8b28-c72a86c31cbd', 'Glute or hip bridge on the floor.'),
  ('ca9aa041-039e-5108-a659-86779081eb0a', '743573b2-fc13-5d46-b6af-b4953d8ace58', 'Jumps, throws and sprint drills: bodyweight or explosive, outside machines and free weights.'),
  ('0e385e73-d3fe-53f2-b1ad-9733062fd244', '3f3b2f44-4e5d-5bea-b867-88080f3b5ce0', 'Floor sit-up.'),
  ('860ae4fb-02b1-5a6e-a4b7-75807fc94908', 'ad40dddf-2c92-572f-9d15-af837824cec1', 'Mobility and stretching, mostly on the floor; not part of the lifting plan.'),
  ('59500147-949e-5054-b9f1-a79221169ae8', 'b85e7923-18bf-588f-9346-cb6e77aee829', 'No sled or prowler at your gym.'),
  ('4765cfe1-6979-5991-a4d8-2ea48b60dcde', '9e982c4f-7aea-5620-8550-aa1e4c12dc55', 'No sled or prowler at your gym.'),
  ('016e5b86-9f72-5a19-bcaf-2398dd7f1cc9', '5940b4c3-959f-5c9d-8752-24a4886ff8ee', 'No sled or prowler at your gym.'),
  ('1fb20274-e1fc-59a5-b4e6-de2d5d3a2c20', '553e8a93-9a8b-56d6-9918-0346f323ac81', 'No sled or prowler at your gym.'),
  ('a9c9e52d-fe54-56dc-9dcc-fb8d8e369ba0', '3e5ece28-db6b-5da8-aae9-018080461176', 'No sled or prowler at your gym.'),
  ('7633a629-0fc1-597a-84aa-83766abb58ab', 'd85afd4b-7729-5888-8915-66b2531c4ff3', 'No sled or prowler at your gym.'),
  ('c9edd858-1679-5e60-ad5a-3cbe8dc74c30', '4814917e-4344-5d1c-88b3-1308d32e5397', 'No sledgehammer at your gym.'),
  ('9fa3e280-1e53-538a-b4ff-6568281500e0', '48010a60-dd7d-5e55-a4fd-98a423a3fe2f', 'Resistance bands are not at your gym.'),
  ('0ad67a3f-4647-5fcb-86d8-2942c45d20c6', '1fd62fc2-dc72-593e-821b-469452faf17b', 'Bodyweight exercise; Aaron trains with machines and free weights only (SPEC §2).'),
  ('a28d3bc2-1b9e-5abd-b23d-1ff6192d3499', '90586ad2-2564-51da-aea5-878c2d8cd799', 'Mobility and stretching, mostly on the floor; not part of the lifting plan.'),
  ('12fb04e9-d108-5b6d-84b3-dbadc63ab691', '1a4f4f21-7b29-52d6-94ce-d1f403506f68', 'Jumps, throws and sprint drills: bodyweight or explosive, outside machines and free weights.'),
  ('07ca9955-8835-57fc-9ac4-7388eb66aa9e', '45ad3501-4068-5d95-a497-49ce2965a99d', 'Mobility and stretching, mostly on the floor; not part of the lifting plan.'),
  ('c18848d7-45cd-5051-bb8a-0fdb14994239', '28eabf24-c047-508c-a10b-979f924e18c0', 'No chains at your gym; the racks and plates cover the same lifts.'),
  ('bfee66c7-4500-5e66-a339-20b0344eb480', 'c3ee8f34-a23d-5727-9e3b-7eee60b6c73e', 'Mobility and stretching, mostly on the floor; not part of the lifting plan.'),
  ('8a28320b-9266-5936-a30a-d76f4b5e691e', 'fa40654e-8e78-50b7-a2cd-4ee53bab9167', 'Mobility and stretching, mostly on the floor; not part of the lifting plan.'),
  ('1fb547a3-efe6-5f33-81f3-cda910a5140f', 'fbcf73b3-8a37-51ce-9409-ba4845e84225', 'Mobility and stretching, mostly on the floor; not part of the lifting plan.'),
  ('2c42d42e-54fe-5838-bcf7-afef1de52b87', 'cca5bdea-48c0-51b5-a111-058957ae9d1c', 'Mobility and stretching, mostly on the floor; not part of the lifting plan.'),
  ('6705d848-bc8c-59eb-b747-a29c4fe42a2b', 'b1fddb84-8e3a-55ee-9c13-b32c401eef2a', 'Mobility and stretching, mostly on the floor; not part of the lifting plan.'),
  ('8abf2793-eca5-5e2a-a9c8-6baf09aac842', 'b9b82b39-fc3f-5ba7-b523-025700a8d8f9', 'Mobility and stretching, mostly on the floor; not part of the lifting plan.'),
  ('401b843a-4a48-52f4-927c-324b314ff31f', '03ff5361-b6c8-564b-ad42-fa0149df99a9', 'Mobility and stretching, mostly on the floor; not part of the lifting plan.'),
  ('baf80e1d-9259-52d1-909b-991d67dba023', '45350366-c7b4-50a4-902f-e8123d505bca', 'Jumps, throws and sprint drills: bodyweight or explosive, outside machines and free weights.'),
  ('8a431af4-f574-5b16-8308-e39013d86b49', '0adb10e4-9fd7-5cda-9154-0b1681ff794b', 'Mobility and stretching, mostly on the floor; not part of the lifting plan.'),
  ('5236eb9d-2f15-5854-9a25-94cee38ed192', 'fdba579b-b055-51b4-9656-f8e5f909828b', 'Mobility and stretching, mostly on the floor; not part of the lifting plan.'),
  ('19fe7d0c-d4f3-583e-9f90-578b2bdaecba', '82cd7156-0714-50e3-ab4e-0f24424af046', 'Mobility and stretching, mostly on the floor; not part of the lifting plan.'),
  ('59deb95a-5c0e-5c57-9453-10b0bb981801', 'e1d9fb28-a25f-5299-bfcf-065025b41b59', 'Bodyweight exercise; Aaron trains with machines and free weights only (SPEC §2).'),
  ('b06e557e-e9c4-5f23-adfd-4460aef31f19', '43f76ebc-c13d-5bdc-86da-7a55a8af6e86', 'Jumps, throws and sprint drills: bodyweight or explosive, outside machines and free weights.'),
  ('563e33ae-30e3-5f72-8d36-44209a4af510', '43c7c0a9-f7d6-5bba-ad6b-39f3e5eef4f3', 'Jumps, throws and sprint drills: bodyweight or explosive, outside machines and free weights.')
) AS v JOIN exercises e ON e.id = v.column2;
--> statement-breakpoint
INSERT OR IGNORE INTO exercise_exclusions (id, exercise_id, reason)
SELECT v.column1, v.column2, v.column3 FROM (VALUES
  ('a23b25bf-3174-501b-9871-63b7fc04a3f3', '3d0b34ec-2811-5ddc-9738-65221fd5b124', 'Bodyweight exercise; Aaron trains with machines and free weights only (SPEC §2).'),
  ('f7a337e8-41bb-5f0b-8f69-e8cc65b7d797', '0efb32eb-b4d5-5556-9f42-e4b10edb28e8', 'Mobility and stretching, mostly on the floor; not part of the lifting plan.'),
  ('62728c74-2a08-5726-afad-c59ab2437083', 'accdc23f-1c47-5451-9ca5-79bc8276ccaa', 'Jumps, throws and sprint drills: bodyweight or explosive, outside machines and free weights.'),
  ('4e5d232c-e8bb-5f8a-ab6b-acb6c9bae654', '50105bba-0725-5404-b7c8-119d77e7b15e', 'No chains at your gym; the racks and plates cover the same lifts.'),
  ('530ce05a-a24b-5e5d-9c02-b999c6675e76', '3adfb9b6-0cd3-59df-82d4-2ee9553f0f0f', 'Floor back extension (superman).'),
  ('00282fab-ad0b-544d-a373-4e5ce00014c8', 'd60fa08b-224f-59f5-b38b-cceb05c73a96', 'Jumps, throws and sprint drills: bodyweight or explosive, outside machines and free weights.'),
  ('61c9b839-dd46-5406-9135-27872e4ead9b', '848ed284-8d34-56fe-b1fa-1d9671137b97', 'Jumps, throws and sprint drills: bodyweight or explosive, outside machines and free weights.'),
  ('ec2b879a-2f30-56e9-a18b-b0efe2b3fe3e', '6494a785-fcce-590d-b002-bda600eaa916', 'Jumps, throws and sprint drills: bodyweight or explosive, outside machines and free weights.'),
  ('2f49ffb3-f33b-50d3-b768-1c03d00d96d8', '7efe471e-4d56-5ec0-9283-728cb88b2d3e', 'Suspension-trainer bodyweight move.'),
  ('fb708fdb-2360-5765-8bc1-37cca7a16f37', '8f2e6846-ee4e-56bd-bbab-ad808c5dabae', 'Bodyweight push-up.'),
  ('bcbc7ed7-d49b-54c2-8668-18b1ce5ebf1e', '8759c331-5952-552b-ae9b-73b52e41e947', 'Floor crunch; cable and machine crunches stay allowed.'),
  ('f0638f27-fc09-5d6f-a3e3-cea217f48959', '895852db-c9fb-53d4-9209-3bc5188312bd', 'Suspension-trainer bodyweight move.'),
  ('3bf53e7d-d875-5183-9d95-2393526be336', '8aeb9468-8619-5b85-8eaa-a760a24f45ed', 'Suspension-trainer bodyweight move.'),
  ('84115935-6591-5bd2-8fd7-c46315eb3331', '4c137da2-0029-53bc-9200-906b07b592a1', 'Mobility and stretching, mostly on the floor; not part of the lifting plan.'),
  ('3f9f0215-2e68-5254-9a76-5200e9a3653d', 'a062e719-ac7f-5d1c-95dd-19b3b19e0943', 'Strongman implements (stones, yokes, tyres, logs, sleds) are not at your gym.'),
  ('8d75bd5b-ade7-5167-9283-163cf7f87878', '5f40563e-6156-530d-9612-7b2fa31c2873', 'Mobility and stretching, mostly on the floor; not part of the lifting plan.'),
  ('91544866-10d0-5fe0-a1c1-9b554b730036', '61f10fd0-c4df-58bf-95eb-ec9163235e21', 'Mobility and stretching, mostly on the floor; not part of the lifting plan.'),
  ('3ed61070-e474-5b36-8ac7-f4f4d41c40a8', '88f9a7a4-98e0-5d3b-a8e9-ca5ae5312c8f', 'Bodyweight exercise; Aaron trains with machines and free weights only (SPEC §2).'),
  ('5d7cd7e5-4585-5840-bc10-202f106ae70d', '2e2a9e12-646c-5bfc-be46-978a7f66daef', 'No trap bar at your gym; deadlift with a bar or dumbbells.'),
  ('6dff5ae1-4c27-59ae-b0bc-aa85265f8313', '02e9ef42-6ff0-596e-9c3f-e950812a6363', 'Mobility and stretching, mostly on the floor; not part of the lifting plan.'),
  ('5a84c9d7-95c5-53d2-a4c5-100fb54e4e1d', '5eedc3d0-8649-5b3b-b742-73078d294c7e', 'Mobility and stretching, mostly on the floor; not part of the lifting plan.'),
  ('42238b58-d525-5009-965e-33dba867f193', '1629c2d3-30ef-5d37-97b7-1cb60dd35331', 'Floor crunch; cable and machine crunches stay allowed.'),
  ('ac6ef7bd-6ce4-516c-bab3-7310c05e901e', 'd2748940-71e9-5b01-95f7-c810b7f8d327', 'Mobility and stretching, mostly on the floor; not part of the lifting plan.'),
  ('44547cd1-66b5-5fb6-bc24-a386ad715e06', '33f922fc-bcf8-5fb8-aea2-fe6720669ac2', 'Mobility and stretching, mostly on the floor; not part of the lifting plan.'),
  ('ecefcfb1-0180-5c72-95d9-ec4bae9e3a64', '618c7d75-917a-5b9c-9e68-902357b36f4d', 'Mobility and stretching, mostly on the floor; not part of the lifting plan.'),
  ('30277813-b73b-5a27-955c-971afbc5ff91', '06590fcf-30e0-5520-ab50-36244aab20f7', 'Bodyweight hang or dip; use the assisted pull-up/dip machine or lat pulldown instead.'),
  ('47bfe8af-9d04-57a7-8318-478590e0c722', '5e9f24f7-b008-594f-b6ce-3a47a6ff268b', 'Jumps, throws and sprint drills: bodyweight or explosive, outside machines and free weights.'),
  ('73278e89-dcc1-5a60-8252-d89316336185', '6673122f-3225-5814-9341-c7656e5eba3b', 'Bodyweight hang or dip; use the assisted pull-up/dip machine or lat pulldown instead.'),
  ('9c382ef2-ee47-532e-95d2-38fe3d112e10', '4644316a-1535-5e18-a845-906b32d8d44a', 'Floor crunch; cable and machine crunches stay allowed.'),
  ('2b292312-e3fd-51f1-81ee-1cc84b6336b2', '78c0a274-99a1-52ae-aff5-df470c299051', 'Bodyweight hang or dip; use the assisted pull-up/dip machine or lat pulldown instead.'),
  ('7d669e30-5b7a-5e51-b9c1-58a189fa0e5d', '4af1d087-c288-59c7-9576-76ca598dbf2a', 'Floor sit-up.'),
  ('72ab4a8e-55a6-5b70-853a-bc0502b589c7', '10e8747a-2cd6-5b5b-bbc6-195d994120b3', 'Bodyweight hang or dip; use the assisted pull-up/dip machine or lat pulldown instead.'),
  ('40e4ba4c-faca-53a5-99e1-cb55d72ee885', '81dcc4b6-8032-523b-80bf-fea67694ef06', 'Bodyweight exercise; Aaron trains with machines and free weights only (SPEC §2).'),
  ('3f4b1a6d-d3d2-510d-920b-08a716a42902', '58631125-92cd-50a9-b59e-a615d1886dfb', 'Mobility and stretching, mostly on the floor; not part of the lifting plan.'),
  ('46e3c212-07ca-5203-a9c3-af2199deac21', 'e851d94d-b9bd-5b42-9e17-92e02e80d815', 'Mobility and stretching, mostly on the floor; not part of the lifting plan.'),
  ('3e67a913-5072-57c1-9575-f0597b63fe3a', 'c4f07f37-3c7b-51c4-88e3-b066044d5a47', 'Mobility and stretching, mostly on the floor; not part of the lifting plan.'),
  ('886dc8bc-949d-5591-9442-436b13226067', '778b7a43-0b88-522a-893e-a34367155483', 'No wrist roller at your gym.'),
  ('d39bc20b-5340-5936-88b2-3c492988b902', '71777c4a-74b2-5c67-9670-71eb66d662d4', 'Strongman implements (stones, yokes, tyres, logs, sleds) are not at your gym.')
) AS v JOIN exercises e ON e.id = v.column2;
